
SELECT*FROM Dbamv.pre_med
WHERE dT_PRE_MED BETWEEN To_Date ('15082022','DD/MM/YYYY') AND To_Date ('16082022','DD/MM/YYYY')
--AND CD_ATENDIMENTO = '2900133'
AND CD_PRE_MED IN ('6299209')
ORDER BY CD_PRE_MED desc
;

select*from dbamv.solsai_pro
;

select*from prestador
where cd_prestador = '10687';

--SITUA플O DE PRODUTOS NA SOLICITA합ES
SELECT
SSP.CD_SOLSAI_PRO,
SSP.CD_SETOR,
SSP.CD_ESTOQUE,
Decode (SSP.TP_SITUACAO,'S','CONFIRMADO','A','CANCELADO','P','PEDIDO','C','PARCIAL') AS TIPO_SOLICITACAO,
SSP.DS_OBS,
SSP.DT_GRAVACAO LIBERADO_EM,
SSP.CD_ATENDIMENTO,
SSP.DT_SOLSAI_PRO,
SSP.CD_PRE_MED,
ITS.CD_PRODUTO,
PR.DS_PRODUTO,
ITS.QT_ATENDIDA,
SSP.DT_CANCELAMENTO CANCELADO_EM
FROM dbamv.solsai_pro SSP
LEFT JOIN ITSOLSAI_PRO ITS ON ITS.CD_SOLSAI_PRO = SSP.CD_SOLSAI_PRO
LEFT JOIN ESTOQUE EST ON EST.CD_ESTOQUE = SSP.CD_ESTOQUE
LEFT JOIN PRODUTO PR ON PR.CD_PRODUTO = ITS.CD_PRODUTO
WHERE SSP.DT_SOLSAI_PRO BETWEEN To_Date ('24082022','DD/MM/YYYY') AND To_Date ('25082022','DD/MM/YYYY')
AND SSP.CD_ATENDIMENTO = '3012625'
--AND SSP.TP_SITUACAO = 'A'
--AND SSP.CD_PRE_MED = 6299209
--AND SSP.CD_SOLSAI_PRO = '12021303'
ORDER BY DT_SOLSAI_PRO DESC, TIPO_SOLICITACAO DESC
;
-- SITUA플O DE PRODUTOS NA PRESCRI플O MEDICA
SELECT
PM.CD_ATENDIMENTO,
PM.CD_SETOR,
PM.CD_PRE_MED,
ITP.CD_ITPRE_MED,
ITP.DH_INICIAL,
ITP.CD_PRODUTO,
P.DS_PRODUTO,
ITP.DH_CANCELADO,
ITP.CD_PREST_CANC,
S.CD_SOLSAI_PRO,
S.CD_ESTOQUE,
S.DT_SOLSAI_PRO,
S.TP_SITUACAO
FROM dbamv.pre_med PM
LEFT JOIN dbamv.itpre_med ITP ON ITP.CD_PRE_MED = PM.CD_PRE_MED
LEFT JOIN dbamv.solsai_pro S ON S.CD_SOLSAI_PRO = PM.CD_SOLSAI_PRO
LEFT JOIN dbamv.produto P ON P.CD_PRODUTO = ITP.CD_PRODUTO
LEFT JOIN ESTOQUE EST ON EST.CD_ESTOQUE = S.CD_ESTOQUE
WHERE PM.DT_PRE_MED BETWEEN To_Date ('01082022','DD/MM/YYYY') AND To_Date ('03082022','DD/MM/YYYY')
AND PM.CD_ATENDIMENTO = '2958199'
AND PM.CD_PRE_MED = '6242285'
--AND S.CD_SOLSAI_PRO = '12106427'
ORDER BY PM.CD_PRE_MED DESC,ITP.CD_PRODUTO DESC;

-- SITUA플O DE CANCELAMENTO DE PRESCRI합ES
SELECT
PM.CD_PRE_MED NUMERO_PRESCRICAO,
PM.CD_ATENDIMENTO ATENDIMENTO,
PM.CD_PRESTADOR MEDICO,
P.NM_PRESTADOR NOME_COMPLETO,
PM.HR_PRE_MED VALIDADE_INICIAL,
PM.DT_VALIDADE VALIDADE_FINAL,
PM.CD_SETOR N_SETOR,
S.NM_SETOR NOME_SETOR,
PM.DH_CRIACAO CRIADO_EM,
Decode(PM.SN_COPIADA,'N','SIM','S','NAO') AS COPIADO FROM Dbamv.pre_med PM
LEFT JOIN SETOR S ON S.CD_SETOR = PM.CD_SETOR
LEFT JOIN PRESTADOR P ON P.CD_PRESTADOR = PM.CD_PRESTADOR
WHERE dT_PRE_MED BETWEEN To_Date ('15082022','DD/MM/YYYY') AND To_Date ('16082022','DD/MM/YYYY')
--AND CD_ATENDIMENTO = '2900133'
AND CD_PRE_MED IN ('6299209')
ORDER BY CD_PRE_MED DESC;


