SELECT
To_Char (SSP.AUDIT_DT_REGISTRO,'DD/MM/YYYY HH24:MI:ss') REG
,SSP.AUDIT_CD_MODULO
,SSP.CD_SOLSAI_PRO
,SSP.TP_SOLSAI_PRO
,SSP.CD_SETOR
,SSP.CD_ESTOQUE
,SSP.TP_SITUACAO
,SSP.CD_PRE_MED
,SSP.DT_SOLSAI_PRO
,SSP.DS_OBS
,ISP.CD_PRODUTO

 from AUDIT_DBAMV.SOLSAI_PRO SSP  , DBAMV.ITSOLSAI_PRO ISP
WHERE SSP.CD_SOLSAI_PRO = ISP.CD_SOLSAI_PRO
AND SSP.CD_PRE_MED = 8457191
 AND SSP.CD_SOLSAI_PRO IN (17194777, 17194776, 17194778,17194775)
ORDER BY 1, 3
