--CADASTRO PARA DOAÇÕES DO BANCO DE LEITE
CREATE TABLE EDITOR_CUSTOM.CAD_BL (
  NM_PACIENTE VARCHAR2(255),
    CD_CPF VARCHAR2(30) PRIMARY KEY,
    DT_NASCIMENTO VARCHAR2(30)
);

INSERT INTO EDITOR_CUSTOM.CAD_BL (NM_PACIENTE, CD_CPF, DT_NASCIMENTO) 
SELECT DISTINCT P.NM_PACIENTE, P.NR_CPF, p.DT_NASCIMENTO  FROM PACIENTE P, ATENDIME A
WHERE P.CD_PACIENTE = A.CD_PACIENTE
AND P. tp_sexo = 'F'
AND P.nr_cpf IS NOT NULL
AND P.dt_nascimento IS NOT NULL
;

SELECT * FROM EDITOR_CUSTOM.CAD_BL
ORDER BY 1
;

CREATE OR REPLACE PROCEDURE EDITOR_CUSTOM.PRC_CAD_BL(
NM_PACIENTE VARCHAR2,
CD_CPF VARCHAR2,
DT_NASCIMENTO VARCHAR2
) IS

BEGIN
INSERT INTO EDITOR_CUSTOM.CAD_BL
VALUES (NM_PACIENTE, CD_CPF, DT_NASCIMENTO);
COMMIT;
END;
/
;

GRANT EXECUTE ON EDITOR_CUSTOM.PRC_CAD_BL TO EDITOR
;

SELECT 
DATE (EDITOR_CUSTOM.CAD_BL.DT_NASCIMENTO,'DD/MM/YYYY') AS 'DATA' FROM EDITOR_CUSTOM.CAD_BL
WHERE NM_PACIENTE LIKE 'MASSA%'
