SELECT 
PA.CD_PERFIL_ALERTA
,PA.PERFIL
,TO_CHAR(A.DT_ATENDIMENTO, 'DD/MM/YYYY') DT_ATENDIMENTO
,A.CD_ATENDIMENTO
,P.CD_PACIENTE
,P.NM_PACIENTE
,TO_CHAR(P.DT_NASCIMENTO, 'DD/MM/YYYY') DT_NASCIMENTO
,PR.CD_PRESTADOR
,PR.NM_PRESTADOR
,ESP.CD_ESPECIALID
,ESP.DS_ESPECIALID
,(SELECT ESP.CD_ESPECIALID FROM DBAMV.ESPECIALID ESP, DBAMV.ESP_MED EMD WHERE EMD.CD_ESPECIALID = ESP.CD_ESPECIALID AND EMD.CD_PRESTADOR = PR.CD_PRESTADOR ORDER BY SN_ESPECIAL_PRINCIPAL DESC OFFSET 1 ROW FETCH FIRST 1 ROW ONLY) AS CD_EPECIALID_SEC
,(SELECT DS_ESPECIALID FROM DBAMV.ESPECIALID ESP, DBAMV.ESP_MED EMD WHERE EMD.CD_ESPECIALID = ESP.CD_ESPECIALID AND EMD.CD_PRESTADOR = PR.CD_PRESTADOR ORDER BY SN_ESPECIAL_PRINCIPAL DESC OFFSET 1 ROW FETCH FIRST 1 ROW ONLY) AS DS_EPECIALID_SEC
,CASE 
                  WHEN PR.CD_PRESTADOR = 11957 THEN 'MEDICO DA FAMILIA'
                  WHEN PR.CD_PRESTADOR = 11939 THEN 'MEDICO DA FAMILIA'
                  WHEN PR.CD_PRESTADOR = 12040 THEN 'MEDICO DA FAMILIA'
                  WHEN PR.CD_PRESTADOR = 11922 THEN 'MEDICO DA FAMILIA'
                  WHEN PR.CD_PRESTADOR = 11924 THEN 'MEDICO DA FAMILIA'
                  WHEN PR.CD_PRESTADOR = 11925 THEN 'MEDICO DA FAMILIA'
                  ELSE 'OUTROS' END AS SERVICO
,A.CD_TIP_RES
,TR.DS_TIP_RES AS "TIPO ENCAMINHAMENTO"
FROM 
  DBAMV.ATENDIME A
  ,DBAMV.PACIENTE P
  ,DBAMV.PRESTADOR PR
  ,DBAMV.ESP_MED EMD
  ,DBAMV.ESPECIALID ESP
  ,DBAMV.PERFIL_ALERTA_PACIENTE PAP
  ,DBAMV.PERFIL_ALERTA PA
  ,DBAMV.TIP_RES TR
  --RELACIONAMENTOS
  WHERE A.CD_PACIENTE = P.CD_PACIENTE
  AND A.CD_PRESTADOR = PR.CD_PRESTADOR
  AND PR.CD_PRESTADOR = EMD.CD_PRESTADOR
  AND EMD.CD_ESPECIALID = ESP.CD_ESPECIALID
  AND A.CD_PACIENTE = PAP.CD_PACIENTE(+)
  AND PAP.CD_PERFIL_ALERTA = PA.CD_PERFIL_ALERTA(+)
  AND A.CD_TIP_RES = TR.CD_TIP_RES(+)
  --FILTROS
  AND A.CD_ORI_ATE IN (181,189)
  AND EMD.SN_ESPECIAL_PRINCIPAL = 'S'
  AND ESP.CD_ESPECIALID NOT IN (25 ,42,38) -- 25 = HEMATOLOGIA || 42 = OFTALMOLOGIA || 38 = NEUROLOGIA
  --39314 SEM AS ESPECIALIDADES 39316 COM AS ESPECIALIDADES
  --AND P.CD_PACIENTE = '2043302' -- VALIDAR PACIENTES SEM GRUPO ATRELADO

  ORDER BY TO_DATE(DT_ATENDIMENTO) DESC, PA.CD_PERFIL_ALERTA,PR.NM_PRESTADOR
  ;
  SELECT ESP.CD_ESPECIALID, ESP.DS_ESPECIALID
  FROM DBAMV.ESPECIALID ESP
  
