SELECT DISTINCT
/*CASE 
  WHEN INSTR(AHP.BUSINESS_KEY_,'-',1,3) > 0 THEN SUBSTR ( AHP.BUSINESS_KEY_, INSTR(AHP.BUSINESS_KEY_,'-',1,3)+1, LENGTH(AHP.BUSINESS_KEY_) - INSTR(AHP.BUSINESS_KEY_,'-',1,3))
  WHEN INSTR(AHP.BUSINESS_KEY_,'-',1,2) > 0 THEN SUBSTR ( AHP.BUSINESS_KEY_, INSTR(AHP.BUSINESS_KEY_,'-',1,2)+1, LENGTH(AHP.BUSINESS_KEY_) - INSTR(AHP.BUSINESS_KEY_,'-',1,2))
  ELSE SUBSTR ( AHP.BUSINESS_KEY_, INSTR(AHP.BUSINESS_KEY_,'-',1,1)+1) END AS CD_REGISTRO
  
,*/CASE 
  WHEN AHT.PROC_DEF_KEY_ = 'ChkAMAUwzOTZopktTHU8Fl' THEN UPPER('ACESSO ATIVIDADES FLOW')
  WHEN AHT.PROC_DEF_KEY_ = 'jZD2kTDc4DkUifjBrLjHFK' THEN UPPER('CADASTRAR ORIGEM')
  WHEN AHT.PROC_DEF_KEY_ = 'kmK5nkK_C7kfj2UUHTKOzs' THEN UPPER('SOLICITAÇÃIO DE ALTERAÇÃO Cadastro de PRODUTOS')
  WHEN AHT.PROC_DEF_KEY_ = 'kekXG7UZw2krRcgfmBuo1v' THEN UPPER('AGRUPAMENTO DE REMESSA')
  WHEN AHT.PROC_DEF_KEY_ = 'VowG3KPB_0OHPpGPm_0pJf' THEN UPPER('SOLICITAÇÃO CADASTRO DE RECURSO')
  WHEN AHT.PROC_DEF_KEY_ = 'fKtENXJwD6WNkCnL4xVrdg' THEN UPPER('SOLICITAÇÃO DE Material EM GERAL')
  WHEN AHT.PROC_DEF_KEY_ = 'pZNEd0fk8tZRkDLhcz2_6K' THEN UPPER('SOLICITAÇÃO DE Material Descartável')
  WHEN AHT.PROC_DEF_KEY_ = 'xou7ACMdcFAkvkBX6VcAOw' THEN UPPER('Criar ou Alterar Motivos de Auditoria')
  WHEN AHT.PROC_DEF_KEY_ = 'SKHLmobDSVwOppMdMG3DZv' THEN UPPER('Fracionamento Mat/Med')
  WHEN AHT.PROC_DEF_KEY_ = 'Jru5ikKnrVSFG6O1kosdB7' THEN UPPER('ITENS DE AGENDAMENTO')
  WHEN AHT.PROC_DEF_KEY_ = 'ZgP_6mPlPxdgNzwdrAJOK7' THEN UPPER('SOLICITAÇÃO DE PACOTES')
  WHEN AHT.PROC_DEF_KEY_ = 'vUjgjcXEmPucDG1uzEDG7K' THEN UPPER('BLOQUEIO/DESBLOQUEIO DE PRODUTOS')
  WHEN AHT.PROC_DEF_KEY_ = 'uOkiAk72G24j5Ta6VJWKXO' THEN UPPER('Revisar Itens Zerados')
  WHEN AHT.PROC_DEF_KEY_ = 'zga6Hk_hTECe8Ji256gXcp' THEN UPPER('Cadastrar Material com Substituição')
  WHEN AHT.PROC_DEF_KEY_ = 'kFKIB17KrPhNh3jFMz26h5' THEN UPPER('Cadastrar Medicamento')
  WHEN AHT.PROC_DEF_KEY_ = 'Rbc3BvMbu37dmeZuCUoI3D' THEN UPPER('VERSÃO ANTIGA Reajustes de Convênios')
  WHEN AHT.PROC_DEF_KEY_ = 'BBJWKWvK9fMd9IbKhDz5Hd' THEN UPPER('NEGOCIAÇÕES CONTRATUAIS')
  WHEN AHT.PROC_DEF_KEY_ = 'dCizKvCk_df3Zz_VzD_v7v' THEN UPPER('EXCEÇÃO DE CONVÊNIOS - COMERCIAL')
  WHEN AHT.PROC_DEF_KEY_ = 'GCUkaEt5JKMsiB1cClGBWW' THEN UPPER('MOTIVOS DE BAIXA - LOGÍSTICA')
  WHEN AHT.PROC_DEF_KEY_ = 'kzaPwKz5kK2GV5sfrLD2cZ' THEN UPPER('NOVO CENTRO DE CUSTO')
  WHEN AHT.PROC_DEF_KEY_ = 'FGpbozhF7mHI0PeXhnKroH' THEN UPPER('PARAMETRIZAÇÃO DE VALOR OPME')
  WHEN AHT.PROC_DEF_KEY_ = 'pWVg7KGAi4DswKrHzXS2mb' THEN UPPER('VALIDAR PROIBIÇÕES')
  WHEN AHT.PROC_DEF_KEY_ = 'KTjtA5ACKaDoJ703vezao0' THEN UPPER('CADASTRO DE OPME')
  WHEN AHT.PROC_DEF_KEY_ = 'BjCkEZSU8O6ar44iuATHgZ' THEN UPPER('ITENS DE PRESCRIÇÃO DE DIETAS')
  WHEN AHT.PROC_DEF_KEY_ = 'mfcaSZStHxVKAcfMzA5g_P' THEN UPPER('Proibição de Convênios')
END AS DS_PROCESSO

,TO_DATE (TRUNC (AHT.START_TIME_)) AS DT_INTEGRA
/*,CASE 
  WHEN AHP.STATE_ = 'COMPLETED' THEN 'FINALIZADO'
  WHEN AHP.STATE_ = 'ACTIVE' THEN 'EM ANDAMENTO'
  WHEN AHP.STATE_ = 'EXTERNALLY_TERMINATED' THEN 'EXCLUIDO'
  END AS STATUS_PROCESSO
  */
,    CASE 
      WHEN ASSIGNEE_ = 14636 THEN 'CENTRAL CADASTRO'
      WHEN ASSIGNEE_ = 17446 THEN 'CENTRAL CADASTRO'
      WHEN ASSIGNEE_ = 23135 THEN 'CENTRAL CADASTRO'
      WHEN ASSIGNEE_ = 11245 THEN 'CENTRAL CADASTRO'
      WHEN ASSIGNEE_ = 18484 THEN 'CENTRAL CADASTRO'
      WHEN ASSIGNEE_ = 20587 THEN 'CENTRAL CADASTRO'
      WHEN ASSIGNEE_ IS NOT NULL THEN 'EXTERNOS'
      ELSE 'SEM RESPONSÁVEL' END DS_EQUIPE

,AHT.ASSIGNEE_ AS RESP_ATUAL
,AHT.NAME_ AS ATIVIDADE_ATUAL
,AHT.START_TIME_ AS DT_INICIO_ATIV
,AHT.END_TIME_ AS DT_FINAL_ATIV
--,ROUND((TRUNC (AHT.END_TIME_,'DD/MM/RRRR HH24:MI:SS') - TRUNC (AHT.START_TIME_,'DD/MM/RRRR HH24:MI:SS')),0) AS SLA_MIN
,EXTRACT(HOUR FROM AHT.END_TIME_ - AHT.START_TIME_) || ':' || EXTRACT(MINUTE FROM AHT.END_TIME_ - AHT.START_TIME_) || ':' || TRUNC(EXTRACT(SECOND FROM AHT.END_TIME_ - AHT.START_TIME_)) AS TMP_SLA
,EXTRACT(MINUTE FROM AHT.END_TIME_ - AHT.START_TIME_) AS TMP_MIN
,INSTR(((AHT.END_TIME_ - AHT.START_TIME_)*24*60),' ') AS TMP
,DECODE (UPPER (AHT.DELETE_REASON_),'COMPLETED','FINALIZADO',NULL,'AGUARDANDO','DELETED','EXCLUIDO') AS STATUS_ATIV
,DENSE_RANK() OVER (PARTITION BY AHT.PROC_INST_ID_ ORDER BY AHT.START_TIME_ DESC) AS NR_ORDERM

FROM ENGINE.ACT_HI_TASKINST AHT
--LIGAÇÕES REALIZADAS
--FILTROS
--WHERE AHP.STATE_ NOT IN ('EXTERNALLY_TERMINATED')

WHERE AHT.PROC_DEF_KEY_ IN (
'ChkAMAUwzOTZopktTHU8Fl', --ACESSO ATIVIDADES FLOW
'jZD2kTDc4DkUifjBrLjHFK', --CADASTRAR ORIGEM
'kmK5nkK_C7kfj2UUHTKOzs', --CADASTRO -  Alterar Cadastro de Material
'kekXG7UZw2krRcgfmBuo1v', --CADASTRO - AGRUPAMENTO DE REMESSA
'VowG3KPB_0OHPpGPm_0pJf', --CADASTRO - CADASTRAR DE RECURSO
'fKtENXJwD6WNkCnL4xVrdg', --CADASTRO - Cadastrar Material
'pZNEd0fk8tZRkDLhcz2_6K', --CADASTRO - Cadastrar Material Descartável
'xou7ACMdcFAkvkBX6VcAOw', --CADASTRO - Criar ou Alterar Motivos de Auditoria
'SKHLmobDSVwOppMdMG3DZv', --CADASTRO - Fracionamento Mat/Med
'Jru5ikKnrVSFG6O1kosdB7', --CADASTRO - ITENS DE AGENDAMENTO
'ZgP_6mPlPxdgNzwdrAJOK7', --CADASTRO - PARAMETRIZAÇÃO PACOTES (SOLICITAÇÃO DE PACOTES)
'vUjgjcXEmPucDG1uzEDG7K', --CADASTRO - REATIVAR - BLOQUEAR PRODUTOS
'uOkiAk72G24j5Ta6VJWKXO', --CADASTRO - Revisar Itens Zerados
'zga6Hk_hTECe8Ji256gXcp', --CENTRAL DE CADASTRO - Cadastrar Material com Substituição
'kFKIB17KrPhNh3jFMz26h5', --CENTRAL DE CADASTRO - Cadastrar Medicamento
'Rbc3BvMbu37dmeZuCUoI3D', --CENTRAL DE CADASTRO - Reajustes de Convênios
'BBJWKWvK9fMd9IbKhDz5Hd', --Contrato/Reajuste de Convênios
'dCizKvCk_df3Zz_VzD_v7v', --EXCEÇÃO DE CONVÊNIOS - COMERCIAL
'GCUkaEt5JKMsiB1cClGBWW', --MOTIVOS DE BAIXA - LOGÍSTICA
'kzaPwKz5kK2GV5sfrLD2cZ', --NOVO CENTRO DE CUSTO
'FGpbozhF7mHI0PeXhnKroH', --PARAMETRIZAÇÃO DE VALOR OPME
'pWVg7KGAi4DswKrHzXS2mb', --VALIDAR PROIBIÇÕES
'KTjtA5ACKaDoJ703vezao0', --CADASTRO DE OPME
'BjCkEZSU8O6ar44iuATHgZ', --CADASTRO DIETAS
'mfcaSZStHxVKAcfMzA5g_P'  --COMERCIAL - Proibição de Convênios
)
--AND TRUNC (AHP.START_TIME_) > '31/12/2023'
--AND  (ASSIGNEE_ IN (14636,17446,23135,11245,18484,20587) OR ASSIGNEE_ IS NULL) 

GROUP BY 
ASSIGNEE_
,NAME_
,AHT.START_TIME_
,AHT.END_TIME_
,AHT.DELETE_REASON_
,AHT.PROC_INST_ID_
,AHT.PROC_DEF_KEY_
ORDER BY AHT.START_TIME_ DESC
