SELECT DISTINCT
INF.CD_ATENDIMENTO
,PAC.CD_PACIENTE
,PAC.NM_PACIENTE
,PAC.DT_NASCIMENTO
,INF.TP_LOCALIZACAO
,INF.DS_TP_LOCALIZACAO
,INF.CD_UNID_INT
,INF.DS_UNID_INT
,INF.DT_ATENDIMENTO
,INF.DT_ALTA
,INF.DT_REG_INF
,INF.TP_INFEC
,INF.DS_TP_INFEC
,INF.TP_SIT
,INF.DS_TP_SIT
,INF.CD_ESPECIALID
,INF.DS_ESPECIALID
,INF.CD_REG_INF
,INF.CD_SERVICO
,INF.DS_SERVICO
,INF.SN_COLONIZACAO
,INF.SN_INFECCAO
,INF.SN_INFCOL
,INF.CD_TOPOGRAFIA
,INF.DS_TOPOGRAFIA
,INF.CD_SIGLA_IRAS
,INF.DS_SITIO_PRINCIPAL
,ST.CD_SETOR
,ST.NM_SETOR
,INF.DS_LEITO
,INF.CD_LEITO
--NF.DS_GERME
,INF.CD_ORI_ATE
,INF.DS_OBSERVACAO
,CA.CD_AVISO_CIRURGIA
,CA.CD_CIRURGIA_AVISO
,AC.CD_SAL_CIR
,INF.DS_SAL_CIR
,AC.DT_REALIZACAO
,CA.CD_CIRURGIA
,CIR.DS_CIRURGIA
,CA.CD_CONVENIO
,Decode(CA.TP_NATUREZA,'P','POTENCIALMENTE CONTAMINADA','C','CONTAMINADA','I','INFECCTADA','L','LIMPA','N','NÃO CLASSIFICADA', NULL,'NÃO INFORMADA') Ds_Potencial_telaMV
,INF.CD_PRESTADOR
,INF.NM_PRESTADOR
FROM
  DBAMV.VDES_REGISTRO_INFECCAO_MAIN INF
  ,DBAMV.PACIENTE PAC
  ,DBAMV.AVISO_CIRURGIA AC
  ,DBAMV.CIRURGIA_AVISO CA
  ,DBAMV.UNID_INT UI
  ,DBAMV.SETOR ST
  ,DBAMV.CIRURGIA CIR
  
  --RELAÇÕES

WHERE PAC.CD_PACIENTE = INF.CD_PACIENTE
AND INF.CD_ATENDIMENTO = AC.CD_ATENDIMENTO
AND CA.CD_AVISO_CIRURGIA = AC.CD_AVISO_CIRURGIA
AND UI.CD_UNID_INT = AC.CD_UNID_INT
AND ST.CD_SETOR = UI.CD_SETOR
AND CIR.CD_CIRURGIA = CA.CD_CIRURGIA
  --FILTROS
--AND DT_ATENDIMENTO BETWEEN To_Date('01/04/2024', 'DD/MM/RRRR') AND To_Date('30/04/2024', 'DD/MM/RRRR')
--AND AC.CD_AVISO_CIRURGIA = 155706
AND CA.SN_PRINCIPAL = 'S'
--AND INF.CD_ATENDIMENTO = 4473358

GROUP BY 

INF.CD_ATENDIMENTO
,PAC.CD_PACIENTE
,PAC.NM_PACIENTE
,PAC.DT_NASCIMENTO
,INF.TP_LOCALIZACAO
,INF.DS_TP_LOCALIZACAO
,INF.CD_UNID_INT
,INF.DS_UNID_INT
,INF.DT_ATENDIMENTO
,INF.DT_ALTA
,INF.DT_REG_INF
,INF.TP_INFEC
,INF.DS_TP_INFEC
,INF.TP_SIT
,INF.DS_TP_SIT
,INF.CD_ESPECIALID
,INF.DS_ESPECIALID
,INF.CD_REG_INF
,INF.CD_SERVICO
,INF.DS_SERVICO
,INF.SN_COLONIZACAO
,INF.SN_INFECCAO
,INF.SN_INFCOL
,INF.CD_TOPOGRAFIA
,INF.DS_TOPOGRAFIA
,INF.CD_SIGLA_IRAS
,INF.DS_SITIO_PRINCIPAL
,ST.CD_SETOR
,ST.NM_SETOR
,INF.DS_LEITO
,INF.CD_LEITO
--,INF.DS_GERME
,INF.CD_ORI_ATE
,INF.DS_OBSERVACAO
,CA.CD_AVISO_CIRURGIA
,CA.CD_CIRURGIA_AVISO
,AC.CD_SAL_CIR
,INF.DS_SAL_CIR
,AC.DT_REALIZACAO
,CA.CD_CIRURGIA
,CIR.DS_CIRURGIA
,CA.CD_CONVENIO
,INF.CD_PRESTADOR
,INF.NM_PRESTADOR
,Decode(CA.TP_NATUREZA,'P','POTENCIALMENTE CONTAMINADA','C','CONTAMINADA','I','INFECCTADA','L','LIMPA','N','NÃO CLASSIFICADA', NULL,'NÃO INFORMADA')
ORDER BY to_date (INF.DT_REG_INF) DESC