    SELECT 
        S.NM_SET_EXA TIPO_EXA,
        A.CD_ATENDIMENTO,
        A.CD_PACIENTE,
        (SELECT REGEXP_REPLACE(NM_PACIENTE, '\s([A-Za-z])[A-Za-z]+', ' \1.') FROM PACIENTE WHERE CD_PACIENTE = A.CD_PACIENTE) NM_PACIENTE,
        UI.CD_UNID_INT,
        UI.DS_UNID_INT,
        LEI.DS_LEITO,
        A.DT_ALTA_MEDICA,
        P.CD_PED_RX,
        IPR.CD_EXA_RX,
        (SELECT MIN(DS_EXA_RX) FROM DBAMV.EXA_RX ERX WHERE CD_EXA_RX = IPR.CD_EXA_RX) AS DS_EXA_RX,
        (DBAMV.FNC_MV_RECUPERA_DATA_HORA(P.DT_PEDIDO, P.HR_PEDIDO)) AS DT_PEDIDO_RX,
        MAX(LAU.DT_STUDY) AS DH_REALIZADO,
        MAX(LAU.DT_REVISADO) AS DT_REVISADO,
        MAX(LAU.DT_LAUDADO) AS DT_LAUDADO,
        MAX(LAU.DT_ENTREGA_PREVISTA) AS DT_ENTREGA_PREVISTA,
        ROUND(((SYSDATE - MAX(DBAMV.FNC_MV_RECUPERA_DATA_HORA(P.DT_PEDIDO, P.HR_PEDIDO)))*24*60),0) AS TEMPO,
        TO_CHAR(TO_DATE('00:00', 'HH24:MI') + NUMTODSINTERVAL(ROUND(((SYSDATE - MAX(DBAMV.FNC_MV_RECUPERA_DATA_HORA(P.DT_PEDIDO, P.HR_PEDIDO)))*24*60),0), 'MINUTE'), 'HH24:MI') AS HM_TEMPO,
        (RANK() OVER (PARTITION BY A.CD_ATENDIMENTO ORDER BY S.NM_SET_EXA DESC, P.HR_PEDIDO DESC)) AS NR_ORD

    FROM 
        DBAMV.PED_RX P,
        DBAMV.ITPED_RX IPR,
        DBAMV.ATENDIME A,
        DBAMV.SET_EXA S,
        DBAMV.LEITO LEI,
        DBAMV.UNID_INT UI,

        IDCE.RS_LAU_PEDIDO_EXAME ped,
        IDCE.RS_LAU_EXAME_PEDIDO lau,
        IDCE.RS_EXA_EXAME_UNIDADE exame

    WHERE A.CD_ATENDIMENTO = P.CD_ATENDIMENTO
    AND   P.CD_SET_EXA = S.CD_SET_EXA
    AND   P.CD_PED_RX = IPR.CD_PED_RX
    AND LEI.CD_LEITO = A.CD_LEITO 
    AND UI.CD_UNID_INT = LEI.CD_UNID_INT

    AND   ped.cd_pedido_his = P.CD_PED_RX
    AND   ped.CD_ATENDIMENTO_HIS  = P.CD_ATENDIMENTO
    AND   ped.ID_PEDIDO_EXAME  = lau.ID_PEDIDO_EXAME
    AND   exame.ID_EXAME_UNIDADE  = lau.ID_EXAME_UNIDADE

    AND   NVL(LAU.DT_STUDY,LAU.DT_LAUDADO) IS NULL --NÃO TEVE IMAGEM OU LAUDO
    --AND A.DT_ATENDIMENTO >= '01/JUL/2024'
    AND   A.DT_ATENDIMENTO < TRUNC(SYSDATE)+INTERVAL '24' HOUR
    AND   A.DT_ALTA IS NULL
    AND   A.TP_ATENDIMENTO = 'I'
    AND   P.DT_PEDIDO >= TRUNC(SYSDATE)--INTERVAL '24' HOUR
    AND   P.CD_SET_EXA IN (12,13,15,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,36,38,39,40,41,42,43,77) --SETORES DE EXAMES DO REAL IMAGEM
    group by A.CD_ATENDIMENTO,S.NM_SET_EXA,P.DT_PEDIDO, P.HR_PEDIDO,A.CD_PACIENTE,UI.CD_UNID_INT, UI.DS_UNID_INT, LEI.DS_LEITO, A.DT_ALTA_MEDICA, P.CD_PED_RX, IPR.CD_EXA_RX, IPR.CD_EXA_RX
    
    order by CD_PED_RX