SELECT 
TIPO_EXA
, CD_ATENDIMENTO
--, CD_PACIENTE
,(SELECT REGEXP_REPLACE(NM_PACIENTE, '\s([A-Za-z])[A-Za-z]+', ' \1.') FROM PACIENTE WHERE CD_PACIENTE = BASE.CD_PACIENTE) NM_PACIENTE
, CD_UNID_INT
, DS_UNID_INT
, DS_LEITO
, CD_PED_RX
, DS_EXA_RX
--, HR_SOLSAI_PRO
--, DH_DISPENSACAO_FARM
--, ROUND(((NVL(MAX(DH_DISPENSACAO_FARM), sysdate) - MAX(HR_SOLSAI_PRO)) * 24 * 60),0) AS FARM
--, DH_PED_LAB
--, DH_COLETA_LAB
--, ROUND(((NVL(MAX(DH_COLETA_LAB), sysdate) - MAX(DH_PED_LAB))* 24 * 60),0) AS LAB
, DT_PEDIDO_RX
, DH_REALIZADO
, CASE 
    WHEN ROUND(((NVL (NVL (DH_REALIZADO, DT_ALTA_MEDICA),SYSDATE) - DT_PEDIDO_RX)*24 *60),0) >= 0
    THEN ROUND(((NVL (NVL (DH_REALIZADO, DT_ALTA_MEDICA),SYSDATE) - DT_PEDIDO_RX)*24 *60),0)
    ELSE ROUND(((NVL (NVL (DH_REALIZADO, DT_ALTA_MEDICA),SYSDATE) - DT_PEDIDO_RX)*24 *60),0) * -1
  END AS TEMPO_09
, CASE 
    WHEN ROUND(((NVL (NVL (DH_REALIZADO, DT_ALTA_MEDICA),SYSDATE) - DT_PEDIDO_RX)*24 *60),0) >= 0 
    THEN TO_CHAR(TO_DATE('00:00', 'HH24:MI') + NUMTODSINTERVAL(ROUND(((NVL (NVL (DH_REALIZADO, DT_ALTA_MEDICA),SYSDATE) - DT_PEDIDO_RX)*24 *60),0), 'MINUTE'), 'HH24:MI') 
    ELSE TO_CHAR(TO_DATE('00:00', 'HH24:MI') + NUMTODSINTERVAL((ROUND(((NVL (NVL (DH_REALIZADO, DT_ALTA_MEDICA),SYSDATE) - DT_PEDIDO_RX)*24 *60),0)*-1), 'MINUTE'), 'HH24:MI') 
  END AS HM_TEMPO9
/*
, DT_REVISADO
, ROUND(((NVL (NVL (DT_REVISADO, DT_ALTA_MEDICA),SYSDATE) - DH_REALIZADO)*24 *60),0) AS TEMPO_16
, TO_CHAR(TO_DATE('00:00', 'HH24:MI') + NUMTODSINTERVAL(ROUND(((NVL (NVL (DT_REVISADO, DT_ALTA_MEDICA),SYSDATE) - DH_REALIZADO)*24 *60),0), 'MINUTE'), 'HH24:MI') AS HM_TEMPO16

, DT_LAUDADO
, ROUND(((NVL (NVL (DT_LAUDADO, DT_ALTA_MEDICA),SYSDATE) - DT_REVISADO)*24 *60),0) AS TEMPO_17
, TO_CHAR(TO_DATE('00:00', 'HH24:MI') + NUMTODSINTERVAL(ROUND(((NVL (NVL (DT_LAUDADO, DT_ALTA_MEDICA),SYSDATE) - DT_REVISADO)*24 *60),0), 'MINUTE'), 'HH24:MI') AS HM_TEMPO17

, DT_ENTREGA_PREVISTA
, ROUND(((NVL (NVL (DT_ENTREGA_PREVISTA, DT_ALTA_MEDICA),SYSDATE) - DT_LAUDADO)*24 *60),0) AS TEMPO_18
, TO_CHAR(TO_DATE('00:00', 'HH24:MI') + NUMTODSINTERVAL(ROUND(((NVL (NVL (DT_ENTREGA_PREVISTA, DT_ALTA_MEDICA),SYSDATE) - DT_LAUDADO)*24 *60),0), 'MINUTE'), 'HH24:MI') AS HM_TEMPO18

/*,CASE 
    WHEN DT_PEDIDO_RX IS NOT NULL AND DH_PED_LAB IS NOT NULL  AND DH_COLETA_LAB IS NOT NULL  AND HR_SOLSAI_PRO IS NOT NULL AND DH_DISPENSACAO_FARM IS NOT NULL THEN 1   --COMPLETO
    WHEN DT_PEDIDO_RX IS NOT NULL AND DH_PED_LAB IS NULL      AND DH_COLETA_LAB IS NULL      AND HR_SOLSAI_PRO IS NOT NULL AND DH_DISPENSACAO_FARM IS NOT NULL THEN 1   --APENAS IMAGEM E PRODUTO
    WHEN DT_PEDIDO_RX IS NOT NULL AND DH_PED_LAB IS NOT NULL  AND DH_COLETA_LAB IS NOT NULL  AND HR_SOLSAI_PRO IS NULL     AND DH_DISPENSACAO_FARM IS NULL     THEN 1   --APENAS IMAGEM E LABORATORIO
    WHEN DT_PEDIDO_RX IS NOT NULL AND DH_PED_LAB IS NULL      AND DH_COLETA_LAB IS NULL      AND HR_SOLSAI_PRO IS NULL     AND DH_DISPENSACAO_FARM IS NULL     THEN 1   --APENAS IMAGEM
    ELSE 0 END AS SN_OCULTO
,CASE 
    WHEN DT_PEDIDO_RX IS NOT NULL AND DH_PED_LAB IS NOT NULL AND HR_SOLSAI_PRO IS NOT NULL THEN 'C'   --COMPLETO
    WHEN DT_PEDIDO_RX IS NOT NULL AND DH_PED_LAB IS NULL AND HR_SOLSAI_PRO IS NOT NULL THEN 'IP'      --APENAS IMAGEM E PRODUTO
    WHEN DT_PEDIDO_RX IS NOT NULL AND DH_PED_LAB IS NOT NULL AND HR_SOLSAI_PRO IS NULL THEN 'IL'      --APENAS IMAGEM E LABORATORIO
    WHEN DT_PEDIDO_RX IS NOT NULL AND DH_PED_LAB IS NULL AND HR_SOLSAI_PRO IS NULL THEN 'I'           --APENAS IMAGEM
    ELSE 'N' END AS SN_IMAGEM
      
,CASE
    WHEN DT_PEDIDO_RX IS NOT NULL AND DH_PED_LAB IS NOT NULL AND HR_SOLSAI_PRO IS NOT NULL THEN ROUND(((NVL(NVL(DH_REALIZADO,DT_ALTA_MEDICA),SYSDATE) - DT_PEDIDO_RX)*24 *60),0) - (ROUND(((NVL(MAX(DH_COLETA_LAB), sysdate) - MAX(DH_PED_LAB))* 24 * 60),0) + ROUND(((NVL(MAX(DH_DISPENSACAO_FARM), sysdate) - MAX(HR_SOLSAI_PRO)) * 24 * 60),0) )
    WHEN DT_PEDIDO_RX IS NOT NULL AND DH_PED_LAB IS NULL AND HR_SOLSAI_PRO IS NOT NULL THEN ROUND(((NVL(NVL(DH_REALIZADO,DT_ALTA_MEDICA),SYSDATE) - DT_PEDIDO_RX)*24 *60),0) - (ROUND(((NVL(MAX(DH_DISPENSACAO_FARM), sysdate) - MAX(HR_SOLSAI_PRO)) * 24 * 60),0)*-1)
    WHEN DT_PEDIDO_RX IS NOT NULL AND DH_PED_LAB IS NOT NULL AND HR_SOLSAI_PRO IS NULL THEN ROUND(((NVL(NVL(DH_REALIZADO,DT_ALTA_MEDICA),SYSDATE) - DT_PEDIDO_RX)*24 *60),0) - ROUND(((NVL(MAX(DH_COLETA_LAB), sysdate) - MAX(DH_PED_LAB))* 24 * 60),0)
    WHEN DT_PEDIDO_RX IS NOT NULL AND DH_PED_LAB IS NULL AND HR_SOLSAI_PRO IS NULL THEN ROUND(((NVL(NVL(DH_REALIZADO,DT_ALTA_MEDICA),SYSDATE) - DT_PEDIDO_RX)*24 *60),0) END AS TEMPO_09
, TO_CHAR(TO_DATE('00:00', 'HH24:MI') + NUMTODSINTERVAL(
CASE
    WHEN DT_PEDIDO_RX IS NOT NULL AND DH_PED_LAB IS NOT NULL AND HR_SOLSAI_PRO IS NOT NULL THEN ROUND(((NVL(DH_REALIZADO,SYSDATE) - DT_PEDIDO_RX)*24 *60),0) - (ROUND(((NVL(MAX(DH_COLETA_LAB), sysdate) - MAX(DH_PED_LAB))* 24 * 60),0) + ROUND(((NVL(MAX(DH_DISPENSACAO_FARM), sysdate) - MAX(HR_SOLSAI_PRO)) * 24 * 60),0) )
    WHEN DT_PEDIDO_RX IS NOT NULL AND DH_PED_LAB IS NULL AND HR_SOLSAI_PRO IS NOT NULL THEN ROUND(((NVL(DH_REALIZADO,SYSDATE) - DT_PEDIDO_RX)*24 *60),0) - (ROUND(((NVL(MAX(DH_DISPENSACAO_FARM), sysdate) - MAX(HR_SOLSAI_PRO)) * 24 * 60),0)*-1)
    WHEN DT_PEDIDO_RX IS NOT NULL AND DH_PED_LAB IS NOT NULL AND HR_SOLSAI_PRO IS NULL THEN ROUND(((NVL(DH_REALIZADO,SYSDATE) - DT_PEDIDO_RX)*24 *60),0) - ROUND(((NVL(MAX(DH_COLETA_LAB), sysdate) - MAX(DH_PED_LAB))* 24 * 60),0)
    WHEN DT_PEDIDO_RX IS NOT NULL AND DH_PED_LAB IS NULL AND HR_SOLSAI_PRO IS NULL THEN ROUND(((NVL(DH_REALIZADO,SYSDATE) - DT_PEDIDO_RX)*24 *60),0) END
, 'MINUTE'), 'HH24:MI') AS HM_TEMPO09
*/
FROM (
    SELECT 
        S.NM_SET_EXA TIPO_EXA,
        A.CD_ATENDIMENTO,
        A.CD_PACIENTE,
        UI.CD_UNID_INT,
        UI.DS_UNID_INT,
        LEI.DS_LEITO,
        MAX(A.DT_ALTA_MEDICA) AS DT_ALTA_MEDICA,
        MAX(P.CD_PED_RX) AS CD_PED_RX,
        MAX((SELECT MIN(DS_EXA_RX) FROM ITPED_RX IPR, DBAMV.EXA_RX ERX WHERE IPR.CD_EXA_RX = ERX.CD_EXA_RX AND IPR.CD_PED_RX = P.CD_PED_RX)) AS DS_EXA_RX,
        MAX(DBAMV.FNC_MV_RECUPERA_DATA_HORA(P.DT_PEDIDO, P.HR_PEDIDO)) AS DT_PEDIDO_RX,
        MAX(LAU.DT_STUDY) AS DH_REALIZADO,
        MAX(LAU.DT_REVISADO) AS DT_REVISADO,
        MAX(LAU.DT_LAUDADO) AS DT_LAUDADO,
        MAX(LAU.DT_ENTREGA_PREVISTA) AS DT_ENTREGA_PREVISTA,
        (RANK() OVER (PARTITION BY A.CD_ATENDIMENTO ORDER BY S.NM_SET_EXA DESC, P.HR_PEDIDO DESC)) AS NR_ORD

    FROM 
        DBAMV.PED_RX P,
        DBAMV.ATENDIME A,
        DBAMV.SET_EXA S,
        --DBAMV.ITPED_RX IPR,
        DBAMV.LEITO LEI,
        DBAMV.UNID_INT UI,

        IDCE.RS_LAU_PEDIDO_EXAME ped,
        IDCE.RS_LAU_EXAME_PEDIDO lau,
        IDCE.RS_EXA_EXAME_UNIDADE exame

    WHERE A.CD_ATENDIMENTO = P.CD_ATENDIMENTO
    AND   P.CD_SET_EXA = S.CD_SET_EXA
    --AND   P.CD_PED_RX = IPR.CD_PED_RX
    AND LEI.CD_LEITO = A.CD_LEITO 
    AND UI.CD_UNID_INT = LEI.CD_UNID_INT

    AND   ped.cd_pedido_his = P.CD_PED_RX
    AND   ped.CD_ATENDIMENTO_HIS  = P.CD_ATENDIMENTO
    AND   ped.ID_PEDIDO_EXAME  = lau.ID_PEDIDO_EXAME
    AND   exame.ID_EXAME_UNIDADE  = lau.ID_EXAME_UNIDADE

    AND   NVL(LAU.DT_STUDY,LAU.DT_LAUDADO) IS NULL --NÃO TEVE IMAGEM OU LAUDO
    --AND A.DT_ATENDIMENTO >= '01/JUL/2024'
    AND   A.DT_ATENDIMENTO < TRUNC(SYSDATE)+INTERVAL '24' HOUR
    AND   A.DT_ALTA IS NULL
    AND   A.TP_ATENDIMENTO = 'I'
    AND   P.DT_PEDIDO >= TRUNC(SYSDATE)-INTERVAL '24' HOUR
    AND   P.CD_SET_EXA IN (12,13,15,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,36,38,39,40,41,42,43,77) --SETORES DE EXAMES DO REAL IMAGEM
    group by A.CD_ATENDIMENTO,S.NM_SET_EXA,P.HR_PEDIDO,A.CD_PACIENTE,UI.CD_UNID_INT, UI.DS_UNID_INT, LEI.DS_LEITO
    ORDER BY CD_ATENDIMENTO
)BASE
WHERE NR_ORD = 1 
--AND CD_ATENDIMENTO = 4764605

GROUP BY 
TIPO_EXA
, CD_ATENDIMENTO
, DT_PEDIDO_RX
, DH_REALIZADO
, CD_PED_RX
, DS_EXA_RX
, DT_ALTA_MEDICA
, DT_REVISADO
, DT_LAUDADO
, DT_ENTREGA_PREVISTA
, CD_PACIENTE
, CD_UNID_INT
, DS_UNID_INT
, DS_LEITO

ORDER BY CD_ATENDIMENTO DESC