SELECT * FROM (
SELECT 
    PMD.CD_PRE_MED,
    PMD.CD_ATENDIMENTO,
    (SELECT REGEXP_REPLACE(NM_PACIENTE, '\s([A-Za-z])[A-Za-z]+', ' \1.') FROM PACIENTE WHERE CD_PACIENTE = ATE.CD_PACIENTE) AS NM_PACIENTE,
    PMD.CD_PRESTADOR || ' - ' || (SELECT MAX(NM_PRESTADOR) FROM DBAMV.PRESTADOR WHERE CD_PRESTADOR = PMD.CD_PRESTADOR) AS NM_PRESTADOR,
    PMD.CD_UNID_INT,
    UI.DS_UNID_INT,
    MAX(LEI.DS_LEITO) AS DS_LEITO,
    PMD.DT_REFERENCIA,
    DBAMV.FNC_MV_RECUPERA_DATA_HORA(PMD.DT_PRE_MED, PMD.HR_PRE_MED) AS DT_PRE_MED,
    PMD.TP_PRE_MED,
    PMD.NM_USUARIO || ' - ' || (SELECT MAX(NM_USUARIO) FROM DBASGU.USUARIOS WHERE CD_USUARIO = PMD.NM_USUARIO) AS NM_USUARIO_PREC,
    MAX(IPM.CD_ITPRE_MED) AS CD_ITPRE_MED,
    (SELECT MAX(DS_TIP_PRESC) FROM DBAMV.TIP_PRESC WHERE CD_TIP_PRESC = IPM.CD_TIP_PRESC) AS DS_TIP_PRESC,
    MAX(IPM.CD_TIP_ESQ) AS CD_TIP_ESQ,
    MAX(IPM.CD_PRODUTO) || ' - ' || (SELECT MAX(DS_PRODUTO) FROM DBAMV.PRODUTO WHERE CD_PRODUTO = IPM.CD_PRODUTO) AS DS_PRODUTO,
    MAX(HIMD.DH_MEDICACAO) AS DH_MEDICACAO,
    MAX(HIMD.TP_GERACAO) AS TP_GERACAO,
    (SELECT MAX(HIPC.DH_CHECAGEM) FROM HRITPRE_CONS HIPC WHERE HIPC.CD_ITPRE_MED (+) = IPM.CD_ITPRE_MED AND HIPC.DH_MEDICACAO (+) = HIMD.DH_MEDICACAO) AS DH_CHECAGEM,
    (SELECT MAX((SELECT NM_USUARIO FROM DBASGU.USUARIOS WHERE CD_USUARIO = HIPC.NM_USUARIO)) FROM HRITPRE_CONS HIPC WHERE HIPC.CD_ITPRE_MED (+) = IPM.CD_ITPRE_MED AND HIPC.DH_MEDICACAO (+) = HIMD.DH_MEDICACAO) AS NM_USUARIO_CHEC,
    
    ROUND(((SYSDATE - MAX(HIMD.DH_MEDICACAO))*24 *60),0) AS TEMPO,
    TO_CHAR(TO_DATE('00:00', 'HH24:MI') + NUMTODSINTERVAL(ROUND(((SYSDATE - MAX(HIMD.DH_MEDICACAO))*24 *60),0), 'MINUTE'), 'HH24:MI') AS HM_TEMPO

FROM 
    DBAMV.PRE_MED PMD,
    DBAMV.ITPRE_MED IPM,
    DBAMV.SET_EXA S,
    DBAMV.LEITO LEI,
    DBAMV.UNID_INT UI,
    DBAMV.HRITPRE_MED HIMD,
    DBAMV.ATENDIME ATE

WHERE PMD.CD_PRE_MED = IPM.CD_PRE_MED
AND UI.CD_UNID_INT = PMD.CD_UNID_INT
AND UI.CD_UNID_INT = LEI.CD_UNID_INT
AND IPM.CD_ITPRE_MED = HIMD.CD_ITPRE_MED(+)
AND PMD.CD_ATENDIMENTO = ATE.CD_ATENDIMENTO
AND DBAMV.FNC_MV_RECUPERA_DATA_HORA(PMD.DT_PRE_MED, PMD.HR_PRE_MED) >= TRUNC(SYSDATE)
AND DBAMV.FNC_MV_RECUPERA_DATA_HORA(PMD.DT_PRE_MED, PMD.HR_PRE_MED) < TRUNC(SYSDATE) + INTERVAL '24' HOUR
AND HIMD.DH_MEDICACAO >= TRUNC(SYSDATE)
AND HIMD.DH_MEDICACAO < TRUNC(SYSDATE) + INTERVAL '24' HOUR
AND PMD.TP_PRE_MED = 'M'
AND IPM.CD_TIP_ESQ NOT IN ('PME', 'MAN')
AND IPM.CD_PRODUTO IS NOT NULL
AND (SELECT MAX(HIPC.DH_CHECAGEM) FROM HRITPRE_CONS HIPC WHERE HIPC.CD_ITPRE_MED (+) = IPM.CD_ITPRE_MED AND HIPC.DH_MEDICACAO (+) = HIMD.DH_MEDICACAO) IS NULL
AND ATE.TP_ATENDIMENTO = 'I'
AND ATE.DT_ALTA IS NULL

-- Nova condição CASE no WHERE
AND CASE
    WHEN HIMD.DH_MEDICACAO <= SYSDATE THEN
      CASE 
        WHEN ROUND(((NVL((SELECT HIPC.DH_CHECAGEM FROM HRITPRE_CONS HIPC WHERE HIPC.CD_ITPRE_MED (+) = IPM.CD_ITPRE_MED AND HIPC.DH_MEDICACAO (+) = HIMD.DH_MEDICACAO), SYSDATE) - HIMD.DH_MEDICACAO) * 24 * 60), 0) > 0 
        THEN ROUND(((NVL((SELECT HIPC.DH_CHECAGEM FROM HRITPRE_CONS HIPC WHERE HIPC.CD_ITPRE_MED (+) = IPM.CD_ITPRE_MED AND HIPC.DH_MEDICACAO (+) = HIMD.DH_MEDICACAO), SYSDATE) - HIMD.DH_MEDICACAO) * 24 * 60), 0)
        ELSE ROUND(((NVL((SELECT HIPC.DH_CHECAGEM FROM HRITPRE_CONS HIPC WHERE HIPC.CD_ITPRE_MED (+) = IPM.CD_ITPRE_MED AND HIPC.DH_MEDICACAO (+) = HIMD.DH_MEDICACAO), SYSDATE) - HIMD.DH_MEDICACAO) * 24 * 60), 0) * -1
      END
END > 30

GROUP BY
    PMD.CD_PRE_MED,
    PMD.CD_ATENDIMENTO,
    PMD.CD_PRESTADOR,
    PMD.CD_UNID_INT,
    UI.DS_UNID_INT,
    PMD.DT_REFERENCIA,
    PMD.DT_PRE_MED,
    PMD.HR_PRE_MED,
    PMD.TP_PRE_MED,
    PMD.NM_USUARIO,
    IPM.CD_ITPRE_MED,
    IPM.CD_TIP_PRESC,
    IPM.CD_TIP_ESQ,
    IPM.CD_PRODUTO,
    HIMD.DH_MEDICACAO,
    ATE.CD_PACIENTE

)
ORDER BY DT_PRE_MED DESC
