SELECT 
        CD_ATENDIMENTO,
        DT_ATENDIMENTO,
        DT_ALTA_MEDICA,
        NM_PACIENTE,
        PRESTADO_MED,
        NM_CONVENIO,
        CD_FILA_SENHA,
        DS_SENHA,
        CD_LEITO,
        DS_RESUMO,
        DECODE(TP_OCUPACAO,'O','OCUPADO','R','RESERVADO','M','MANUTENCAO','I','INFECTADO','A','ACOMPANHANTE','V','VAGO') AS TP_OCUPACAO,
        DECODE(STATUSLIMPEZA,'L','HIGIENIZACAO','H','LIMPEZA','C','CAMAREIRA','P','POS_LIMPEZA') AS STATUSLIMPEZA,
        SN_EXTRA,
        CD_TIP_ACOM,
        DIA_NO_LEITO,
        ENTRADA_DETERIORACAO,
        SAIDA_DETERIORACAO,
        HEMODIALISE,
        ENTRADA_AVC,
        SAIDA_AVC,
        SCA,
        PREV_ALTA,
        DECODE(NM_PACIENTE,NULL,NULL,DECODE(AGENDABLOCOCIRURGICO,1,'BLOCO',NULL)) AS BLC,
        DECODE(NM_PACIENTE,NULL,NULL,DECODE(AGENDAHEMODINAMICA,1,'TRUE',NULL)) AS HMD,
        DECODE(NM_PACIENTE,NULL,NULL,DECODE(AGENDAENDOSCOPIA,1,'TRUE',NULL)) AS ENDSC,
        DECODE(NM_PACIENTE,NULL,NULL,DECODE(EVOLUCAOENFERMAGEM,1,'RED',2,'YELLOW','GREEN')) AS EVOLENF,
        DECODE(NM_PACIENTE,NULL,NULL,DECODE(PRESCRICAOMEDICA,1,'RED',2,'YELLOW','GREEN')) AS PRESCMED,
        DECODE(NM_PACIENTE,NULL,NULL,DECODE(PRESCRICAOABERTA,1,'RED','GREEN')) AS PRESCMEDAB,
        DECODE(NM_PACIENTE,NULL,NULL,DECODE(CHECAGEMMEDICACAO,1,'RED','GREEN')) AS CKG,
        DECODE(NM_PACIENTE,NULL,NULL,DECODE(PARECERMEDICO,1,'RED',2,'YELLOW','GREEN')) AS PARMED,
        DECODE(NM_PACIENTE,NULL,NULL,PROXIMOHORARIO) AS PXHOR,
        DECODE(NM_PACIENTE,NULL,NULL,DECODE(APRAZAMENTO,1,'RED','GREEN')) AS APRAZ,
        DECODE(NM_PACIENTE,NULL,NULL,DECODE(PROTOCOLOTEV,1,'TRUE',NULL)) AS TEV,
        DECODE(NM_PACIENTE,NULL,NULL,DECODE(PROTOCOLOQUEDA,1,'YELLOW',2,'RED',5,'GREEN')) AS QUEDA,
        DECODE(NM_PACIENTE,NULL,NULL,DECODE(PROTOCOLOBRONCO,1,'YELLOW',2,'RED',5,'GREEN')) AS BRONCO,
        DECODE(NM_PACIENTE,NULL,NULL,DECODE(PROTOCOLODOR,1,'YELLOW',2,'RED',5,'GREEN')) AS DOS,
        DECODE(NM_PACIENTE,NULL,NULL,VLRSCOREENFERMAGEM) AS SCE,
        DECODE(NM_PACIENTE,NULL,NULL,VLRSCOREMEDICO) AS SCM,
        DECODE(NM_PACIENTE,NULL,NULL,Decode(PRECAUCAOAR,1,'GREEN',null)) PAR,
        DECODE(NM_PACIENTE,NULL,NULL,Decode(PRECAUCAOCONTATO,1,'GREEN',null)) PCT,
        DECODE(NM_PACIENTE,NULL,NULL,Decode(PRECAUCAOGOTICULA,1,'GREEN',null)) PGT,
        DECODE(NM_PACIENTE,NULL,NULL,Decode(PRECAUCAOMAXIMA,1,'GREEN',null)) PMX,
        DECODE(NM_PACIENTE,NULL,NULL,Decode(PRECAUCAOPADRAO,1,'GREEN',null)) PPD,
        DECODE(NM_PACIENTE,NULL,NULL,Decode(AVISOALERGIA,1,'GREEN',null)) ALE,
        DECODE(NM_PACIENTE,NULL,NULL,Decode(MONITORAMENTO,1,'YELLOW','GREEN')) MON,
        DECODE(NM_PACIENTE,NULL,NULL,Decode(BALANCOHIDRICO,1,'RED','GREEN')) BLH,
        DECODE(NM_PACIENTE,NULL,NULL,Decode(RESULTADOEXAMES,1,'RESULTADO_EXAME',3,'DOC_PREENCHIDO')) EXA,
        DECODE(NM_PACIENTE,NULL,NULL,Decode(RESULTADOIMAGENS,1,'RESULTADO_IMAGEM',3,'DOC_PREENCHIDO')) IMG,
        DECODE(NM_PACIENTE,NULL,NULL,Decode(PEDIDOFARMACIAATRASADO,1,'RED',Decode(PedidoFarmaciaPendente,1,'ESTOQUE','GREEN'))) PED,
        DECODE(NM_PACIENTE,NULL,NULL,Decode(PEDIDOFARMACIADEVOLUCAO,1,'ESTOQUE',2,'RED','GREEN')) DEV,
        DECODE(NM_PACIENTE,NULL,NULL,Decode(AUDITORIACHECAGEM,1,'RED','GREEN')) AUD,
        DECODE(LOCALPACIENTE,1,'BLOCO',2,'SRPA' ,DECODE(ALTAMEDICA,1,'ALTA' ,DECODE(TP_OCUPACAO,'O','OCUPADO','R','RESERVADO','M','MANUTENCAO','I','INFECTADO','A','ACOMPANHANTE','V','VAGO' ,DECODE(STATUSLIMPEZA,'L','HIGIENIZACAO','H','LIMPEZA','C','CAMAREIRA','P','POS_LIMPEZA',DECODE(TP_OCUPACAO,'L','HIGIENIZACAO'))))) SIT,

        PEDIDOFARMACIAPENDENTE,
        VLRSCOREMEDICO,
        ITENSAPAGAR,
        HINT,
        CASE 
        WHEN CD_FILA_SENHA = 19  THEN 'Real Vida - ATENDIMENTO PREFERENCIAL'   
        WHEN CD_FILA_SENHA = 29  THEN 'Real Vida - ATENDIMENTO NORMAL'
        WHEN CD_FILA_SENHA = 182 THEN 'Real Vida - CONVOCAÇÃO DE TRANSPLANTE'
        WHEN CD_FILA_SENHA = 244 THEN 'Real Vida - PACIENTE COM DEFICIÊNCIA'
        WHEN CD_FILA_SENHA = 246 THEN 'Real Vida - PACIENTE AVC' 
        WHEN CD_FILA_SENHA = 248 THEN 'Real Vida - SUPER IDOSO 80+'
        WHEN CD_FILA_SENHA = 161 THEN 'Real Vida - VIAGEM INTERNACIONAL RECENTE'
        WHEN CD_FILA_SENHA = 196 THEN 'Real Vida - NEUROLOGIA'
        WHEN CD_FILA_SENHA = 210 THEN 'Real Vida - PACIENTE EM CURSO DE QT/RT'
        WHEN CD_FILA_SENHA = 220 THEN 'Real Vida - SÍNDROME GRIPAL' 
        WHEN CD_FILA_SENHA = 221 THEN 'Real Vida - ORTOPEDIA'
        WHEN CD_FILA_SENHA = 222 THEN 'Real Vida - OTORRINOLARINGOLOGIA'
        WHEN CD_FILA_SENHA = 245 THEN 'Real Vida - PACIENTE GESTANTE'
        WHEN CD_FILA_SENHA = 247 THEN 'Real Vida - PACIENTE DOR TORÁCIC'
        WHEN CD_FILA_SENHA = 335 THEN 'Real Vida - TEA'
        WHEN CD_FILA_SENHA = 136 THEN 'Real Vida - CARDIOLOGIA'
        WHEN CD_FILA_SENHA = 17  THEN 'Infante - ATENDIMENTO'
        WHEN CD_FILA_SENHA = 99  THEN 'Infante - PREFERENCIAL- PESSOA COM DEFICIÊNCIA'
        WHEN CD_FILA_SENHA = 100 THEN 'Infante - PREFERENCIAL - GENITORA GRÁVIDA'
        WHEN CD_FILA_SENHA = 168 THEN 'Infante - VIAGEM RECENTE PARA CHINA'
        WHEN CD_FILA_SENHA = 97  THEN 'Infante - PREFERENCIAL - PACIENTE ONCOPEDIATRIA'
        WHEN CD_FILA_SENHA = 162 THEN 'Infante - VIAGEM INTERNACIONAL RECENTE'
        WHEN CD_FILA_SENHA = 175 THEN 'Infante - SÍNDROME GRIPAL' 
        WHEN CD_FILA_SENHA = 98  THEN 'Infante - PREFERENCIAL - RECÉM NASCIDO'
        WHEN CD_FILA_SENHA = 198 THEN 'Infante - VIAGEM RECENTE PARA REGIÃO NORTE BR'
        WHEN CD_FILA_SENHA = 22 THEN 'RM - ATENDIMENTO URGÊNCIA /GESTANTE'
        WHEN CD_FILA_SENHA = 60 THEN 'RM - INTERNAMENTO'
        WHEN CD_FILA_SENHA = 61 THEN 'RM - ATENDIMENTO URGÊNCIA /GINECOLÓGICO'
        WHEN CD_FILA_SENHA = 170 THEN 'RM - VIAGEM INTERNACIONAL RECENTE'
        WHEN CD_FILA_SENHA = 172 THEN 'RM - VIAGEM INTERNACIONAL RECENTE'
        WHEN CD_FILA_SENHA = 178 THEN 'RM - FEBRE E SINTOMAS RESPIRATÓRIOS'
        WHEN CD_FILA_SENHA = 25 THEN 'BV - ATENDIMENTO PREFERENCIAL'
        WHEN CD_FILA_SENHA = 45 THEN 'BV - ATENDIMENTO PEDIATRIA'
        WHEN CD_FILA_SENHA = 53 THEN 'BV - ATENDIMENTO PREFERENCIAL'
        WHEN CD_FILA_SENHA = 54 THEN 'BV - TOMOGRAFIA'
        WHEN CD_FILA_SENHA = 55 THEN 'BV - EXAMES LABORATORIAIS'
        WHEN CD_FILA_SENHA = 56 THEN 'BV - ATENDIMENTO NORMAL'
        WHEN CD_FILA_SENHA = 57 THEN 'BV - EXAMES DE IMAGEM'
        WHEN CD_FILA_SENHA = 58 THEN 'BV - ATENDIMENTO PEDIATRIA'
        WHEN CD_FILA_SENHA = 59 THEN 'BV - ULTRASSONOGRAFIA'
        WHEN CD_FILA_SENHA = 164 THEN 'BV - VIAGEM INTERNACIONAL RECENTE'
        WHEN CD_FILA_SENHA = 165 THEN 'BV - VIAGEM INTERNACIONAL RECENTE'
        WHEN CD_FILA_SENHA = 171 THEN 'BV - VIAGEM RECENTE PARA CHINA'
        WHEN CD_FILA_SENHA = 174 THEN 'BV - FEBRE E SINTOMAS RESPIRATÓRIOS'
        WHEN CD_FILA_SENHA = 228 THEN 'BV - RESSONÂNCIA / TOMOGRAFIA' 
        WHEN CD_FILA_SENHA = 229 THEN 'BV - RAIO X / USG / MAMOGRAFIA'
        WHEN CD_FILA_SENHA = 230 THEN 'BV - SÍNDROME GRIPAL'
        WHEN CD_FILA_SENHA = 233 THEN 'BV - EXAMES AGENDADOS REAL IMAGEM'
        WHEN CD_FILA_SENHA = 234 THEN 'BV - MARCAÇÃO DE EXAMES REAL IMAGEM'
        WHEN CD_FILA_SENHA = 235 THEN 'BV - EXAMES DE IMAGEM PREFERENCIAL'
        WHEN CD_FILA_SENHA = 278 THEN 'BV - ATENDIMENTO PREFERENCIAL'
        WHEN CD_FILA_SENHA = 332 THEN 'BV - SINDROME GRIPAL'
        WHEN CD_FILA_SENHA = 343 THEN 'BV - TEA'
        END DESC_FILA,
        CASE 
          WHEN CD_FILA_SENHA IN (19,29,136,161,182,196,210,220,221,222,244,245,246,247,248,336) THEN 'Real Vida'
          WHEN CD_FILA_SENHA IN (17,97,98,99,100,162,168,175,198) THEN 'Infante'
          WHEN CD_FILA_SENHA IN (22,60,61,170,172,178) THEN 'RM'
          WHEN CD_FILA_SENHA IN (25,45,53,54,55,56,57,58,59,164,165,171,174,228,229,230,233,234,235,278,332,343) THEN 'BV'
        END as emergencia,
        CD_ORI_ATE,
        DS_ORI_ATE,
        MAX(TOTEM) AS TOTEM,
        MAX(NVL(CLASS_CHAMADA,CLASS_INICIO)) AS CLASS_CHAMADA,
        NVL(MAX(NVL(CLASS_CHAMADA,CLASS_INICIO)),SYSDATE) - MAX(TOTEM) AS TEMPO_01, --Totem até Triagem (Iniciar registro do paciente)
        
        MAX(CLASS_INICIO) AS CLASS_INICIO,
        MAX(CLASS_FINAL) AS CLASS_FINAL,
        NVL(MAX(CLASS_FINAL),SYSDATE) - MAX(CLASS_INICIO) AS TEMPO_02, --Triagem (Classificar paciente)
        
        MAX(NVL(AT_ADM_CHAMADA,AT_ADM_INICIO)) AS AT_ADM_CHAMADA,
        MAX(AT_ADM_INICIO) AS AT_ADM_INICIO,
        MAX(AT_ADM_FINAL) AS AT_ADM_FINAL,
        NVL(MAX(AT_ADM_FINAL),SYSDATE) - MAX(NVL(AT_ADM_CHAMADA,AT_ADM_INICIO)) AS TEMPO_03, --Recepção (Cadastro do paciente)
        
        MAX(NVL(AT_MEDICO_CHAMADA,AT_MEDICO_INICIO)) AS AT_MEDICO_CHAMADA,
        NVL(MAX(NVL(AT_MEDICO_CHAMADA,AT_MEDICO_INICIO)),SYSDATE) - MAX(AT_ADM_FINAL) AS TEMPO_04, --Inicio do Atendimento Médico
        
        (SELECT MAX(PDC.DH_FECHAMENTO) 
        FROM 
            DBAMV.PW_DOCUMENTO_CLINICO PDC, 
            DBAMV.PW_EDITOR_CLINICO PEC,
            DBAMV.PRESTADOR PRD, 
            DBAMV.CONSELHO COS
        WHERE PEC.CD_DOCUMENTO_CLINICO = PDC.CD_DOCUMENTO_CLINICO
            AND PDC.CD_PRESTADOR = PRD.CD_PRESTADOR
            AND PRD.CD_CONSELHO = COS.CD_CONSELHO
            AND COS.TP_CONSELHO = 1 --CRM
            AND PEC.CD_DOCUMENTO IN (730,566,1130,1131,1298) --DOCUMENTOS DE EVOLUÇÃO MEDICA
            AND PDC.CD_ATENDIMENTO = ATENDIMENTO
            ) DH_EVOL_MED,
        NVL((SELECT MAX(PDC.DH_FECHAMENTO) 
                            FROM 
                                DBAMV.PW_DOCUMENTO_CLINICO PDC, 
                                DBAMV.PW_EDITOR_CLINICO PEC,
                                DBAMV.PRESTADOR PRD, 
                                DBAMV.CONSELHO COS
                            WHERE PEC.CD_DOCUMENTO_CLINICO = PDC.CD_DOCUMENTO_CLINICO
                                AND PDC.CD_PRESTADOR = PRD.CD_PRESTADOR
                                AND PRD.CD_CONSELHO = COS.CD_CONSELHO
                                AND COS.TP_CONSELHO = 1 --CRM
                                AND PEC.CD_DOCUMENTO IN (730,566,1130,1131,1298) --DOCUMENTOS DE EVOLUÇÃO MEDICA
                                AND PDC.CD_ATENDIMENTO = ATENDIMENTO
                                ), SYSDATE) - MAX(NVL(AT_MEDICO_CHAMADA,AT_MEDICO_INICIO)) AS TEMPO_05, -- Em atendimento médico
                                
        MAX(HR_PRE_MED) AS DH_PRE_MED,
        MAX(HR_SOLSAI_PRO) AS DH_SOLSAI_PRO,
        MAX(DH_DISPENSACAO_FARM) AS DH_DISPENSACAO_FARM,
        NVL(MAX(DH_DISPENSACAO_FARM),SYSDATE) - MAX(HR_SOLSAI_PRO) AS TEMPO_06, --Dispensação Farmacia
        
        MAX(DH_CHECAGEM)AS DH_CHECAGEM,
        NVL(MAX(DH_CHECAGEM),SYSDATE) - NVL(MAX(DH_DISPENSACAO_FARM),MAX(HR_PRE_MED)) AS TEMPO_07 --Administração medicação
FROM (
            SELECT 
                STTP.DS_TIPO_TEMPO_PROCESSO,
                NVL(SCP.CD_CATEGORIA_PROCESSO,'0')CD_CATEGORIA_PROCESSO,
                NVL(SCP.ds_categoria_processo,'ALTA MÉDICA')ds_categoria_processo,
                STP.DH_PROCESSO,
                tma.DS_SENHA,
                ATE.CD_ATENDIMENTO,
                ATE.CD_ATENDIMENTO AS ATENDIMENTO,
                ATE.DT_ATENDIMENTO,
                ATE.DT_ALTA_MEDICA,
                DBAMV.FNC_DES_OBTER_INICIAIS(TMA.NM_PACIENTE,1) AS NM_PACIENTE,
                CON.NM_CONVENIO,
                TMA.CD_FILA_SENHA,
                OA.CD_ORI_ATE,
                OA.DS_ORI_ATE,
                TMP_MED.DH_DISPENSACAO_FARM,
                TMP_MED.DH_CHECAGEM,
                TMP_MED.HR_PRE_MED,
                TMP_MED.HR_SOLSAI_PRO,
                LEITOS.CD_LEITO,
                LEITOS.DS_RESUMO,
                LEITOS.TP_OCUPACAO,
                LEITOS.STATUSLIMPEZA,
                LEITOS.SN_EXTRA,
                LEITOS.CD_TIP_ACOM
                ,REGEXP_REPLACE(PRE.NM_PRESTADOR, '\s([A-Za-z])[A-Za-z]+', ' \1.') PRESTADO_MED
                ,(SELECT Trunc(SYSDATE - DT_MOV_INT) FROM mov_int WHERE CD_LEITO = ATE.CD_LEITO AND CD_ATENDIMENTO = ATE.CD_ATENDIMENTO AND DT_LIB_MOV IS NULL) AS DIA_NO_LEITO
                ,(SELECT Max(VDIC.DH_FECHAMENTO) FROM DBAMV.VDIC_PW_RESPOSTA_DOCUMENTO VDIC WHERE VDIC.CD_DOCUMENTO IN (1291)  AND VDIC.TP_STATUS = 'FECHADO' and VDIC.CD_ATENDIMENTO = ATE.CD_ATENDIMENTO) AS ENTRADA_DETERIORACAO
                ,(SELECT Max(VDIC.DH_FECHAMENTO) FROM DBAMV.VDIC_PW_RESPOSTA_DOCUMENTO VDIC WHERE VDIC.CD_DOCUMENTO IN (1292)  AND VDIC.TP_STATUS = 'FECHADO' and VDIC.CD_ATENDIMENTO = ATE.CD_ATENDIMENTO) AS SAIDA_DETERIORACAO
                ,(SELECT Max(VDIC.DH_FECHAMENTO) FROM DBAMV.VDIC_PW_RESPOSTA_DOCUMENTO VDIC WHERE VDIC.CD_DOCUMENTO IN (1408)  AND VDIC.TP_STATUS = 'FECHADO' and VDIC.CD_ATENDIMENTO = ATE.CD_ATENDIMENTO) AS HEMODIALISE /*--WHERE VDIC.CD_DOCUMENTO IN (1488)*/
                ,(SELECT Max(VDIC.DH_FECHAMENTO) FROM DBAMV.VDIC_PW_RESPOSTA_DOCUMENTO VDIC WHERE VDIC.CD_DOCUMENTO IN (886,809) AND VDIC.TP_STATUS = 'FECHADO' and VDIC.CD_ATENDIMENTO = ATE.CD_ATENDIMENTO) AS ENTRADA_AVC
                ,(SELECT Max(VDIC.DH_FECHAMENTO) FROM DBAMV.VDIC_PW_RESPOSTA_DOCUMENTO VDIC WHERE VDIC.CD_DOCUMENTO IN (961)   AND VDIC.TP_STATUS = 'FECHADO' and VDIC.CD_ATENDIMENTO = ATE.CD_ATENDIMENTO) AS SAIDA_AVC
                ,(SELECT Max(VDIC.DH_FECHAMENTO) FROM DBAMV.VDIC_PW_RESPOSTA_DOCUMENTO VDIC WHERE VDIC.CD_DOCUMENTO IN (835)   AND VDIC.TP_STATUS = 'FECHADO' and VDIC.CD_ATENDIMENTO = ATE.CD_ATENDIMENTO) AS SCA
                ,(SELECT VIE.DS_RESPOSTA 
                        FROM DBAMV.VDIC_PW_RESPOSTA_DOCUMENTO VIE
                        WHERE VIE.CD_DOCUMENTO IN (1106)
                        AND VIE.TP_STATUS = 'FECHADO'
                        AND VIE.DS_IDENTIFICADOR_FILHO = 'dt_pre_alta_1'
                        AND VIE.DH_FECHAMENTO IN (
                                                    SELECT Max(VDIC.DH_FECHAMENTO)
                                                    FROM DBAMV.VDIC_PW_RESPOSTA_DOCUMENTO VDIC
                                                    WHERE VDIC.CD_DOCUMENTO IN (1106)
                                                    AND VDIC.TP_STATUS = 'FECHADO'
                                                    AND VDIC.DS_IDENTIFICADOR_FILHO = 'dt_pre_alta_1'
                                                    and VDIC.CD_ATENDIMENTO = ATE.CD_ATENDIMENTO
                                                )
                        AND VIE.CD_ATENDIMENTO = ATE.CD_ATENDIMENTO) AS PREV_ALTA
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'CHECAGEMMEDICACAO',ATE.CD_MULTI_EMPRESA) CHECAGEMMEDICACAO
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'PROXIMOHORARIO',ATE.CD_MULTI_EMPRESA) PROXIMOHORARIO
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'APRAZAMENTO',ATE.CD_MULTI_EMPRESA) APRAZAMENTO
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'PEDIDOFARMACIAPENDENTE',ATE.CD_MULTI_EMPRESA) PEDIDOFARMACIAPENDENTE
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'PEDIDOFARMACIAATRASADO',ATE.CD_MULTI_EMPRESA) PEDIDOFARMACIAATRASADO
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'PRESCRICAOMEDICA',ATE.CD_MULTI_EMPRESA) PRESCRICAOMEDICA
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'PRESCRICAOABERTA',ATE.CD_MULTI_EMPRESA) PRESCRICAOABERTA
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'PARECERMEDICO',ATE.CD_MULTI_EMPRESA) PARECERMEDICO
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'EVOLUCAOENFERMAGEM',ATE.CD_MULTI_EMPRESA) EVOLUCAOENFERMAGEM
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'PROTOCOLOTEV_SEMINDICE',ATE.CD_MULTI_EMPRESA) PROTOCOLOTEV
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'PROTOCOLOQUEDA',ATE.CD_MULTI_EMPRESA) PROTOCOLOQUEDA
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'PROTOCOLOBRONCO',ATE.CD_MULTI_EMPRESA) PROTOCOLOBRONCO
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'PROTOCOLODOR',ATE.CD_MULTI_EMPRESA) PROTOCOLODOR
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'VLRSCOREENFERMAGEM',ATE.CD_MULTI_EMPRESA) VLRSCOREENFERMAGEM
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'VLRSCOREMEDICO',ATE.CD_MULTI_EMPRESA) VLRSCOREMEDICO
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'AGENDABLOCOCIRURGICO',ATE.CD_MULTI_EMPRESA) AGENDABLOCOCIRURGICO
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'AGENDAHEMODINAMICA',ATE.CD_MULTI_EMPRESA) AGENDAHEMODINAMICA
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'AGENDAENDOSCOPIA',ATE.CD_MULTI_EMPRESA) AGENDAENDOSCOPIA
                ,Dbamv.Fnc_Painel_Vigilancia_Epidemio(ATE.CD_ATENDIMENTO,'PRECAUCAOGOTICULA',ATE.CD_MULTI_EMPRESA) PRECAUCAOGOTICULA
                ,Dbamv.Fnc_Painel_Vigilancia_Epidemio(ATE.CD_ATENDIMENTO,'PRECAUCAOCONTATO',ATE.CD_MULTI_EMPRESA) PRECAUCAOCONTATO
                ,Dbamv.Fnc_Painel_Vigilancia_Epidemio(ATE.CD_ATENDIMENTO,'PRECAUCAOAR',ATE.CD_MULTI_EMPRESA) PRECAUCAOAR
                ,Dbamv.Fnc_Painel_Vigilancia_Epidemio(ATE.CD_ATENDIMENTO,'PRECAUCAOMAXIMA',ATE.CD_MULTI_EMPRESA) PRECAUCAOMAXIMA
                ,Dbamv.Fnc_Painel_Vigilancia_Epidemio(ATE.CD_ATENDIMENTO,'PRECAUCAOPADRAO',ATE.CD_MULTI_EMPRESA) PRECAUCAOPADRAO
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'AVISOALERGIATELA',ATE.CD_MULTI_EMPRESA) AVISOALERGIA
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'RESULTADOEXAMES',ATE.CD_MULTI_EMPRESA) RESULTADOEXAMES
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'PEDIDOFARMACIADEVOLUCAO',ATE.CD_MULTI_EMPRESA) PEDIDOFARMACIADEVOLUCAO
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'BALANCOHIDRICO',ATE.CD_MULTI_EMPRESA) BALANCOHIDRICO
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'ALTAMEDICA',ATE.CD_MULTI_EMPRESA) ALTAMEDICA
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'RESULTADOIMAGENS',ATE.CD_MULTI_EMPRESA) RESULTADOIMAGENS
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'MONITORAMENTO',ATE.CD_MULTI_EMPRESA) MONITORAMENTO
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'AUDITORIACHECAGEM',ATE.CD_MULTI_EMPRESA) AUDITORIACHECAGEM
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'LOCALPACIENTE',ATE.CD_MULTI_EMPRESA) LOCALPACIENTE
                ,Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'ITENSAPAGAR',ATE.CD_MULTI_EMPRESA) ITENSAPAGAR
                ,Rtrim(Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'PROXIMAMEDICACAO',ATE.CD_MULTI_EMPRESA))||' '|| Rtrim(Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'PEDIDOMEDICACAOATRASADA',ATE.CD_MULTI_EMPRESA))||' '|| Rtrim(Dbamv.Fnc_Painel_Assistencial(ATE.CD_ATENDIMENTO,'MEDICACAOATRASADA',ATE.CD_MULTI_EMPRESA)) HINT
    
                
            FROM 
                SACR_TEMPO_PROCESSO STP,
                SACR_TIPO_TEMPO_PROCESSO STTP,
                SACR_CATEGORIA_PROCESSO SCP,
                DBAMV.ATENDIME ATE,
                DBAMV.PRESTADOR PRE,
                DBAMV.TRIAGEM_ATENDIMENTO TMA,
                DBAMV.ORI_ATE OA,
                DBAMV.CONVENIO CON,
                (SELECT * FROM
                  (SELECT * FROM
                    (SELECT
                    ATE.CD_ATENDIMENTO,
                    PAC.NM_PACIENTE,
                    ATE.CD_ORI_ATE,
                    ATE.CD_CONVENIO,
                    ATE.DT_ATENDIMENTO,
                    MAX(PMD.CD_PRE_MED) AS CD_PRE_MED,
                    MAX(PMD.HR_PRE_MED) AS HR_PRE_MED,
                    MAX(SSP.CD_SOLSAI_PRO) AS CD_SOLSAI_PRO,
                    MAX(SSP.HR_SOLSAI_PRO) AS HR_SOLSAI_PRO,
                    --SSP.TP_SITUACAO,
                    MAX(MES.HR_MVTO_ESTOQUE) AS DH_DISPENSACAO_FARM,
                    MAX(HIPC.DH_CHECAGEM) AS DH_CHECAGEM,
                    (
                        RANK() OVER (
                            PARTITION BY ATE.CD_ATENDIMENTO
                            ORDER BY
                                PMD.CD_PRE_MED DESC,
                                MES.HR_MVTO_ESTOQUE DESC
                        )
                    ) AS NR_ORD
                FROM
                    DBAMV.ATENDIME ATE,
                    DBAMV.PRE_MED PMD,
                    DBAMV.ITPRE_MED IPM,
                    DBAMV.SOLSAI_PRO SSP,
                    DBAMV.ITSOLSAI_PRO ISSP,
                    DBAMV.MVTO_ESTOQUE MES,
                    DBAMV.HRITPRE_CONS HIPC,
                    DBAMV.ITMVTO_ESTOQUE IME,
                    DBAMV.PACIENTE PAC
                    /*RELACIONAMENTO*/
                WHERE
                    PMD.CD_ATENDIMENTO = ATE.CD_ATENDIMENTO
                    AND SSP.CD_PRE_MED = PMD.CD_PRE_MED
                    AND PMD.CD_PRE_MED = IPM.CD_PRE_MED
                    AND SSP.CD_SOLSAI_PRO = ISSP.CD_SOLSAI_PRO(+)
                    AND SSP.CD_SOLSAI_PRO = MES.CD_SOLSAI_PRO(+)
                    AND IPM.CD_ITPRE_MED = HIPC.CD_ITPRE_MED(+) --AND IPM.CD_ITPRE_MED = IME.CD_ITPRE_MED
                    AND IME.CD_ITSOLSAI_PRO(+) = ISSP.CD_ITSOLSAI_PRO
                    AND PAC.CD_PACIENTE = ATE.CD_PACIENTE
                    /*FILTROS*/
                    AND ATE.DT_ALTA IS NULL
                    AND ATE.DT_ATENDIMENTO >= TRUNC (SYSDATE)-1
                    AND ATE.TP_ATENDIMENTO = 'U' 
                    --AND ATE.CD_ORI_ATE = 2
                GROUP BY
                    ATE.CD_ATENDIMENTO,
                    ATE.CD_ORI_ATE,
                    ATE.CD_CONVENIO,
                    ATE.DT_ATENDIMENTO,
                    PMD.CD_PRE_MED,
                    PMD.HR_PRE_MED,
                    SSP.CD_SOLSAI_PRO,
                    SSP.HR_SOLSAI_PRO,
                    SSP.TP_SITUACAO,
                    PAC.NM_PACIENTE,
                    MES.HR_MVTO_ESTOQUE
                ORDER BY
                    DH_CHECAGEM DESC,
                    1
            ) BASE
        WHERE
            NR_ORD = 1
      ) 
    )TMP_MED,
     (
        SELECT  
          Leito.Cd_leito
          ,Leito.Cd_Leito_Aih
          ,Leito.Cd_Unid_Int
          ,Leito.Sn_Extra
          ,Leito.Ds_Resumo
          ,Leito.TP_OCUPACAO
          ,SolicLimpeza.StatusLimpeza
          ,leito.cd_tip_acom
        FROM 
          Dbamv.Leito ,
          (
          SELECT  Solic_Limpeza.Cd_Leito
          ,Decode(Solic_Limpeza.Dt_Inicio_Higieniza,NULL,'H',Decode(solic_limpeza.dt_hr_fim_higieniza,NULL,'L',Decode(Solic_Limpeza.Dt_Hr_Fim_Rouparia,NULL,'C',Decode(Solic_Limpeza.Dt_Hr_Fim_Pos_higieniza,NULL,'P',Decode(Solic_Limpeza.Dt_Realizado,NULL,'L'))))) StatusLimpeza
          FROM Dbamv.Solic_Limpeza
          WHERE To_Char(Solic_Limpeza.Dt_Solic_Limpeza, 'dd/mm/rrrr')||' '||To_Char(Solic_Limpeza.Hr_Solic_Limpeza, 'hh24:mi') IS NOT NULL
          AND To_Char(Solic_Limpeza.Dt_Hr_Fim_pos_higieniza, 'dd/mm/rrrr hh24:mi') IS null
          AND (Solic_Limpeza.Cd_Leito, To_Date(To_Char(Solic_Limpeza.Dt_Solic_Limpeza, 'dd/mm/rrrr')||' '||To_Char(Solic_Limpeza.Hr_Solic_Limpeza, 'hh24:mi'), 'dd/mm/yyyy hh24:mi')) IN ( SELECT Solic_Limpeza.Cd_Leito , MAX(To_Date(To_Char(Solic_Limpeza.Dt_Solic_Limpeza, 'dd/mm/rrrr')||' '||To_Char(Solic_Limpeza.Hr_Solic_Limpeza, 'hh24:mi'), 'dd/mm/yyyy hh24:mi')) DtInicioLimpeza FROM Dbamv.solic_limpeza GROUP BY Solic_limpeza.cd_leito )
          ) SolicLimpeza
        WHERE Leito.Cd_Leito = SolicLimpeza.Cd_Leito(+)
          AND Leito.Dt_Desativacao is null 
      ) LEITOS
            --LIGAÇÕES
            WHERE STP.CD_TIPO_TEMPO_PROCESSO (+) = STTP.CD_TIPO_TEMPO_PROCESSO
            AND STTP.cd_categoria_processo = SCP.cd_categoria_processo (+)
            AND STP.CD_ATENDIMENTO = ATE.CD_ATENDIMENTO(+)
            AND TMA.CD_TRIAGEM_ATENDIMENTO(+) = STP.CD_TRIAGEM_ATENDIMENTO
            AND OA.CD_ORI_ATE(+) = ATE.CD_ORI_ATE
            AND ATE.CD_CONVENIO = CON.CD_CONVENIO(+)
            AND ATE.CD_ATENDIMENTO = TMP_MED.CD_ATENDIMENTO(+)
            AND ATE.CD_PRESTADOR = PRE.CD_PRESTADOR(+)
            AND ATE.CD_LEITO = LEITOS.CD_LEITO(+)
            --FILTROS
            AND DH_PROCESSO >= TRUNC(SYSDATE)-1
            AND DH_PROCESSO < TRUNC(SYSDATE) + INTERVAL '24' HOUR
            AND ATE.DT_ALTA_MEDICA IS NULL
            AND   (TMA.CD_FILA_SENHA      IN (19,29,182,244,246,248,161,196,210,220,221,222,245,247,335,136,17,99,100,168,97,162,175,98,198,22,60,61,170,172,178)--UNIDADES AGAMENOM
                OR TMA.CD_FILA_SENHA   IN (25,26,27,43,44,45,53,54,55,56,57,58,59,164,165,171,174,228,229,230,233,234,235,278,332,343,345,346)) --UNIDADES BV)
                --order by CD_ATENDIMENTO, dh_processo desc 
    ) 
        PIVOT (
            MAX(DH_PROCESSO) 
            FOR DS_TIPO_TEMPO_PROCESSO IN(
                'CADASTRO NO TOTEM' AS TOTEM, 
                'CLASSIFICAÇÃO CHAMADA' AS CLASS_CHAMADA, 
                'CLASSIFICAÇÃO INÍCIO' AS CLASS_INICIO, 
                'CLASSIFICAÇÃO FINAL' AS CLASS_FINAL, 
                'ATENDIMENTO ADMINISTRATIVO CHAMADA' AS AT_ADM_CHAMADA, 
                'ATENDIMENTO ADMINISTRATIVO INÍCIO' AS AT_ADM_INICIO, 
                'ATENDIMENTO ADMINISTRATIVO FINAL' AS AT_ADM_FINAL, 
                'ATENDIMENTO MÉDICO CHAMADA' AS AT_MEDICO_CHAMADA, 
                'ATENDIMENTO MÉDICO INÍCIO' AS AT_MEDICO_INICIO,
                'ATENDIMENTO MÉDICO FINAL' AS AT_MEDICO_FINAL,
                'ATENDIMENTO MÉDICO ALTA' AS AT_MEDICO_ALTA 
            )
        )
        
        GROUP BY 
        CD_ATENDIMENTO,
        DT_ATENDIMENTO,
        DT_ALTA_MEDICA,
        NM_PACIENTE,
        CD_FILA_SENHA,
        DS_SENHA,
        CD_ORI_ATE,
        DS_ORI_ATE,
        DH_DISPENSACAO_FARM,
        NM_CONVENIO,
        DH_CHECAGEM,
        HR_PRE_MED,
        HR_SOLSAI_PRO,
        CD_LEITO,
        DS_RESUMO,
        DECODE(TP_OCUPACAO,'O','OCUPADO','R','RESERVADO','M','MANUTENCAO','I','INFECTADO','A','ACOMPANHANTE','V','VAGO'),
        DECODE(STATUSLIMPEZA,'L','HIGIENIZACAO','H','LIMPEZA','C','CAMAREIRA','P','POS_LIMPEZA'),
        SN_EXTRA,
        CD_TIP_ACOM,
        DIA_NO_LEITO,
        ENTRADA_DETERIORACAO,
        SAIDA_DETERIORACAO,
        HEMODIALISE,
        ENTRADA_AVC,
        SAIDA_AVC,
        SCA,
        PREV_ALTA,
        CHECAGEMMEDICACAO,
        PROXIMOHORARIO,
        APRAZAMENTO,
        PEDIDOFARMACIAPENDENTE,
        PEDIDOFARMACIAATRASADO,
        PRESCRICAOMEDICA,
        PRESCRICAOABERTA,
        PARECERMEDICO,
        EVOLUCAOENFERMAGEM,
        PROTOCOLOTEV,
        PROTOCOLOQUEDA,
        PROTOCOLOBRONCO,
        PROTOCOLODOR,
        VLRSCOREENFERMAGEM,
        VLRSCOREMEDICO,
        AGENDABLOCOCIRURGICO,
        AGENDAHEMODINAMICA,
        AGENDAENDOSCOPIA,
        PRECAUCAOGOTICULA,
        PRECAUCAOCONTATO,
        PRECAUCAOAR,
        PRECAUCAOMAXIMA,
        PRECAUCAOPADRAO,
        AVISOALERGIA,
        RESULTADOEXAMES,
        PEDIDOFARMACIADEVOLUCAO,
        BALANCOHIDRICO,
        ALTAMEDICA,
        RESULTADOIMAGENS,
        MONITORAMENTO,
        AUDITORIACHECAGEM,
        LOCALPACIENTE,
        ITENSAPAGAR,
        HINT,
        PRESTADO_MED,
        DECODE(LOCALPACIENTE,1,'BLOCO',2,'SRPA' ,DECODE(ALTAMEDICA,1,'ALTA' ,DECODE(TP_OCUPACAO,'O','OCUPADO','R','RESERVADO','M','MANUTENCAO','I','INFECTADO','A','ACOMPANHANTE','V','VAGO' ,DECODE(STATUSLIMPEZA,'L','HIGIENIZACAO','H','LIMPEZA','C','CAMAREIRA','P','POS_LIMPEZA',DECODE(TP_OCUPACAO,'L','HIGIENIZACAO')))))


    ORDER BY DT_ATENDIMENTO ASC, TOTEM DESC, EMERGENCIA DESC