SELECT * FROM SYS.ALL_TAB_COLUMNS
WHERE OWNER = 'DBAMV'
AND 
--COLUMN_NAME LIKE '%CD_PARE%'
TABLE_NAME LIKE '%PARE%'

ORDER BY 2,3
;
--SAC_SOLIC_PARECER
--ACAO_PARECER_MEDICO
--COBRANCA_PARECER
--SOLIC_PARECER
--VDIC_LISTA_PARECER_MEDICO
SELECT 
CD_PARECER_MEDICO
, CODIGO_DO_ATENDIMENTO
, DATA_SOLICITACAO
, REGEXP_REPLACE(NOME_DO_PACIENTE, '\s([A-Za-z])[A-Za-z]+', ' \1.') AS NM_PACIENTE
, NOME_DO_SETOR
, NOME_DO_LEITO
, REGEXP_REPLACE(NOME_DO_PRESTADOR_SOLICITANTE, '\s([A-Za-z])[A-Za-z]+', ' \1.') AS PRESTADOR_SOLICITANTE
, ESPECIALIDADE_REQUISITADA
, STATUS_SITUACAO
, ROUND(((SYSDATE - DATA_SOLICITACAO)*24 *60),0) AS TEMPO
, TO_CHAR(TO_DATE('00:00', 'HH24:MI') + NUMTODSINTERVAL(ROUND(((SYSDATE - DATA_SOLICITACAO)*24 *60),0), 'MINUTE'), 'HH24:MI') AS HM_TEMPO

FROM VDIC_LISTA_PARECER_MEDICO PAR, DBAMV.ATENDIME ATE
WHERE ATE.CD_ATENDIMENTO = PAR.CODIGO_DO_ATENDIMENTO

AND UPPER(STATUS_SITUACAO) = 'SOLICITADO'
AND TRUNC(DATA_SOLICITACAO) >= TRUNC(SYSDATE)
AND ATE.DT_ALTA_MEDICA IS NULL