SELECT 
ATE.CD_ATENDIMENTO
,(SELECT REGEXP_REPLACE(NM_PACIENTE, '\s([A-Za-z])[A-Za-z]+', ' \1.') FROM PACIENTE WHERE CD_PACIENTE = ATE.CD_PACIENTE) NM_PACIENTE
,ATE.DT_ATENDIMENTO
,(SELECT MIN(PMD.CD_PRE_MED) FROM DBAMV.PRE_MED PMD
      WHERE TP_PRE_MED = 'M'
      AND PMD.DT_PRE_MED >= TRUNC(SYSDATE)
      AND PMD.DT_PRE_MED < TRUNC(SYSDATE) + INTERVAL '24' HOUR
      AND CD_ATENDIMENTO = ATE.CD_ATENDIMENTO) CD_PRE_MED
,(SELECT MIN(PMD.DT_PRE_MED) FROM DBAMV.PRE_MED PMD
      WHERE TP_PRE_MED = 'M'
      AND PMD.DT_PRE_MED >= TRUNC(SYSDATE)
      AND PMD.DT_PRE_MED < TRUNC(SYSDATE) + INTERVAL '24' HOUR
      AND CD_ATENDIMENTO = ATE.CD_ATENDIMENTO) DT_PRE_MED
, UI.CD_UNID_INT
, UI.DS_UNID_INT
, LEI.DS_LEITO

,ROUND(((SYSDATE - TRUNC(SYSDATE))*24*60),0) AS TEMPO
,TO_CHAR(TO_DATE('00:00', 'HH24:MI') + NUMTODSINTERVAL(ROUND(((SYSDATE - TRUNC(SYSDATE))*24*60),0), 'MINUTE'), 'HH24:MI') AS HM_TEMPO

FROM 
DBAMV.ATENDIME ATE
,DBAMV.LEITO LEI
,DBAMV.UNID_INT UI

WHERE LEI.CD_LEITO = ATE.CD_LEITO 
  AND UI.CD_UNID_INT = LEI.CD_UNID_INT

AND ATE.TP_ATENDIMENTO = 'I'
AND ATE.DT_ALTA IS NULL
AND (SELECT MIN(PMD.CD_PRE_MED) FROM DBAMV.PRE_MED PMD
      WHERE TP_PRE_MED = 'M'
      AND PMD.DT_PRE_MED >= TRUNC(SYSDATE)
      AND PMD.DT_PRE_MED < TRUNC(SYSDATE) + INTERVAL '24' HOUR
      AND CD_ATENDIMENTO = ATE.CD_ATENDIMENTO) IS NULL
--AND UI.CD_UNID_INT <> 91

ORDER BY UI.DS_UNID_INT