      SELECT 
        A.CD_ATENDIMENTO,
        A.CD_PACIENTE,
        (SELECT REGEXP_REPLACE(NM_PACIENTE, '\s([A-Za-z])[A-Za-z]+', ' \1.') FROM PACIENTE WHERE CD_PACIENTE = A.CD_PACIENTE) NM_PACIENTE,
        UI.CD_UNID_INT,
        UI.DS_UNID_INT,
        LEI.DS_LEITO,
        P.CD_PED_LAB AS CD_PED_LAB,
        IPL.CD_EXA_LAB,
        (SELECT MAX(NM_EXA_LAB) FROM DBAMV.EXA_LAB WHERE CD_EXA_LAB = IPL.CD_EXA_LAB) AS DS_EXA_LAB,
        (SELECT MAX(NM_SET_EXA) FROM DBAMV.SET_EXA WHERE CD_SET_EXA = IPL.CD_SET_EXA) AS NM_SET_EXA,
        (DBAMV.FNC_MV_RECUPERA_DATA_HORA(P.DT_PEDIDO, P.HR_PED_LAB)) AS DH_PED_LAB,
        A.DT_ALTA_MEDICA,
        (SELECT MAX(DT_MOVIMENTO) AS DT_MOVIMENTO FROM DBAMV.LOG_MOVIMENTO_EXAME lme
            WHERE lme.DT_MOVIMENTO >= '01/JUL/2024'
            AND lme.DT_MOVIMENTO < TRUNC(SYSDATE)+INTERVAL '24' HOUR
            AND CD_ATENDIMENTO = A.CD_ATENDIMENTO
            AND CD_PED_LAB_RX = P.CD_PED_LAB
            AND DS_MOVIMENTO LIKE '%Amostra associada ao exame foi colhida no Setor%'
              ) AS DH_COLETA_LAB,
        
        ROUND(((SYSDATE - MAX(DBAMV.FNC_MV_RECUPERA_DATA_HORA(P.DT_PEDIDO, P.HR_PED_LAB)))*24*60),0) AS TEMPO,
        TO_CHAR(TO_DATE('00:00', 'HH24:MI') + NUMTODSINTERVAL(ROUND(((SYSDATE - MAX(DBAMV.FNC_MV_RECUPERA_DATA_HORA(P.DT_PEDIDO, P.HR_PED_LAB)))*24*60),0), 'MINUTE'), 'HH24:MI') AS HM_TEMPO,
       /* (SELECT MAX(DT_MOVIMENTO) AS DT_MOVIMENTO FROM DBAMV.LOG_MOVIMENTO_EXAME lme
            WHERE lme.DT_MOVIMENTO >= '01/JUL/2024'
            AND lme.DT_MOVIMENTO < TRUNC(SYSDATE)+INTERVAL '24' HOUR
            AND CD_ATENDIMENTO = A.CD_ATENDIMENTO
            AND CD_PED_LAB_RX = P.CD_PED_LAB
            AND DS_MOVIMENTO LIKE '%Exame revisado%'
              ) AS DH_RESULTADO_LAB,
        
        (SELECT MAX(DT_MOVIMENTO) AS DT_MOVIMENTO FROM DBAMV.LOG_MOVIMENTO_EXAME lme
            WHERE lme.DT_MOVIMENTO >= '01/JUL/2024'
            AND lme.DT_MOVIMENTO < TRUNC(SYSDATE)+INTERVAL '24' HOUR
            AND CD_ATENDIMENTO = A.CD_ATENDIMENTO
            AND CD_PED_LAB_RX = P.CD_PED_LAB
            AND DS_MOVIMENTO LIKE '%Exame Assinado%'
              ) AS DH_LIBERADO_LAB,*/
                
        --(SELECT MAX(HR_SOLSAI_PRO) FROM DBAMV.SOLSAI_PRO WHERE CD_ATENDIMENTO = A.CD_ATENDIMENTO) AS HR_SOLSAI_PRO,
        --(SELECT MAX(HR_MVTO_ESTOQUE) FROM DBAMV.MVTO_ESTOQUE WHERE CD_ATENDIMENTO = A.CD_ATENDIMENTO) AS DH_DISPENSACAO_FARM,
        /*CASE 
          WHEN A.CD_ORI_ATE = 4 THEN (SELECT MAX(HR_MVTO_ESTOQUE) FROM DBAMV.MVTO_ESTOQUE WHERE CD_ATENDIMENTO = A.CD_ATENDIMENTO) 
          ELSE NVL((SELECT  MAX(HR_MVTO_ESTOQUE) FROM DBAMV.MVTO_ESTOQUE MVE, DBAMV.SOLSAI_PRO SSP WHERE MVE.CD_SOLSAI_PRO = SSP.CD_SOLSAI_PRO AND SSP.CD_ATENDIMENTO = A.CD_ATENDIMENTO),SYSDATE) END AS DH_DISPENSACAO_FARM,*/
        (RANK() OVER (PARTITION BY A.CD_ATENDIMENTO ORDER BY P.CD_PED_LAB DESC, P.HR_PED_LAB DESC)) AS NR_ORD

    FROM DBAMV.ATENDIME A,
         DBAMV.PED_LAB P,
         DBAMV.ITPED_LAB IPL,
         DBAMV.SET_EXA S,
         DBAMV.LEITO LEI,
         DBAMV.UNID_INT UI
                    
    WHERE A.CD_ATENDIMENTO = P.CD_ATENDIMENTO
    AND S.CD_SET_EXA(+) = P.CD_SET_EXA
    AND LEI.CD_LEITO = A.CD_LEITO 
    AND UI.CD_UNID_INT = LEI.CD_UNID_INT
    AND P.CD_PED_LAB = IPL.CD_PED_LAB
    
    AND   A.TP_ATENDIMENTO = 'I'
    --AND   A.DT_ATENDIMENTO >= '01/JUL/2024'
    AND   A.DT_ATENDIMENTO < TRUNC(SYSDATE)+INTERVAL '24' HOUR
    AND   A.DT_ALTA IS NULL
    AND   (SELECT MAX(DT_MOVIMENTO) AS DT_MOVIMENTO FROM DBAMV.LOG_MOVIMENTO_EXAME lme
            WHERE CD_ATENDIMENTO = A.CD_ATENDIMENTO
            AND CD_PED_LAB_RX = P.CD_PED_LAB
            AND lme.DT_MOVIMENTO >= TRUNC(SYSDATE)--+INTERVAL '24' HOUR
            AND lme.DT_MOVIMENTO < TRUNC(SYSDATE)+INTERVAL '24' HOUR
            AND DS_MOVIMENTO LIKE '%Amostra associada ao exame foi colhida no Setor%'
              ) IS NULL
    AND P.DT_PEDIDO >= TRUNC(SYSDATE)-- INTERVAL '24' HOUR
    
    group by A.CD_ATENDIMENTO,P.DT_PEDIDO,P.CD_PED_LAB/*, PAC.NM_PACIENTE*/,P.HR_PED_LAB, P.CD_PED_LAB,A.CD_ORI_ATE, A.CD_PACIENTE, UI.CD_UNID_INT, UI.DS_UNID_INT, LEI.DS_LEITO, A.DT_ALTA_MEDICA,  IPL.CD_EXA_LAB,IPL.CD_SET_EXA
    
    
    ORDER BY DH_PED_LAB 