SELECT CD_ATENDIMENTO
      ,CD_PRE_MED
      ,CD_ITPRE_MED
      ,CD_SOLSAI_PRO
      ,CD_ITSOLSAI_PRO
      ,CD_TIP_ESQ
      ,DS_TIP_ESQ
      ,CD_TIP_PRESC
      ,DS_TIP_PRESC
      ,CD_PRODUTO_SOLICITADO
      ,DS_PRODUTO_SOLICITADO
      ,CD_PRODUTO_DISPENSADO
      ,DS_PRODUTO_DISPENSADO
      ,DH_FECHAMENTO_PRESCRICAO
      ,DH_DISPENSACAO_FARM
      ,DH_MEDICACAO
      ,PRIMEIRO_HORARIO
      ,DH_CHECAGEM
      ,DH_CANCELADO
      ,ROUND (((NVL(DH_CHECAGEM,SYSDATE) - DH_FECHAMENTO_PRESCRICAO) * 1440),2) AS Diferenca_em_minutos
      ,ABS((DH_DISPENSACAO_FARM - DH_FECHAMENTO_PRESCRICAO ) * 1440) AS Tmp_Presc_Dispensacao_Farmacia
      ,(DH_CHECAGEM - DH_DISPENSACAO_FARM ) *1440 AS  TMP_Disp_Farmacia_Checagem
      ,NM_PACIENTE
      ,CD_UNID_INT
      ,DS_UNID_INT
      ,TP_SITUACAO
      ,COMPETENCIA
      --ADICIONADO POR 26753 EM 17/05/2024
      ,CD_PRESCRITOR
      ,NM_PRESCRITOR
      FROM (
SELECT RDO.CD_ATENDIMENTO



      ,RDO.CD_PRE_MED
      ,RDO.CD_ITPRE_MED
			,SSP.CD_SOLSAI_PRO
      ,ISSP.CD_ITSOLSAI_PRO
      ,IPM.CD_TIP_ESQ
      ,TE.DS_TIP_ESQ
      ,IPM.CD_TIP_PRESC
      ,TP.DS_TIP_PRESC
      ,PDISSP.CD_PRODUTO AS CD_PRODUTO_SOLICITADO
      ,PDISSP.DS_PRODUTO AS DS_PRODUTO_SOLICITADO
      ,IME.CD_PRODUTO AS CD_PRODUTO_DISPENSADO
      ,PD.DS_PRODUTO AS DS_PRODUTO_DISPENSADO
      ,PM.DH_IMPRESSAO AS DH_FECHAMENTO_PRESCRICAO
      ,IME.DH_MVTO_ESTOQUE AS DH_DISPENSACAO_FARM
      ,HISSP.DH_MEDICACAO AS DH_MEDICACAO
			,DECODE(RANK() OVER (PARTITION BY RDO.CD_ATENDIMENTO, RDO.CD_PRE_MED ORDER BY HISSP.DH_MEDICACAO ASC),1,'PRIMEIRO HORÁRIO') AS PRIMEIRO_HORARIO
      ,(SELECT HIPC.DH_CHECAGEM FROM HRITPRE_CONS HIPC WHERE HIPC.CD_ITPRE_MED (+) = IPM.CD_ITPRE_MED AND HIPC.DH_MEDICACAO (+) = HISSP.DH_MEDICACAO) AS DH_CHECAGEM
      ,IPM.DH_CANCELADO

      --ADICIONADO POR 26753 EM 10/04/2024
      ,PC.NM_PACIENTE
      ,UNI.CD_UNID_INT
      ,UNI.DS_UNID_INT
--      ,DECODE(SSP.TP_SITUACAO,'P', 'PEDIDO',
--                              'S', 'CONFIRMADO',
--                              'C', 'CONFIRMADO PARCIALMENTE',
--                              'A', 'CANCELADA')TP_SITUACAO
      ,TO_DATE('01/'||TO_CHAR(PM.DH_IMPRESSAO,'MM/RRRR'),'DD/MM/RRRR')COMPETENCIA

      --ADICIONADO POR 26753 EM 17/05/2024
      ,PRD.CD_PRESTADOR CD_PRESCRITOR
      ,PRD.NM_PRESTADOR NM_PRESCRITOR
      ,CASE WHEN SSP.TP_SITUACAO = 'A' THEN 'CANCELADO'
            WHEN SSP.TP_SITUACAO = 'P' AND NVL(AVG(IME.QT_MOVIMENTACAO) OVER(PARTITION BY ISSP.CD_ITSOLSAI_PRO ORDER BY ISSP.CD_ITSOLSAI_PRO),ISSP.QT_ATENDIDA) = 0 THEN 'EM ABERTO'
            WHEN (SSP.TP_SITUACAO = 'C' OR SSP.TP_SITUACAO = 'S') AND NVL(AVG(IME.QT_MOVIMENTACAO) OVER(PARTITION BY ISSP.CD_ITSOLSAI_PRO ORDER BY ISSP.CD_ITSOLSAI_PRO),ISSP.QT_ATENDIDA) = 0 THEN 'NÃO ATENDIDO'
            WHEN ISSP.QT_SOLICITADO > NVL(AVG(IME.QT_MOVIMENTACAO) OVER(PARTITION BY ISSP.CD_ITSOLSAI_PRO ORDER BY ISSP.CD_ITSOLSAI_PRO),ISSP.QT_ATENDIDA) THEN 'PARC. ATENDIDO'
            WHEN ISSP.QT_SOLICITADO = NVL(AVG(IME.QT_MOVIMENTACAO) OVER(PARTITION BY ISSP.CD_ITSOLSAI_PRO ORDER BY ISSP.CD_ITSOLSAI_PRO),ISSP.QT_ATENDIDA) THEN 'ATENDIDO'
            END TP_SITUACAO


      FROM DBAMV.REGISTRO_DOCUMENTO_OBRIGATORIO RDO
          ,DBAMV.PW_EDITOR_CLINICO PEC
          ,DBAMV.PW_DOCUMENTO_CLINICO PWD
          ,DBAMV.EDITOR_REGISTRO_CAMPO ERC
          ,DBAMV.EDITOR_CAMPO EC
          ,DBAMV.PRE_MED PM
          ,DBAMV.ITPRE_MED IPM
          ,DBAMV.ATENDIME AT
          ,DBAMV.PACIENTE PC
          ,DBAMV.TIP_ESQ TE
          ,DBAMV.TIP_PRESC TP
          ,DBAMV.ITSOLSAI_PRO ISSP
          ,DBAMV.SOLSAI_PRO SSP
          ,DBAMV.ITMVTO_ESTOQUE IME
          ,DBAMV.HRITSOLSAI_PRO HISSP
          ,DBAMV.HRITPRE_MED HIPM
          ,DBAMV.PRODUTO PD
          ,DBAMV.PRODUTO PDISSP
          ,DBAMV.UNID_INT UNI --ADICIONADO POR 26753 EM 10/04/2024
          ,DBAMV.PRESTADOR PRD --ADICIONADO POR 26753 EM 17/05/2024

WHERE PEC.CD_EDITOR_REGISTRO = RDO.CD_EDITOR_CLINICO
  AND PWD.CD_DOCUMENTO_CLINICO = PEC.CD_DOCUMENTO_CLINICO
  AND ERC.CD_REGISTRO (+) = PEC.CD_EDITOR_REGISTRO
  AND EC.CD_CAMPO(+) = ERC.CD_CAMPO
  AND PM.CD_PRE_MED = RDO.CD_PRE_MED
  AND PM.CD_PRESTADOR = PRD.CD_PRESTADOR --ADICIONADO POR 26753 EM 17/05/2024
  AND IPM.CD_ITPRE_MED = RDO.CD_ITPRE_MED
  AND AT.CD_ATENDIMENTO = RDO.CD_ATENDIMENTO
  AND PC.CD_PACIENTE = AT.CD_PACIENTE
  AND TE.CD_TIP_ESQ (+) = IPM.CD_TIP_ESQ
  AND TP.CD_TIP_PRESC (+) = IPM.CD_TIP_PRESC
  AND ISSP.CD_ITPRE_MED (+) = IPM.CD_ITPRE_MED
  AND SSP.CD_SOLSAI_PRO (+) = ISSP.CD_SOLSAI_PRO
  AND IME.CD_ITSOLSAI_PRO (+) = ISSP.CD_ITSOLSAI_PRO
  AND IME.CD_PRODUTO (+) = ISSP.CD_PRODUTO
  AND HISSP.CD_ITSOLSAI_PRO (+) = ISSP.CD_ITSOLSAI_PRO
  AND HIPM.CD_ITPRE_MED (+) = IPM.CD_ITPRE_MED
  AND HIPM.DH_MEDICACAO (+) = HISSP.DH_MEDICACAO
  AND PD.CD_PRODUTO (+) = IME.CD_PRODUTO
  AND PDISSP.CD_PRODUTO (+) = ISSP.CD_PRODUTO
  AND SSP.CD_UNID_INT = UNI.CD_UNID_INT(+)--ADICIONADO POR 26753 EM 10/04/2024
  AND RDO.CD_DOCUMENTO = 1455
  AND (NVL(PDISSP.CD_ESPECIE,1) = 1 AND NVL(PDISSP.CD_CLASSE,2) = 2 AND NVL(PDISSP.CD_SUB_CLA,65) = 65
    OR NVL(PDISSP.CD_ESPECIE,1) = 1 AND NVL(PDISSP.CD_CLASSE,1) = 1 AND NVL(PDISSP.CD_SUB_CLA,89) = 89
    OR NVL(PDISSP.CD_ESPECIE,1) = 1 AND NVL(PDISSP.CD_CLASSE,1) = 1 AND NVL(PDISSP.CD_SUB_CLA,52) = 52
    OR NVL(PDISSP.CD_ESPECIE,1) = 1 AND NVL(PDISSP.CD_CLASSE,2) = 2 AND NVL(PDISSP.CD_SUB_CLA,52) = 52
    OR NVL(PDISSP.CD_ESPECIE,1) = 1 AND NVL(PDISSP.CD_CLASSE,1) = 1 AND NVL(PDISSP.CD_SUB_CLA,34) = 34
    OR NVL(PDISSP.CD_ESPECIE,1) = 1 AND NVL(PDISSP.CD_CLASSE,2) = 2 AND NVL(PDISSP.CD_SUB_CLA,34) = 34)
  AND EC.DS_IDENTIFICADOR IN ('SN_USO_SEPSE_SIM_1')
  AND UPPER(DBMS_LOB.SUBSTR(ERC.LO_VALOR,4000,1)) = 'TRUE'
  AND PWD.TP_STATUS IN ('FECHADO','ASSINADO')
  AND PWD.DH_CRIACAO >= TRUNC(SYSDATE-1)
	AND PDISSP.CD_PRODUTO NOT IN (6256)
ORDER BY RDO.DT_REFERENCIA DESC, RDO.CD_ATENDIMENTO ASC, RDO.CD_PRE_MED DESC, TP.DS_TIP_PRESC ASC, HISSP.DH_MEDICACAO ASC)
WHERE PRIMEIRO_HORARIO IS NOT NULL