SELECT 
  ATE.CD_ATENDIMENTO,
  ATE.CD_ORI_ATE,
  (SELECT REGEXP_REPLACE(NM_PACIENTE, '\s([A-Za-z])[A-Za-z]+', ' \1.') FROM PACIENTE WHERE CD_PACIENTE = ATE.CD_PACIENTE) AS NM_PACIENTE,
  (SELECT REGEXP_REPLACE(NM_CONVENIO, '\s([A-Za-z])[A-Za-z]+', ' \1.') FROM CONVENIO WHERE CD_CONVENIO = ATE.CD_CONVENIO) AS NM_CONVENIO,
  DBAMV.FNC_MV_RECUPERA_DATA_HORA(ATE.DT_ATENDIMENTO, ATE.HR_ATENDIMENTO) AS DT_ATENDIMENTO,
  (SELECT REGEXP_REPLACE(NM_PRESTADOR, '\s([A-Za-z])[A-Za-z]+', ' \1.') FROM DBAMV.PRESTADOR WHERE CD_PRESTADOR = ATE.CD_PRESTADOR) AS MEDICO_ASSISTENTE,
  UI.CD_UNID_INT,
  UI.DS_UNID_INT,
  ATE.CD_LEITO,
  LEI.DS_RESUMO AS DS_LEITO,
  (SELECT DS_MOT_ALT FROM DBAMV.MOT_ALT WHERE CD_MOT_ALT = ATE.CD_MOT_ALT) AS DS_MOT_ALTA,
  ATE.CD_CID,
  (SELECT DS_CID FROM DBAMV.CID WHERE CD_CID = ATE.CD_CID) AS DS_CID,
  (SELECT DS_ESPECIALID FROM DBAMV.ESPECIALID WHERE CD_ESPECIALID = ATE.CD_ESPECIALID) DS_ESPECIALID,
  ATE.NM_USUARIO_ALTA_MEDICA,
  DBAMV.FNC_MV_RECUPERA_DATA_HORA(ATE.DT_PREVISTA_ALTA, ATE.DT_PREVISTA_ALTA) AS DT_PREVISTA_ALTA,
  DBAMV.FNC_MV_RECUPERA_DATA_HORA(ATE.DT_ALTA_MEDICA, ATE.HR_ALTA_MEDICA) AS DT_ALTA_MEDICA,
  DBAMV.FNC_MV_RECUPERA_DATA_HORA(ATE.DT_ALTA, ATE.HR_ALTA) AS DT_ALTA,
  CASE
    WHEN TRUNC (DBAMV.FNC_MV_RECUPERA_DATA_HORA(ATE.DT_PREVISTA_ALTA, ATE.DT_PREVISTA_ALTA)) = TRUNC (SYSDATE)    THEN 0
    WHEN TRUNC (DBAMV.FNC_MV_RECUPERA_DATA_HORA(ATE.DT_PREVISTA_ALTA, ATE.DT_PREVISTA_ALTA)) = TRUNC (SYSDATE+1)  THEN 1
    WHEN TRUNC (DBAMV.FNC_MV_RECUPERA_DATA_HORA(ATE.DT_PREVISTA_ALTA, ATE.DT_PREVISTA_ALTA)) = TRUNC (SYSDATE+2)  THEN 2
  END AS D_ALTA,
  CASE 
    WHEN DT_PREVISTA_ALTA IS NOT NULL THEN ROUND(TRUNC(DT_PREVISTA_ALTA)-SYSDATE,0)+1
  END AS D_PREV --BASEADO NA QUERY DE ASSERTIVIDADE CRIADA PELA TASCOM & RESTRUTURADA POR MARCLYSON
  --CASE WHEN ATE.DT_ALTA IS NULL THEN trunc( Nvl(To_Date(ATE.DT_PREVISTA_ALTA,'DD/MM/RRRR'),To_Date(SYSDATE,'DD/MM/RRRR')) - To_Date(SYSDATE,'DD/MM/RRRR')) END AS Dias_Alta

FROM DBAMV.ATENDIME ATE,
    DBAMV.LEITO LEI,
    DBAMV.UNID_INT UI
    
WHERE LEI.CD_LEITO = ATE.CD_LEITO
AND UI.CD_UNID_INT = LEI.CD_UNID_INT

AND DBAMV.FNC_MV_RECUPERA_DATA_HORA(ATE.DT_PREVISTA_ALTA, ATE.DT_PREVISTA_ALTA) >= TRUNC(SYSDATE) --INTERVAL '24' HOUR
AND ATE.TP_ATENDIMENTO  = 'I'
AND ATE.DT_ALTA IS NULL