SELECT DISTINCT
      A.CD_REG,
      A.NR_ORD,
      --A.PROC_DEF_KEY_,
      A.DT_ABERTURA,
      A.DT_FECHAMENTO,
      A.CD_DOC,
      A.CD_REGISTRANTE,
      A.NM_REGISTRANTE,
      A.NM_OPERADORA,
      A.DT_ABERTURA_NEGOCIACAO,
      TO_NUMBER (A.NR_INDICE_NEG_AB) AS NR_INDICE_NEG_AB,
      A.DT_ENVIO_PROPOSTA,
      TO_NUMBER (A.NR_INDICE_IPCA_ENVIO) AS NR_INDICE_IPCA_ENVIO,
      A.DT_RECEB_PROPOSTA,
      A.TP_STATUS,
      A.DT_ENVIO_RETIFICACAO,
      A.DT_RECEB_RETIFICACAO,
      A.TP_NEGATIVA,
      COALESCE(A.DT_INICIO_CONTRATO, B.DT_INICIO_CONTRATO) AS DT_INICIO_CONTRATO,
      COALESCE(A.DT_FINAL_CONTRATO, B.DT_FINAL_CONTRATO) AS DT_FINAL_CONTRATO,
      A.DT_ELAB_CONTRATO,
      A.NR_INDICE_IPCA_RETIF,
      A.DT_ENV_CADASTRO,
      A.DT_REC_CADASTRO,
      A.DT_IMPLANTACAO,
      A.NR_INDICE_HCT,
      A.NR_INDICE_DTP,
      A.NR_INDICE_SAD,
      A.NR_INDICE_CONTRATUAL,
      A.TP_REAJUSTE,
      A.DS_OBS_CADASTRO,
      A.DS_OBS_ENVPROPOSTA,
      A.DS_OBS_ENVRETPROPOSTA,
      A.DS_OBS_NEGOCIACAO,
      A.DS_OBS_RECPROPOSTA,
      A.DS_OBS_RECRETPROPOSTA
FROM 
(
SELECT * FROM (
SELECT
    SUBSTR (AHP.BUSINESS_KEY_, INSTR(AHP.BUSINESS_KEY_,'-',1,1)+1)AS CD_REG,
    DENSE_RANK() OVER (PARTITION BY AHV.NM_OPERADORA ORDER BY AHP.START_TIME_ DESC) AS NR_ORD,
    --PROC_DEF_KEY_,
    AHP.START_TIME_ AS DT_ABERTURA,
    AHP.END_TIME_ AS DT_FECHAMENTO,
    AHV.CD_DOC,
    AHV.CD_REGISTRANTE,
    (SELECT NM_USUARIO FROM DBASGU.USUARIOS WHERE CD_USUARIO = AHV.CD_REGISTRANTE) NM_REGISTRANTE,
    CON.CD_CONVENIO,
    AHV.NM_OPERADORA,
    TO_DATE(SUBSTR(AHV.DT_NEGOCIACAO, 1, 10),'YYYY-MM-DD') DT_ABERTURA_NEGOCIACAO,
    REPLACE(AHV.NR_INDICE_NEG_AB, '%', '') AS NR_INDICE_NEG_AB,-- INDICE REFERENCIA DA TRATATIVA DA ABERTURA DE NEGOCIACOES
    TO_DATE(SUBSTR(AHV.DT_ENVPROPOSTA, 1, 10),'YYYY-MM-DD') DT_ENVIO_PROPOSTA,
    REPLACE(AHV.NR_INDICE_IPCA_ENVIO, '%', '') AS NR_INDICE_IPCA_ENVIO, -- INDICE REFERENCIA DA TRATATIVA DE ENVIO
    TO_DATE(SUBSTR(AHV.DT_RETPROPOSTA, 1, 10),'YYYY-MM-DD') DT_RECEB_PROPOSTA,
    CASE when (AHV.TP_STATUS) = 'Sim' THEN 'Proposta Retificada' else 'Proposta Aceita' end AS TP_STATUS,
    TO_DATE(SUBSTR(AHV.DT_ENVRET_PROPOSTA, 1, 10),'YYYY-MM-DD') DT_ENVIO_RETIFICACAO,
    TO_DATE(SUBSTR(AHV.DT_RECRET_PROPOSTA, 1, 10),'YYYY-MM-DD') DT_RECEB_RETIFICACAO,
    CASE WHEN AHV.TP_NEGATIVA = 'true' THEN 'Proposta Negada' ELSE 'Proposta Aceita' END AS TP_NEGATIVA,
    TO_DATE(SUBSTR(AHV.DT_CONTRATO, 1, 10),'YYYY-MM-DD') DT_INICIO_CONTRATO,
    TO_DATE(SUBSTR(AHV.DT_VENCIMENTO, 1, 10),'YYYY-MM-DD') DT_FINAL_CONTRATO,
    TO_DATE(SUBSTR(AHV.DT_ELABORACAO, 1, 10),'YYYY-MM-DD') DT_ELAB_CONTRATO,
    REPLACE(AHV.NR_INDICE_IPCA_RETIF, '%', '') AS NR_INDICE_IPCA_RETIF,
    TO_DATE(SUBSTR(AHV.DT_ENV_CADASTRO, 1, 10),'YYYY-MM-DD') DT_ENV_CADASTRO,
    TO_DATE(SUBSTR(AHV.DT_REC_CADASTRO, 1, 10),'YYYY-MM-DD') DT_REC_CADASTRO,
    TO_DATE(SUBSTR(AHV.DT_IMPLANTACAO, 1, 10),'YYYY-MM-DD') DT_IMPLANTACAO,
    REPLACE(AHV.NR_INDICE_HCT, '%', '') AS NR_INDICE_HCT, -- ADC INDICE DE SEGURANÇA Honorários médicos || Consultas || Terapias UTILIZADO PARA MEDIDA
    REPLACE(AHV.NR_INDICE_DTP, '%', '') AS NR_INDICE_DTP, -- ADC INDICE DE SEGURANÇA Diarias || Taxas || Pacotes UTILIZADO PARA MEDIDA
    REPLACE(AHV.NR_INDICE_SAD, '%', '') AS NR_INDICE_SAD, -- ADC INDICE DE SEGURANÇA Serviços Auxiliares de Diagnósticos. UTILIZADO PARA MEDIDA
    REPLACE(AHV.NR_INDICE_CONTRATUAL, '%', '') AS NR_INDICE_CONTRATUAL,
    CASE WHEN AHV.TP_REAJUSTE = 'true' THEN 'Ativado' ELSE 'Inativado' END AS TP_REAJUSTE, --ADC PARA ATIVAÇÃO DE MEDIDA DOS VALORES DE SEGURANÇA
    AHV.DS_OBS_CADASTRO,
    AHV.DS_OBS_ENVPROPOSTA,
    AHV.DS_OBS_ENVRETPROPOSTA,
    AHV.DS_OBS_NEGOCIACAO,
    AHV.DS_OBS_RECPROPOSTA,
    AHV.DS_OBS_RECRETPROPOSTA
FROM
    (
        select
        *
        from
            (
                select
                    PROC_INST_ID_,
                    name_,
                    TEXT_,
                    '1' AS NR_ORD
                from
                    engine.act_hi_varinst
                order by
                    2
            ) eahv PIVOT (
                MAX(TEXT_) FOR name_ IN (
                'PAR_REGISTRY_ID' AS CD_DOC,
                'INSTANCE_USER' AS CD_REGISTRANTE,
                'COM_ROC_DS_OBSERVACAO_ORIENT' AS DS_OBS_CADASTRO,
                'COM_ROC_DS_OBSERVACAO_E2' AS DS_OBS_ENVPROPOSTA,
                'COM_ROC_DS_OBSERVACAO_E4' AS DS_OBS_ENVRETPROPOSTA,
                'COM_ROC_DS_OBSERVACAO_' AS DS_OBS_NEGOCIACAO,
                'COM_ROC_DS_OBSERVACAO_E3' AS DS_OBS_RECPROPOSTA,
                'COM_ROC_DS_OBSERVACAO_E5' AS DS_OBS_RECRETPROPOSTA,
                'COM_ROC_DT_CONTRATO_1' AS DT_CONTRATO,
                'COM_ROC_DT_ELABORACAO_' AS DT_ELABORACAO,
                'COM_ROC_DT_ENVIO_CONTRATUAL_1' AS DT_ENV_CADASTRO,
                'COM_ROC_DT_ENVIO_PROPOSTA_' AS DT_ENVPROPOSTA,
                'COM_ROC_DT_ENVIO_RETIFICADO_' AS DT_ENVRET_PROPOSTA,
                'COM_ROC_DT_IMPLANTACAO_1' AS DT_IMPLANTACAO,
                'COM_ROC_DT_NEGOCIACAO_' AS DT_NEGOCIACAO,
                'COM_ROC_DT_RECEB_CONTRATUAL_' AS DT_REC_CADASTRO,
                'COM_ROC_DT_RECEBIDO_RETIFICADO_' AS DT_RECRET_PROPOSTA,
                'COM_ROC_DT_RETORNO_PROPOSTA_' AS DT_RETPROPOSTA,
                'COM_ROC_DT_VENCIMENTO_1' AS DT_VENCIMENTO,
                'COM_ROC_NM_OPERADORA_1' AS NM_OPERADORA,
                'COM_ROC_CD_INDICE_IPCA2' AS NR_INDICE_IPCA_RETIF,
                'COM_ROC_CD_INDICE_IPCA' AS NR_INDICE_IPCA_ENVIO,
                'COM_ROC_CD_INDICE_' AS NR_INDICE_NEG_AB,
                'COM_ROC_STATUS_CONTRATO_1' AS TP_NEGATIVA,
                'COM_ROC_STATUS_PROPOSTA_' AS TP_STATUS,
                'COM_ROC_NR_IND_HCT_' AS NR_INDICE_HCT,
                'COM_ROC_NR_IND_DTP_' AS NR_INDICE_DTP,
                'COM_ROC_NR_IND_SAD_' AS NR_INDICE_SAD,
                'COM_ROC_CD_IND_CONTRATUAL_' AS NR_INDICE_CONTRATUAL,
                'COM_ROC_TP_REAJUSTE_' AS TP_REAJUSTE
                )
            )
    ) AHV,
    ENGINE.ACT_HI_PROCINST AHP,
    DBAMV.CONVENIO CON

WHERE
    AHP.PROC_INST_ID_ = AHV.PROC_INST_ID_
    AND CON.NM_CONVENIO = AHV.NM_OPERADORA
    AND AHP.START_TIME_ BETWEEN TO_DATE ('01/JAN/2024', 'DD/MM/YYYY')
    AND SYSDATE + 1
    AND AHP.PROC_DEF_KEY_ = 'NchMXoMztB7_Od_56ga5OE' --CODIGO DO SDK DO PROCESSO 
    AND AHP.STATE_ NOT IN ('EXTERNALLY_TERMINATED')
    AND AHP.BUSINESS_KEY_ NOT LIKE ('%TESTE%')
    --AND DENSE_RANK() OVER (PARTITION BY AHV.NM_OPERADORA ORDER BY AHV.DT_ENVPROPOSTA DESC) = 1
    
ORDER BY
    2,
    AHP.START_TIME_ DESC,
    CD_REG
    )
    WHERE NR_ORD IN (1)
)A
,(
SELECT * FROM (
SELECT
    SUBSTR (AHP.BUSINESS_KEY_, INSTR(AHP.BUSINESS_KEY_,'-',1,1)+1)AS CD_REG,
    DENSE_RANK() OVER (PARTITION BY AHV.NM_OPERADORA ORDER BY AHP.START_TIME_ DESC) AS NR_ORD,
    --PROC_DEF_KEY_,
    AHP.START_TIME_ AS DT_ABERTURA,
    AHP.END_TIME_ AS DT_FECHAMENTO,
    AHV.CD_DOC,
    AHV.CD_REGISTRANTE,
    (SELECT NM_USUARIO FROM DBASGU.USUARIOS WHERE CD_USUARIO = AHV.CD_REGISTRANTE) NM_REGISTRANTE,
    CON.CD_CONVENIO,
    AHV.NM_OPERADORA,
    TO_DATE(SUBSTR(AHV.DT_NEGOCIACAO, 1, 10),'YYYY-MM-DD') DT_ABERTURA_NEGOCIACAO,
    REPLACE(AHV.NR_INDICE_NEG_AB, '%', '') AS NR_INDICE_NEG_AB,-- INDICE REFERENCIA DA TRATATIVA DA ABERTURA DE NEGOCIACOES
    TO_DATE(SUBSTR(AHV.DT_ENVPROPOSTA, 1, 10),'YYYY-MM-DD') DT_ENVIO_PROPOSTA,
    REPLACE(AHV.NR_INDICE_IPCA_ENVIO, '%', '') AS NR_INDICE_IPCA_ENVIO, -- INDICE REFERENCIA DA TRATATIVA DE ENVIO
    TO_DATE(SUBSTR(AHV.DT_RETPROPOSTA, 1, 10),'YYYY-MM-DD') DT_RECEB_PROPOSTA,
    CASE when (AHV.TP_STATUS) = 'Sim' THEN 'Proposta Retificada' else 'Proposta Aceita' end AS TP_STATUS,
    TO_DATE(SUBSTR(AHV.DT_ENVRET_PROPOSTA, 1, 10),'YYYY-MM-DD') DT_ENVIO_RETIFICACAO,
    TO_DATE(SUBSTR(AHV.DT_RECRET_PROPOSTA, 1, 10),'YYYY-MM-DD') DT_RECEB_RETIFICACAO,
    CASE WHEN AHV.TP_NEGATIVA = 'true' THEN 'Proposta Negada' ELSE 'Proposta Aceita' END AS TP_NEGATIVA,
    TO_DATE(SUBSTR(AHV.DT_CONTRATO, 1, 10),'YYYY-MM-DD') DT_INICIO_CONTRATO,
    TO_DATE(SUBSTR(AHV.DT_VENCIMENTO, 1, 10),'YYYY-MM-DD') DT_FINAL_CONTRATO,
    TO_DATE(SUBSTR(AHV.DT_ELABORACAO, 1, 10),'YYYY-MM-DD') DT_ELAB_CONTRATO,
    REPLACE(AHV.NR_INDICE_IPCA_RETIF, '%', '') AS NR_INDICE_IPCA_RETIF,
    TO_DATE(SUBSTR(AHV.DT_ENV_CADASTRO, 1, 10),'YYYY-MM-DD') DT_ENV_CADASTRO,
    TO_DATE(SUBSTR(AHV.DT_REC_CADASTRO, 1, 10),'YYYY-MM-DD') DT_REC_CADASTRO,
    TO_DATE(SUBSTR(AHV.DT_IMPLANTACAO, 1, 10),'YYYY-MM-DD') DT_IMPLANTACAO,
    REPLACE(AHV.NR_INDICE_HCT, '%', '') AS NR_INDICE_HCT, -- ADC INDICE DE SEGURANÇA Honorários médicos || Consultas || Terapias UTILIZADO PARA MEDIDA
    REPLACE(AHV.NR_INDICE_DTP, '%', '') AS NR_INDICE_DTP, -- ADC INDICE DE SEGURANÇA Diarias || Taxas || Pacotes UTILIZADO PARA MEDIDA
    REPLACE(AHV.NR_INDICE_SAD, '%', '') AS NR_INDICE_SAD, -- ADC INDICE DE SEGURANÇA Serviços Auxiliares de Diagnósticos. UTILIZADO PARA MEDIDA
    REPLACE(AHV.NR_INDICE_CONTRATUAL, '%', '') AS NR_INDICE_CONTRATUAL,
    CASE WHEN AHV.TP_REAJUSTE = 'true' THEN 'Ativado' ELSE 'Inativado' END AS TP_REAJUSTE, --ADC PARA ATIVAÇÃO DE MEDIDA DOS VALORES DE SEGURANÇA
    AHV.DS_OBS_CADASTRO,
    AHV.DS_OBS_ENVPROPOSTA,
    AHV.DS_OBS_ENVRETPROPOSTA,
    AHV.DS_OBS_NEGOCIACAO,
    AHV.DS_OBS_RECPROPOSTA,
    AHV.DS_OBS_RECRETPROPOSTA
FROM
    (
        select
        *
        from
            (
                select
                    PROC_INST_ID_,
                    name_,
                    TEXT_,
                    '1' AS NR_ORD
                from
                    engine.act_hi_varinst
                order by
                    2
            ) eahv PIVOT (
                MAX(TEXT_) FOR name_ IN (
                'PAR_REGISTRY_ID' AS CD_DOC,
                'INSTANCE_USER' AS CD_REGISTRANTE,
                'COM_ROC_DS_OBSERVACAO_ORIENT' AS DS_OBS_CADASTRO,
                'COM_ROC_DS_OBSERVACAO_E2' AS DS_OBS_ENVPROPOSTA,
                'COM_ROC_DS_OBSERVACAO_E4' AS DS_OBS_ENVRETPROPOSTA,
                'COM_ROC_DS_OBSERVACAO_' AS DS_OBS_NEGOCIACAO,
                'COM_ROC_DS_OBSERVACAO_E3' AS DS_OBS_RECPROPOSTA,
                'COM_ROC_DS_OBSERVACAO_E5' AS DS_OBS_RECRETPROPOSTA,
                'COM_ROC_DT_CONTRATO_1' AS DT_CONTRATO,
                'COM_ROC_DT_ELABORACAO_' AS DT_ELABORACAO,
                'COM_ROC_DT_ENVIO_CONTRATUAL_1' AS DT_ENV_CADASTRO,
                'COM_ROC_DT_ENVIO_PROPOSTA_' AS DT_ENVPROPOSTA,
                'COM_ROC_DT_ENVIO_RETIFICADO_' AS DT_ENVRET_PROPOSTA,
                'COM_ROC_DT_IMPLANTACAO_1' AS DT_IMPLANTACAO,
                'COM_ROC_DT_NEGOCIACAO_' AS DT_NEGOCIACAO,
                'COM_ROC_DT_RECEB_CONTRATUAL_' AS DT_REC_CADASTRO,
                'COM_ROC_DT_RECEBIDO_RETIFICADO_' AS DT_RECRET_PROPOSTA,
                'COM_ROC_DT_RETORNO_PROPOSTA_' AS DT_RETPROPOSTA,
                'COM_ROC_DT_VENCIMENTO_1' AS DT_VENCIMENTO,
                'COM_ROC_NM_OPERADORA_1' AS NM_OPERADORA,
                'COM_ROC_CD_INDICE_IPCA2' AS NR_INDICE_IPCA_RETIF,
                'COM_ROC_CD_INDICE_IPCA' AS NR_INDICE_IPCA_ENVIO,
                'COM_ROC_CD_INDICE_' AS NR_INDICE_NEG_AB,
                'COM_ROC_STATUS_CONTRATO_1' AS TP_NEGATIVA,
                'COM_ROC_STATUS_PROPOSTA_' AS TP_STATUS,
                'COM_ROC_NR_IND_HCT_' AS NR_INDICE_HCT,
                'COM_ROC_NR_IND_DTP_' AS NR_INDICE_DTP,
                'COM_ROC_NR_IND_SAD_' AS NR_INDICE_SAD,
                'COM_ROC_CD_IND_CONTRATUAL_' AS NR_INDICE_CONTRATUAL,
                'COM_ROC_TP_REAJUSTE_' AS TP_REAJUSTE
                )
            )
    ) AHV,
    ENGINE.ACT_HI_PROCINST AHP,
    DBAMV.CONVENIO CON

WHERE
    AHP.PROC_INST_ID_ = AHV.PROC_INST_ID_
    AND CON.NM_CONVENIO = AHV.NM_OPERADORA
    AND AHP.START_TIME_ BETWEEN TO_DATE ('01/JAN/2024', 'DD/MM/YYYY')
    AND SYSDATE + 1
    AND AHP.PROC_DEF_KEY_ = 'NchMXoMztB7_Od_56ga5OE' --CODIGO DO SDK DO PROCESSO 
    AND AHP.STATE_ NOT IN ('EXTERNALLY_TERMINATED')
    AND AHP.BUSINESS_KEY_ NOT LIKE ('%TESTE%')
    --AND DENSE_RANK() OVER (PARTITION BY AHV.NM_OPERADORA ORDER BY AHV.DT_ENVPROPOSTA DESC) = 1
    
ORDER BY
    2,
    AHP.START_TIME_ DESC,
    CD_REG
    )
    WHERE NR_ORD IN (2)
)B

WHERE A.CD_CONVENIO = B.CD_CONVENIO(+)
