SELECT
    SUBSTR(AHP.BUSINESS_KEY_, 22)AS CD_REGISTRO,
    --AHP.NAME_ AS DESCRICAO_ETAPA,
    AHP.START_TIME_ AS DT_ABERTURA,
    AHP.END_TIME_ AS DT_FECHAMENTO,
    --AHP.DURATION_ AS SLA,
    --TRUNC(AHP.DURATION_ / (1000 * 60 * 60 * 60)) || ':' || LPAD(TRUNC(AHP.DURATION_ / (1000 * 60 * 60)), 2, '0') || ':' || LPAD(TRUNC(AHP.DURATION_ / (1000 * 60)), 2, '0') || ':'|| LPAD(MOD(AHP.DURATION_, (1000 * 60)), 2, '0') AS SLA,
    AHV.CD_DOC,
    AHV.CD_REGISTRANTE,
    (SELECT NM_USUARIO FROM DBASGU.USUARIOS WHERE CD_USUARIO = AHV.CD_REGISTRANTE) NM_REGISTRANTE,
    AHV.NM_OPERADORA,
    TO_DATE(SUBSTR(AHV.DT_NEGOCIACAO, 1, 10),'YYYY-MM-DD') DT_ABERTURA_NEGOCIACAO,
    TO_NUMBER (REPLACE(AHV.NR_INDICE_NEG_AB, '%', '')) AS NR_INDICE_NEG_AB,
    TO_DATE(SUBSTR(AHV.DT_ENVPROPOSTA, 1, 10),'YYYY-MM-DD') DT_ENVIO_PROPOSTA,
    TO_NUMBER (REPLACE(AHV.NR_INDICE_IPCA_ENVIO, '%', '')) AS NR_INDICE_IPCA_ENVIO,
    TO_DATE(SUBSTR(AHV.DT_RETPROPOSTA, 1, 10),'YYYY-MM-DD') DT_RECEB_PROPOSTA,
    AHV.TP_STATUS,
    TO_DATE(SUBSTR(AHV.DT_ENVRET_PROPOSTA, 1, 10),'YYYY-MM-DD') DT_ENVIO_RETIFICACAO,
    TO_DATE(SUBSTR(AHV.DT_RECRET_PROPOSTA, 1, 10),'YYYY-MM-DD') DT_RECEB_RETIFICACAO,
    AHV.TP_NEGATIVA,
    TO_DATE(SUBSTR(AHV.DT_CONTRATO, 1, 10),'YYYY-MM-DD') DT_INICIO_CONTRATO,
    TO_DATE(SUBSTR(AHV.DT_VENCIMENTO, 1, 10),'YYYY-MM-DD') DT_FINAL_CONTRATO,
    TO_DATE(SUBSTR(AHV.DT_ELABORACAO, 1, 10),'YYYY-MM-DD') DT_ELAB_CONTRATO,
    TO_NUMBER (REPLACE(AHV.NR_INDICE_IPCA_CONTRATUAL, '%', '')) AS NR_INDICE_IPCA_CONTRATUAL,
    TO_DATE(SUBSTR(AHV.DT_ENV_CADASTRO, 1, 10),'YYYY-MM-DD') DT_ENV_CADASTRO,
    TO_DATE(SUBSTR(AHV.DT_REC_CADASTRO, 1, 10),'YYYY-MM-DD') DT_REC_CADASTRO,
    TO_DATE(SUBSTR(AHV.DT_IMPLANTACAO, 1, 10),'YYYY-MM-DD') DT_IMPLANTACAO,
    AHV.DS_OBS_CADASTRO,
    AHV.DS_OBS_ENVPROPOSTA,
    AHV.DS_OBS_ENVRETPROPOSTA,
    AHV.DS_OBS_NEGOCIACAO,
    AHV.DS_OBS_RECPROPOSTA,
    AHV.DS_OBS_RECRETPROPOSTA
FROM
    (
        select
            *
        from
            (
                select
                    PROC_INST_ID_,
                    name_,
                    TEXT_
                from
                    engine.act_hi_varinst
                order by
                    2
            ) ahv PIVOT (
                MAX(TEXT_) FOR name_ IN (
                'PAR_REGISTRY_ID' AS CD_DOC,
                'INSTANCE_USER' AS CD_REGISTRANTE,
                --'BUSINESS_KEY_CASE_INSENSITIVE' AS CD_REGISTRO,
                'COM_ROC_DS_OBSERVACAO_ORIENT' AS DS_OBS_CADASTRO,
                'COM_ROC_DS_OBSERVACAO_E2' AS DS_OBS_ENVPROPOSTA,
                'COM_ROC_DS_OBSERVACAO_E4' AS DS_OBS_ENVRETPROPOSTA,
                'COM_ROC_DS_OBSERVACAO_' AS DS_OBS_NEGOCIACAO,
                'COM_ROC_DS_OBSERVACAO_E3' AS DS_OBS_RECPROPOSTA,
                'COM_ROC_DS_OBSERVACAO_E5' AS DS_OBS_RECRETPROPOSTA,
                'COM_ROC_DT_CONTRATO_1' AS DT_CONTRATO,
                'COM_ROC_DT_ELABORACAO_' AS DT_ELABORACAO,
                'COM_ROC_DT_ENVIO_CONTRATUAL_1' AS DT_ENV_CADASTRO,
                'COM_ROC_DT_ENVIO_PROPOSTA_' AS DT_ENVPROPOSTA,
                'COM_ROC_DT_ENVIO_RETIFICADO_' AS DT_ENVRET_PROPOSTA,
                'COM_ROC_DT_IMPLANTACAO_1' AS DT_IMPLANTACAO,
                'COM_ROC_DT_NEGOCIACAO_' AS DT_NEGOCIACAO,
                'COM_ROC_DT_RECEB_CONTRATUAL_' AS DT_REC_CADASTRO,
                'COM_ROC_DT_RECEBIDO_RETIFICADO_' AS DT_RECRET_PROPOSTA,
                'COM_ROC_DT_RETORNO_PROPOSTA_' AS DT_RETPROPOSTA,
                'COM_ROC_DT_VENCIMENTO_1' AS DT_VENCIMENTO,
                'COM_ROC_NM_OPERADORA_1' AS NM_OPERADORA,
                'COM_ROC_CD_INDICE_IPCA2' AS NR_INDICE_IPCA_CONTRATUAL,
                'COM_ROC_CD_INDICE_IPCA' AS NR_INDICE_IPCA_ENVIO,
                'COM_ROC_CD_INDICE_' AS NR_INDICE_NEG_AB,
                'COM_ROC_STATUS_CONTRATO_1' AS TP_NEGATIVA,
                'COM_ROC_STATUS_PROPOSTA_' AS TP_STATUS
                )
            )
    ) AHV,
    ENGINE.ACT_HI_PROCINST AHP

WHERE
    AHP.PROC_INST_ID_ = AHV.PROC_INST_ID_
    AND AHP.START_TIME_ BETWEEN TO_DATE ('01/01/2024', 'DD/MM/YYYY')
    AND SYSDATE + 1
    AND UPPER (AHP.BUSINESS_KEY_) LIKE 'CONTROLE DE ADITIVOS-%'
    AND AHP.STATE_ NOT IN ('EXTERNALLY_TERMINATED')
    
ORDER BY
    AHP.START_TIME_ DESC,
    CD_REGISTRO