SELECT 
NAME_
,TO_CHAR (TIME_,'DD/MM/YYYY HH24:MI:ss') AS DATA
,CASE WHEN VAR_TYPE_ IS NULL THEN 'Aguardando' ELSE 'Finalizado' END STATUS
    ,CASE  
  WHEN EXTRACT (month FROM TIME_) = 1 THEN '01.JANEIRO' 
  WHEN  EXTRACT (month FROM TIME_)  = 2 THEN '02.FEVEREIRO' 
  WHEN  EXTRACT (month FROM TIME_)  = 3 THEN '03.MAR?O' 
  WHEN  EXTRACT (month FROM TIME_)  = 4 THEN '04.ABRIL' 
  WHEN  EXTRACT (month FROM TIME_)  = 5 THEN '05.MAIO' 
  WHEN  EXTRACT (month FROM TIME_)  = 6 THEN '06.JUNHO' 
  WHEN  EXTRACT (month FROM TIME_)  = 7 THEN '07.JULHO' 
  WHEN  EXTRACT (month FROM TIME_)  = 8 THEN '08.AGOSTO' 
  WHEN  EXTRACT (month FROM TIME_)  = 9 THEN '09.SETEMBRO' 
  WHEN  EXTRACT (month FROM TIME_)  = 10 THEN '10.OUTUBRO' 
  WHEN  EXTRACT (month FROM TIME_)  = 11 THEN '11.NOVEMBRO' 
  ELSE '12.DEZEMBRO' 
END MESES
,TO_CHAR (TIME_,'HH24:MI') AS HORA
,TEXT_ CD_PRESCRICAO
, SEQUENCE_COUNTER_  AS ORDEM
FROM ENGINE.ACT_HI_DETAIL
WHERE NAME_ = 'RHP2'
--AND VAR_TYPE_ = 'string'
AND TEXT_ = 8457782 
--8130221
--8383378 
--8392176
--8385627
ORDER BY 4, 7 , 5
;
SELECT * FROM ENGINE.ACT_HI_DETAIL
WHERE NAME_ = 'RHP2'
AND TEXT_ = 8392176 
--AND VAR_TYPE_ = 'string'
order by time_