-- EXTRAIR INFORMAÇÃO DA VARIAVEL DA ATIVIDADE NO FLOW
SELECT 
     NAME_
    ,VAR_TYPE_
    ,TO_CHAR (CREATE_TIME_,'YYYY/MM/DD') AS DATA
    ,CASE  
  WHEN EXTRACT (month FROM CREATE_TIME_) = 1 THEN '01.JANEIRO' 
  WHEN  EXTRACT (month FROM CREATE_TIME_)  = 2 THEN '02.FEVEREIRO' 
  WHEN  EXTRACT (month FROM CREATE_TIME_)  = 3 THEN '03.MAR�O' 
  WHEN  EXTRACT (month FROM CREATE_TIME_)  = 4 THEN '04.ABRIL' 
  WHEN  EXTRACT (month FROM CREATE_TIME_)  = 5 THEN '05.MAIO' 
  WHEN  EXTRACT (month FROM CREATE_TIME_)  = 6 THEN '06.JUNHO' 
  WHEN  EXTRACT (month FROM CREATE_TIME_)  = 7 THEN '07.JULHO' 
  WHEN  EXTRACT (month FROM CREATE_TIME_)  = 8 THEN '08.AGOSTO' 
  WHEN  EXTRACT (month FROM CREATE_TIME_)  = 9 THEN '09.SETEMBRO' 
  WHEN  EXTRACT (month FROM CREATE_TIME_)  = 10 THEN '10.OUTUBRO' 
  WHEN  EXTRACT (month FROM CREATE_TIME_)  = 11 THEN '11.NOVEMBRO' 
  ELSE '12.DEZEMBRO' 
END MESES
    ,TO_CHAR (CREATE_TIME_,'HH24:MI') AS HORA
    ,TEXT_
    ,STATE_
   ,CASE 
   WHEN ROW_NUMBER () OVER (PARTITION BY (TEXT_) ORDER BY CREATE_TIME_ ) = 1 THEN 'TELA 01'
   WHEN ROW_NUMBER () OVER (PARTITION BY (TEXT_) ORDER BY CREATE_TIME_ ) = 2 THEN 'TELA 02'
   ELSE 'POC' END SUB_RANKING

FROM ENGINE.ACT_HI_VARINST
WHERE NAME_ IN ('RHP2')
AND CREATE_TIME_ BETWEEN TO_DATE ('01012023','DD/MM/YYYY') AND SYSDATE+1
ORDER BY 3 DESC, 4 DESC
;
