--comparativo de competencia por especialidade e prestadores
SELECT
--P.CD_PRE_MED
--DISTINCT P.CD_PRESTADOR
PR.NM_PRESTADOR
--,P.DT_PRE_MED
--,P.CD_SETOR
--,PR.CD_TIP_PRESTA
--,PR.TP_SITUACAO
,EM.CD_ESPECIALID
,ES.DS_ESPECIALID
--,TO_CHAR (P.DT_PRE_MED,'MM') AS MES
--,TO_CHAR (P.DT_PRE_MED,'YYYY') AS ANO
,Count (P.CD_PRESTADOR) AS QNTD_PRESTADOR
FROM PRESTADOR PR

LEFT JOIN PRE_MED P ON P.CD_PRESTADOR = PR.CD_PRESTADOR
LEFT JOIN ESP_MED EM ON EM.CD_PRESTADOR = PR.CD_PRESTADOR
LEFT JOIN ESPECIALID ES ON ES.CD_ESPECIALID = EM.CD_ESPECIALID

      WHERE  P.DT_PRE_MED between To_Date ('01012022','dd/mm/yyyy') AND To_Date ('17112022','dd/mm/yyyy')
          AND PR.CD_TIP_PRESTA IN (8)
          AND PR.TP_SITUACAO = 'A'
      GROUP BY
              P.CD_PRESTADOR,PR.NM_PRESTADOR,EM.CD_ESPECIALID,ES.DS_ESPECIALID,P.DT_PRE_MED

     ORDER BY
             CD_ESPECIALID
;






--buscar colunas para o select
SELECT * FROM PRE_MED
WHERE CD_PRESTADOR =  '6933'
;
SELECT * FROM dbamv.ESPECIALID
;
SELECT*FROM COLUNAS
WHERE COLUNA LIKE '%ESPECIAL%'
;


SELECT
DISTINCT EM.CD_ESPECIALID
,ES.DS_ESPECIALID
,Count (P.CD_PRESTADOR) AS PRESTADOR FROM PRE_MED P


LEFT JOIN PRESTADOR PR ON PR.CD_PRESTADOR = P.CD_PRESTADOR
LEFT JOIN ESP_MED EM ON EM.CD_PRESTADOR = PR.CD_PRESTADOR
LEFT JOIN ESPECIALID ES ON ES.CD_ESPECIALID = EM.CD_ESPECIALID


WHERE P.DT_PRE_MED between To_Date ('01012022','dd/mm/yyyy') AND To_Date ('17112022','dd/mm/yyyy')

      GROUP BY
              P.CD_PRESTADOR,PR.NM_PRESTADOR,EM.CD_ESPECIALID,ES.DS_ESPECIALID,P.DT_PRE_MED

      ORDER BY
             CD_ESPECIALID
;