SELECT ATENDIMENTO,PACIENTE,USUARIO,PRESTADOR,CID_PRINC, CID_SECUN,DT_AVALIA,AVALIA_PONTUA, DECODE (SN_AVALIA_NEG,'true','NEGADO','false','APROVADO') AS SN_AVALIA_NEG, DECODE(SN_AVALIA_POS,'false','NEGADO','true','APROVADO')AS SN_AVALIA_POS,TX_ENDERECO FROM (
    SELECT 
      EC.DS_CAMPO
      ,ERC.CD_REGISTRO
      ,DBMS_LOB.SUBSTR(ERC.LO_VALOR,4000,1) DADO 
    FROM DBAMV.PW_DOCUMENTO_CLINICO PDC,
      DBAMV.PW_EDITOR_CLINICO PEC,
      DBAMV.EDITOR_REGISTRO_CAMPO ERC,
      DBAMV.EDITOR_CAMPO EC
      
    WHERE PDC.CD_DOCUMENTO_CLINICO = PEC.CD_DOCUMENTO_ClINICO
    AND PEC.CD_EDITOR_REGISTRO     = ERC.CD_REGISTRO
    AND EC.CD_CAMPO                = ERC.CD_CAMPO
      --FILTROS
    AND PEC.CD_DOCUMENTO = 1377
) PIVOT (MAX(DADO) FOR DS_CAMPO IN(
        'BT_CALCULAR_PONTUACAO_FINAL' AS CALC_FINAL,
        'BT_CALCULAR_PONTUACAO_KATZ' AS CALC_KATZ,
        'Chave do Documento' AS CHAVDOC,
        'CID 10 - Principal' AS CID_PRINC,
        'CID 10 - Segundário' AS CID_SECUN,
        'CK_TAB_AVAL_PLJ_ATEN_DOM' AS AVALIA_AT,
        'Código da Empresa' AS EMPRESA,
        'Código do Atendimento' AS ATENDIMENTO,
        'Código do Documento' AS DOCUMENTO,
        'Código do Item na Prescrição' AS ITEM_PRESC,
        'Código do Paciente' AS PACIENTE,
        'Código do Usuário' AS USUARIO,
        'Data de Registro' AS DT_REGISTRO,
        'DT_TAB_AVAL_PLJ_ATEN_DOM' AS DT_AVALIA,
        'Identificador' AS IDENTIFICADOR,
        'NOME DO USUARIO CONSELHO E CODIGO ' AS PRESTADOR,
        'NR_PONTUACAO_TAB_AVAL_PLJ_ATEN_DOM' AS AVALIA_PONTUA,
        'RB_NAO_TAB_AVAL_PLJ_ATEN_DOM' AS SN_AVALIA_NEG,
        'RB_SIM_TAB_AVAL_PLJ_ATEN_DOM' AS SN_AVALIA_POS,
        'Registro de Documento' AS CD_DOCUMENTO,
        'Registro do editor' AS CD_EDITOR,
        'Sistema responsável' AS SISTEMA,
        'TX_ENDERECO_PAC_TERMO' AS TX_ENDERECO,
        'Último Resultado' AS ULTIMO_RESULTADO
))
