SELECT  * FROM DBAPORTAL.REGISTRO_OCORRENCIA
--WHERE CD_REGISTRO_OCORRENCIA = 21101
WHERE CD_METODO_DETECCAO_OCORRENCIA = 35 --DRG
AND CD_OCORRENCIA = 449  --Classificação pelo Gerenciamento de Risco
;

