SELECT BASE.*, ROUND(((NVL(MAX(DH_REALIZADO),SYSDATE) - MAX(DT_PEDIDO_RX))*24*60),2) AS TEMPO_09
FROM(
  SELECT 
  S.NM_SET_EXA TIPO_EXA,
  P.CD_PED_RX,
  A.CD_ATENDIMENTO,
  MIN(DBAMV.FNC_MV_RECUPERA_DATA_HORA(P.DT_PEDIDO, P.HR_PEDIDO))                             AS DT_PEDIDO_RX,
  MIN(LAU.DT_STUDY) AS DH_REALIZADO,
  (RANK() OVER (PARTITION BY A.CD_ATENDIMENTO ORDER BY S.NM_SET_EXA DESC, P.HR_PEDIDO DESC)) AS NR_ORD

  FROM DBAMV.PED_RX P,
  DBAMV.ATENDIME A,
  DBAMV.SET_EXA S,
  IDCE.RS_LAU_PEDIDO_EXAME PED,
  IDCE.RS_LAU_EXAME_PEDIDO LAU,
  IDCE.RS_EXA_EXAME_UNIDADE EXAME

  WHERE A.CD_ATENDIMENTO     = P.CD_ATENDIMENTO
  AND P.CD_SET_EXA           = S.CD_SET_EXA
  AND ped.cd_pedido_his      = P.CD_PED_RX
  AND ped.CD_ATENDIMENTO_HIS = P.CD_ATENDIMENTO
  AND ped.ID_PEDIDO_EXAME    = lau.ID_PEDIDO_EXAME
  AND exame.ID_EXAME_UNIDADE = lau.ID_EXAME_UNIDADE

  --AND LAU.DT_STUDY          IS NULL --NÃO TEVE IMAGEM OU LAUDO
  AND A.DT_ATENDIMENTO >= TRUNC(SYSDATE)-1
  AND A.DT_ATENDIMENTO < TRUNC(SYSDATE)+INTERVAL '24' HOUR
  --AND A.DT_ALTA_MEDICA      IS NULL
  AND A.TP_ATENDIMENTO       = 'U'
  AND P.CD_SET_EXA          IN (12,13,15,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,36,38,39,40,41,42,43,77) --SETORES DE EXAMES DO REAL IMAGEM

  GROUP BY 
  A.CD_ATENDIMENTO,
  S.NM_SET_EXA,
  P.HR_PEDIDO,
  P.CD_PED_RX,
  lau.DT_STUDY

  ORDER BY CD_ATENDIMENTO
)BASE
WHERE NR_ORD = 1

GROUP BY 
TIPO_EXA, CD_PED_RX, CD_ATENDIMENTO, DT_PEDIDO_RX, DH_REALIZADO, NR_ORD