SELECT *--distinct cod, DOM_PRIM 
FROM EDITOR_CUSTOM.CLAS_FARM_RHP
WHERE COD = 6
order by 1
;
--NECESSARIO DELETAR DUPLICATA CRIADA DO ITEM
DELETE FROM EDITOR_CUSTOM.CLAS_FARM_RHP
WHERE SUB_COD = '16.9'
AND COD = 16
;
--IDENTIFICADO AJUSTE DE COD EM DUPLICIDADE
UPDATE EDITOR_CUSTOM.CLAS_FARM_RHP
SET SUB_COD =  '16.9'
WHERE SUB_COD = '16,9'
AND COD = 16
;
--AJUSTES ORTOGRÁFICOS
UPDATE EDITOR_CUSTOM.CLAS_FARM_RHP
SET DOM_PRIM = 'CONCILIAÇÃO MEDICAMENTOSA'
WHERE COD = 8
;
INSERT ALL
INTO EDITOR_CUSTOM.CLAS_FARM_RHP (COD, DOM_PRIM, SUB_COD, DESCR_PRTA, CLAS_INTERV)
VALUES (10,'INEFETIVIDADE TERAPEUTICA',10.2,'PACIENTE SEM RESPOSTA CLÍNICA AO MEDICAMENTO','E')
INTO EDITOR_CUSTOM.CLAS_FARM_RHP (COD, DOM_PRIM, SUB_COD, DESCR_PRTA, CLAS_INTERV)
VALUES (8,'DILUICAO',8.6,'AJUSTE DO DILUENTE POR CONDIÇÕES CLÍNICAS','S')
SELECT 1 FROM DUAL;

