SELECT * FROM ALL_TAB_COLUMNS --ITPROTOCOLO_DOC
WHERE TABLE_NAME LIKE '%PROTOCO%'
;
-- SELECT DO GRID
SELECT 
IPD.CD_PROTOCOLO_DOC AS PROTOCOLO
,TO_DATE (IPD.DT_RECEBIMENTO,'DD/MM/YYYY') "DATA RECEBIMENTO"
,CASE WHEN (TO_DATE (IPD.DT_RECEBIMENTO,'DD/MM/YYYY')) IS NOT NULL THEN 'Recebido' ELSE 'Aberto' END AS STATUS
,US.NM_USUARIO "USUARIO RECEBIMENTO"
,COUNT (IPD.CD_PROTOCOLO_DOC) TOTAL

FROM DBAMV.IT_PROTOCOLO_DOC IPD, DBASGU.USUARIOS US

WHERE IPD.NM_USUARIO_RECEBIMENTO = US.CD_USUARIO
AND IPD.CD_PROTOCOLO_DOC IN (921,113,119)
GROUP BY IPD.CD_PROTOCOLO_DOC,IPD.DT_RECEBIMENTO, IPD.DT_RECEBIMENTO, US.NM_USUARIO

ORDER BY 5 DESC, 2
;
-- CONTADOR DE CONTAS POR PROTOCOLOS
SELECT SUM(TOTAL) "TOTAL CONTAS" FROM ( 
SELECT 
IPD.CD_PROTOCOLO_DOC AS PROTOCOLO
,TO_DATE (IPD.DT_RECEBIMENTO,'DD/MM/YYYY') "DATA RECEBIMENTO"
,CASE WHEN (TO_DATE (IPD.DT_RECEBIMENTO,'DD/MM/YYYY')) IS NOT NULL THEN 'Recebido' ELSE 'Aberto' END AS STATUS
,US.NM_USUARIO "USUARIO RECEBIMENTO"
,COUNT (IPD.CD_PROTOCOLO_DOC) TOTAL

FROM DBAMV.IT_PROTOCOLO_DOC IPD, DBASGU.USUARIOS US

WHERE IPD.NM_USUARIO_RECEBIMENTO = US.CD_USUARIO
AND IPD.CD_PROTOCOLO_DOC IN (921,113,119)
GROUP BY IPD.CD_PROTOCOLO_DOC,IPD.DT_RECEBIMENTO, IPD.DT_RECEBIMENTO, US.NM_USUARIO

ORDER BY 5 DESC, 2
)
ORDER BY 1 DESC
;
--CONTADOR TOTAL DE PROTOCOLOS SINALIZADOS
SELECT COUNT(PROTOCOLO) "TOTAL PROTOCOLOS" FROM ( 
SELECT 
IPD.CD_PROTOCOLO_DOC AS PROTOCOLO
,TO_DATE (IPD.DT_RECEBIMENTO,'DD/MM/YYYY') "DATA RECEBIMENTO"
,CASE WHEN (TO_DATE (IPD.DT_RECEBIMENTO,'DD/MM/YYYY')) IS NOT NULL THEN 'Recebido' ELSE 'Aberto' END AS STATUS
,US.NM_USUARIO "USUARIO RECEBIMENTO"
,COUNT (IPD.CD_PROTOCOLO_DOC) TOTAL

FROM DBAMV.IT_PROTOCOLO_DOC IPD, DBASGU.USUARIOS US

WHERE IPD.NM_USUARIO_RECEBIMENTO = US.CD_USUARIO
AND IPD.CD_PROTOCOLO_DOC IN (921,113,119)
GROUP BY IPD.CD_PROTOCOLO_DOC,IPD.DT_RECEBIMENTO, IPD.DT_RECEBIMENTO, US.NM_USUARIO

ORDER BY 5 DESC, 2
)
ORDER BY 1 DESC