---[RLM]_POC2_BUSCA_ATIVA_REDE_HOSP---
SELECT 
DECODE (ATUA_RHP,'true','Real Hospital Português',null,'Sem utilização') RHP
,DECODE (ATUA_STA_JOANA, 'true','Hospital Santa Joana',null, 'Sem utilização') JOANA
,DECODE (ATUA_ESPERANCA,'true','Hospital Esperança',null, 'Sem utilização') ESPERANCA
,DECODE (ATUA_MEMORIAL_SJ,'true','Hospital Memorial São José',null,'Sem utilização') MEMORIAL
,DECODE (ATUA_SAO_MARCOS,'true','Hospital São Marcos',null,'Sem utilização') SAO_MARCOS
,DECODE (ATUA_JAYME,'true','Hospital Jayme da Fonte',null,'Sem utilização') JAYME
,CASE WHEN ATUA_OUTRO_HOSP <> 'null' THEN ATUA_OUTRO_HOSP ELSE 'Sem utilização' END OUTROS
    FROM  EDITOR_CUSTOM.HIST_VISITA_MED

    WHERE CRM IN ()
    AND NM_MED IN ()
    AND DT_VISITA IN ()
    ;

SELECT 
'REAL HOSPITAL PORTUGUÊS' ||' - '|| DECODE (ATUA_RHP,'true','Utiliza',null,'Sem utilização') RHP
,'HOSPITAL SANTA JOANA' ||' - '|| DECODE (ATUA_STA_JOANA, 'true','Utiliza',null, 'Sem utilização') SANTA_JOANA
,'HOSPITAL ESPERANÇA' ||' - '|| DECODE (ATUA_ESPERANCA,'true','Utiliza',null, 'Sem utilização') ESPERANCA
,'HOSPITAL MEMORIAL SÃO JOSÉ' ||' - '|| DECODE (ATUA_MEMORIAL_SJ,'true','Utiliza',null,'Sem utilização') MEMORIAL_SJ
,'HOSPITAL SÃO MARCOS' ||' - '|| DECODE (ATUA_SAO_MARCOS,'true','Utiliza',null,'Sem utilização') SAO_MARCOS
,'HOSPITAL JAYME DA FONTE' ||' - '|| DECODE (ATUA_JAYME,'true','Utiliza',null,'Sem utilização') JAYME_FONTE
,'OUTRAS REDES HOSPITALARES' ||' - '|| CASE WHEN ATUA_OUTRO_HOSP <> 'null' THEN ATUA_OUTRO_HOSP ELSE 'Sem utilização' END OUTROS
    FROM  EDITOR_CUSTOM.HIST_VISITA_MED

SELECT 
  'REAL HOSPITAL PORTUGUÊS' AS "REDES HOSPITALARES",
  DECODE (ATUA_RHP, 'true', 'Utiliza', null, 'Sem utilização') AS USO
FROM EDITOR_CUSTOM.HIST_VISITA_MED
WHERE CRM = '&<2214:CONSULTACRM494___V3>'
AND DATA_VISITA = '&<2235:DATAVISITA548___V6>'
UNION ALL
SELECT 
  'HOSPITAL SANTA JOANA' AS "REDES HOSPITALARES",
  DECODE (ATUA_STA_JOANA, 'true', 'Utiliza', null, 'Sem utilização') AS USO
FROM EDITOR_CUSTOM.HIST_VISITA_MED
WHERE CRM = '&<2214:CONSULTACRM494___V3>'
AND DATA_VISITA = '&<2235:DATAVISITA548___V6>'
UNION ALL
SELECT 
  'HOSPITAL ESPERANÇA' AS "REDES HOSPITALARES",
  DECODE (ATUA_ESPERANCA, 'true', 'Utiliza', null, 'Sem utilização') AS USO
FROM EDITOR_CUSTOM.HIST_VISITA_MED
WHERE CRM = '&<2214:CONSULTACRM494___V3>'
AND DATA_VISITA = '&<2235:DATAVISITA548___V6>'
UNION ALL
SELECT 
  'HOSPITAL MEMORIAL SÃO JOSÉ' AS "REDES HOSPITALARES",
  DECODE (ATUA_MEMORIAL_SJ, 'true', 'Utiliza', null, 'Sem utilização') AS USO
FROM EDITOR_CUSTOM.HIST_VISITA_MED
WHERE CRM = '&<2214:CONSULTACRM494___V3>'
AND DATA_VISITA = '&<2235:DATAVISITA548___V6>'
UNION ALL
SELECT 
  'HOSPITAL SÃO MARCOS' AS "REDES HOSPITALARES",
  DECODE (ATUA_SAO_MARCOS, 'true', 'Utiliza', null, 'Sem utilização') AS USO
FROM EDITOR_CUSTOM.HIST_VISITA_MED
WHERE CRM = '&<2214:CONSULTACRM494___V3>'
AND DATA_VISITA = '&<2235:DATAVISITA548___V6>'
UNION ALL
SELECT 
  'HOSPITAL JAYME DA FONTE' AS "REDES HOSPITALARES",
  DECODE (ATUA_JAYME, 'true', 'Utiliza', null, 'Sem utilização') AS USO
FROM EDITOR_CUSTOM.HIST_VISITA_MED
WHERE CRM = '&<2214:CONSULTACRM494___V3>'
AND DATA_VISITA = '&<2235:DATAVISITA548___V6>'
UNION ALL
SELECT 
  'OUTRAS REDES HOSPITALARES' AS "REDES HOSPITALARES",
  CASE WHEN ATUA_OUTRO_HOSP <> 'null' THEN ATUA_OUTRO_HOSP ELSE 'Sem utilização' END AS USO
FROM EDITOR_CUSTOM.HIST_VISITA_MED
WHERE CRM = '&<2214:CONSULTACRM494___V3>'
AND DATA_VISITA = '&<2235:DATAVISITA548___V6>'
;

---[RLM]_POC2_BUSCA_ATIVA_CLASSIFICAÇÃO_MED---
SELECT 
    SETOR_AGE_CIR
    ,SETOR_AUT_CIR
    ,SETOR_BLOCO_CIR
    ,SETOR_CAD_MEDICO
    ,SETOR_COMERCIAL
    ,SETOR_FATUR
    ,SETOR_NUTRI
    ,SETOR_TRANSP
    ,SETOR_REPASSE_HONO
    ,SETOR_ORCAMENTO
    ,SETOR_RELAC_MEDICO
    ,SETOR_TECNOLOGIA
FROM EDITOR_CUSTOM.HIST_VISITA_MED

    WHERE CRM = 16492
    AND DATA_VISITA = '07/06/2023'
    AND MEDICO = 'ANA BEATRIZ MEDEIROS LINS DE ALBUQUERQUE'

---[RLM]_POC2_BUSCA_ATIVA_COMO_AVALIA---
SELECT 
    AVALIA_RHP
FROM EDITOR_CUSTOM.HIST_VISITA_MED

---[RLM]_POC2_BUSCA_ATIVA_CONSIDERAÇÕES---
SELECT CONSIDERACOES
FROM EDITOR_CUSTOM.HIST_VISITA_MED

---[RLM]_POC2_BUSCA_ATIVA_GERAÇÃO_DEMANDA---
SELECT GEROU_DEMANDA
FROM EDITOR_CUSTOM.HIST_VISITA_MED

---[RLM]_POC2_BUSCA_ATIVA_SETORES---
SELECT 
DS_RELACIONAMENTO
,DS_CADASTRO
,DS_COMERCIAL
,DS_REPASSE
,DS_REGULACAO
,DS_INT_MERC
,DS_BLOCO_CIR
,DS_TECNOLOGIA
FROM EDITOR_CUSTOM.HIST_VISITA_MED

---[RLM]_POC2_BUSCA_ATIVA_REVISITAÇÃO--
SELECT REVISITA
FROM EDITOR_CUSTOM.HIST_VISITA_MED 

