SELECT
CD_CRM
,NM_MED
,DT_VISITA
,to_char (DT_VISITA, 'MM/YYYY') MES_ANO
,TP_ESPMED
,SN_ATUACAO
,CASE WHEN TP_HOSP_RHP ='true' THEN 'PORTUG�S' ELSE 'ND' END AS TP_HOSP_RHP
,CASE WHEN TP_HOSP_MEMORIAL ='true' THEN 'MEMORIAL' ELSE 'ND' END AS TP_HOSP_MEMORIAL
,CASE WHEN TP_HOSP_ESPERANCA ='true' THEN 'ESPERAN�A' ELSE 'ND' END AS TP_HOSP_ESPERANCA
,CASE WHEN TP_HOSP_STJOANA ='true' THEN 'SANTA JOANA' ELSE 'ND' END AS TP_HOSP_STJOANA
,CASE WHEN TP_HOSP_SMARCOS ='true' THEN 'S�O MARCOS' ELSE 'ND' END AS TP_HOSP_SMARCOS
,CASE WHEN TP_HOSP_JAIME_FONTE ='true' THEN 'JAIME FONTE' ELSE 'ND' END AS TP_HOSP_JAIME_FONTE
,CASE WHEN TP_HOSP_OUTROS ='true' THEN 'SIM' ELSE 'ND' END AS TP_HOSP_OUTROS
,DS_HOSP_OUTROS
,TP_AVALIAR_RHP
,TP_CLASS_MD_VISITA
,CASE WHEN TP_SETOR_REL_MED = 'true' THEN 'Relacionamento M�dico' ELSE 'ND' END AS TP_SETOR_REL_MED
,CASE WHEN TP_SETOR_ORCAMENTO = 'true' THEN 'Or�amento' ELSE 'ND' END AS TP_SETOR_ORCAMENTO
,CASE WHEN TP_SETOR_REPASSE = 'true' THEN 'Repasse de Honor�rios' ELSE 'ND' END AS TP_SETOR_REPASSE
,CASE WHEN TP_SETOR_TRANSP = 'true' THEN 'Transporte' ELSE 'ND' END AS TP_SETOR_TRANSP
,CASE WHEN TP_SETOR_NUTRICAO = 'true' THEN 'Nutri��o' ELSE 'ND' END AS TP_SETOR_NUTRICAO
,CASE WHEN TP_SETOR_FATURANENTO = 'true' THEN 'Admiss�o' ELSE 'ND' END AS TP_SETOR_FATURANENTO
,CASE WHEN TP_SETOR_COMERCIAL = 'true' THEN 'Comercial' ELSE 'ND' END AS TP_SETOR_COMERCIAL
,CASE WHEN TP_SETOR_CAD_MED = 'true' THEN 'Cadastro M�dico' ELSE 'ND' END AS TP_SETOR_CAD_MED
,CASE WHEN TP_SETOR_BLOCO_CIR = 'true' THEN 'Bloco Cir�rgico' ELSE 'ND' END AS TP_SETOR_BLOCO_CIR
,CASE WHEN TP_SETOR_AUTORIZACAO = 'true' THEN 'Autoriza��o Cir�rgica' ELSE 'ND' END AS TP_SETOR_AUTORIZACAO
,CASE WHEN TP_SETOR_AGENDAMENTO = 'true' THEN 'Agendamento Cir�rgico' ELSE 'ND' END AS TP_SETOR_AGENDAMENTO
,DS_CONSIDERACOES
,TP_DEMANDA_AREA
,CASE WHEN TP_ST_RELACIONAMENTO = 'true' THEN 'Sim' ELSE 'ND' END AS TP_ST_RELACIONAMENTO
,DS_ST_RELACIONAMENTO
,CASE WHEN TP_ST_CADASTRO = 'true' THEN 'Sim' ELSE 'ND' END AS TP_ST_CADASTRO
,DS_ST_CADASTRO
,CASE WHEN TP_ST_COMERCIAL = 'true' THEN 'Sim' ELSE 'ND' END AS TP_ST_COMERCIAL
,DS_ST_COMERCIAL
,CASE WHEN TP_ST_REPMED = 'true' THEN 'Sim' ELSE 'ND' END AS TP_ST_REPMED
,DS_ST_REPMED
,CASE WHEN TP_ST_REGULACAO = 'true' THEN 'Sim' ELSE 'ND' END AS TP_ST_REGULACAO
,DS_ST_REGULACAO
,CASE WHEN TP_ST_INTEL_MERC = 'true' THEN 'Sim' ELSE 'ND' END AS TP_ST_INTEL_MERC
,DS_ST_INTEL_MERC
,TP_REVISITA
,DS_OBS_REVISITA
,DT_REVISITA
FROM (
    /*CAMADA BORDA_INTERNA*/
    SELECT
        CD_REGISTRO
        ,LISTAGG(CD_CRM, ';') WITHIN GROUP (ORDER BY CD_CRM) CD_CRM
        ,LISTAGG(NM_MED, ';') WITHIN GROUP (ORDER BY NM_MED) NM_MED
        ,LISTAGG(DT_VISITA, ';') WITHIN GROUP (ORDER BY DT_VISITA) DT_VISITA
        ,LISTAGG(TP_ESPMED, ';') WITHIN GROUP (ORDER BY TP_ESPMED) TP_ESPMED
        ,LISTAGG(SN_ATUACAO, ';') WITHIN GROUP (ORDER BY SN_ATUACAO) SN_ATUACAO
        ,LISTAGG(TP_HOSP_RHP, ';') WITHIN GROUP (ORDER BY TP_HOSP_RHP) TP_HOSP_RHP
        ,LISTAGG(TP_HOSP_MEMORIAL, '; ') WITHIN GROUP (ORDER BY TP_HOSP_MEMORIAL) TP_HOSP_MEMORIAL
        ,LISTAGG(TP_HOSP_ESPERANCA, '; ') WITHIN GROUP (ORDER BY TP_HOSP_ESPERANCA) TP_HOSP_ESPERANCA
        ,LISTAGG(TP_HOSP_STJOANA, '; ') WITHIN GROUP (ORDER BY TP_HOSP_STJOANA) TP_HOSP_STJOANA
        ,LISTAGG(TP_HOSP_SMARCOS, '; ') WITHIN GROUP (ORDER BY TP_HOSP_SMARCOS) TP_HOSP_SMARCOS
        ,LISTAGG(TP_HOSP_JAIME_FONTE, '; ') WITHIN GROUP (ORDER BY TP_HOSP_JAIME_FONTE) TP_HOSP_JAIME_FONTE
        ,LISTAGG(TP_HOSP_OUTROS, '; ') WITHIN GROUP (ORDER BY TP_HOSP_OUTROS) TP_HOSP_OUTROS
        ,LISTAGG(DS_HOSP_OUTROS, '; ') WITHIN GROUP (ORDER BY DS_HOSP_OUTROS) DS_HOSP_OUTROS
        ,LISTAGG(TP_AVALIAR_RHP, '; ') WITHIN GROUP (ORDER BY TP_AVALIAR_RHP) TP_AVALIAR_RHP
        ,LISTAGG(TP_CLASS_MD_VISITA, '; ') WITHIN GROUP (ORDER BY TP_CLASS_MD_VISITA) TP_CLASS_MD_VISITA
        ,LISTAGG(TP_SETOR_REL_MED, '; ') WITHIN GROUP (ORDER BY TP_SETOR_REL_MED) TP_SETOR_REL_MED
        ,LISTAGG(TP_SETOR_ORCAMENTO, '; ') WITHIN GROUP (ORDER BY TP_SETOR_ORCAMENTO) TP_SETOR_ORCAMENTO
        ,LISTAGG(TP_SETOR_REPASSE, '; ') WITHIN GROUP (ORDER BY TP_SETOR_REPASSE) TP_SETOR_REPASSE
        ,LISTAGG(TP_SETOR_TRANSP, '; ') WITHIN GROUP (ORDER BY TP_SETOR_TRANSP) TP_SETOR_TRANSP
        ,LISTAGG(TP_SETOR_NUTRICAO, '; ') WITHIN GROUP (ORDER BY TP_SETOR_NUTRICAO) TP_SETOR_NUTRICAO   
        ,LISTAGG(TP_SETOR_FATURANENTO, '; ') WITHIN GROUP (ORDER BY TP_SETOR_FATURANENTO) TP_SETOR_FATURANENTO
        ,LISTAGG(TP_SETOR_COMERCIAL, '; ') WITHIN GROUP (ORDER BY TP_SETOR_COMERCIAL) TP_SETOR_COMERCIAL
        ,LISTAGG(TP_SETOR_CAD_MED, '; ') WITHIN GROUP (ORDER BY TP_SETOR_CAD_MED) TP_SETOR_CAD_MED
        ,LISTAGG(TP_SETOR_BLOCO_CIR, '; ') WITHIN GROUP (ORDER BY TP_SETOR_BLOCO_CIR) TP_SETOR_BLOCO_CIR
        ,LISTAGG(TP_SETOR_AUTORIZACAO, '; ') WITHIN GROUP (ORDER BY TP_SETOR_AUTORIZACAO) TP_SETOR_AUTORIZACAO
        ,LISTAGG(TP_SETOR_AGENDAMENTO, '; ') WITHIN GROUP (ORDER BY TP_SETOR_AGENDAMENTO) TP_SETOR_AGENDAMENTO
        ,LISTAGG(DS_CONSIDERACOES, '; ') WITHIN GROUP (ORDER BY DS_CONSIDERACOES) DS_CONSIDERACOES
        ,LISTAGG(TP_DEMANDA_AREA, '; ') WITHIN GROUP (ORDER BY TP_DEMANDA_AREA) TP_DEMANDA_AREA
        ,LISTAGG(TP_ST_RELACIONAMENTO, '; ') WITHIN GROUP (ORDER BY TP_ST_RELACIONAMENTO) TP_ST_RELACIONAMENTO
        ,LISTAGG(DS_ST_RELACIONAMENTO, '; ') WITHIN GROUP (ORDER BY DS_ST_RELACIONAMENTO) DS_ST_RELACIONAMENTO
        ,LISTAGG(TP_ST_CADASTRO, '; ') WITHIN GROUP (ORDER BY TP_ST_CADASTRO) TP_ST_CADASTRO
        ,LISTAGG(DS_ST_CADASTRO, '; ') WITHIN GROUP (ORDER BY DS_ST_CADASTRO) DS_ST_CADASTRO
        ,LISTAGG(TP_ST_COMERCIAL, '; ') WITHIN GROUP (ORDER BY TP_ST_COMERCIAL) TP_ST_COMERCIAL
        ,LISTAGG(DS_ST_COMERCIAL, '; ') WITHIN GROUP (ORDER BY DS_ST_COMERCIAL) DS_ST_COMERCIAL
        ,LISTAGG(TP_ST_REPMED, '; ') WITHIN GROUP (ORDER BY TP_ST_REPMED) TP_ST_REPMED
        ,LISTAGG(DS_ST_REPMED, '; ') WITHIN GROUP (ORDER BY DS_ST_REPMED) DS_ST_REPMED
        ,LISTAGG(TP_ST_REGULACAO, '; ') WITHIN GROUP (ORDER BY TP_ST_REGULACAO) TP_ST_REGULACAO
        ,LISTAGG(DS_ST_REGULACAO, '; ') WITHIN GROUP (ORDER BY DS_ST_REGULACAO) DS_ST_REGULACAO
        ,LISTAGG(TP_ST_INTEL_MERC, '; ') WITHIN GROUP (ORDER BY TP_ST_INTEL_MERC) TP_ST_INTEL_MERC
        ,LISTAGG(DS_ST_INTEL_MERC, '; ') WITHIN GROUP (ORDER BY DS_ST_INTEL_MERC) DS_ST_INTEL_MERC
        ,LISTAGG(TP_REVISITA, '; ') WITHIN GROUP (ORDER BY TP_REVISITA) TP_REVISITA
        ,LISTAGG(DS_OBS_REVISITA, '; ') WITHIN GROUP (ORDER BY DS_OBS_REVISITA) DS_OBS_REVISITA
        ,LISTAGG(DT_REVISITA, '; ') WITHIN GROUP (ORDER BY DT_REVISITA) DT_REVISITA
        FROM (
        /*CAMADA INTERNA*/
        SELECT * FROM (
            /*CAMADA NÃšCLEO*/
            SELECT 
                DISTINCT UPPER (C.DS_CAMPO) DS_CAMPO
                , C.CD_METADADO
                ,VD.CD_DOCUMENTO
                ,RC.CD_REGISTRO
                ,DBMS_LOB.SUBSTR(RC.lo_conteudo,4000,1) DADO

                FROM
                EDITOR.EDITOR_REGISTRO_CAMPO RC
                ,EDITOR.EDITOR_CAMPO C
                ,EDITOR.EDITOR_REGISTRO R
                ,EDITOR.EDITOR_LAYOUT L
                ,EDITOR.EDITOR_VERSAO_DOCUMENTO VD

                WHERE R.CD_REGISTRO = RC.CD_REGISTRO
                AND L.CD_LAYOUT = R.CD_LAYOUT
                AND RC.CD_CAMPO = C.CD_CAMPO
                AND R.CD_LAYOUT = L.CD_LAYOUT
                AND L.CD_VERSAO_DOCUMENTO = VD.CD_VERSAO_DOCUMENTO
                AND VD.CD_DOCUMENTO = 7
                AND C.CD_METADADO IN (
                    '690','702','708','69957','80782','80719','80722','80725','80728','80731','80734',
                    '80737','80740','715','69954','80779','80776','80773','80770','80767','80764','80761',
                    '80758','80755','80752','80749','691','701','705','689','703','698','706','700','70271',
                    '70274','70277','70280','70285','70288','70294','70297','79385'
                    )
                ORDER BY 4 DESC
        )
            PIVOT (MAX (DADO) FOR CD_METADADO IN  ('690'       AS CD_CRM
                                                    ,'702'      AS NM_MED
                                                    ,'708'      AS DT_VISITA
                                                    ,'69957'    AS TP_ESPMED
                                                    ,'80782'    AS SN_ATUACAO
                                                    ,'80719'    AS TP_HOSP_RHP
                                                    ,'80722'    AS TP_HOSP_MEMORIAL
                                                    ,'80725'    AS TP_HOSP_ESPERANCA
                                                    ,'80728'    AS TP_HOSP_STJOANA
                                                    ,'80731'    AS TP_HOSP_SMARCOS
                                                    ,'80734'    AS TP_HOSP_JAIME_FONTE
                                                    ,'80737'    AS TP_HOSP_OUTROS
                                                    ,'80740'    AS DS_HOSP_OUTROS
                                                    ,'715'      AS TP_AVALIAR_RHP
                                                    ,'69954'    AS TP_CLASS_MD_VISITA
                                                    ,'80779'    AS TP_SETOR_REL_MED
                                                    ,'80776'    AS TP_SETOR_ORCAMENTO
                                                    ,'80773'    AS TP_SETOR_REPASSE
                                                    ,'80770'    AS TP_SETOR_TRANSP
                                                    ,'80767'    AS TP_SETOR_NUTRICAO
                                                    ,'80764'    AS TP_SETOR_FATURANENTO
                                                    ,'80761'    AS TP_SETOR_COMERCIAL
                                                    ,'80758'    AS TP_SETOR_CAD_MED
                                                    ,'80755'    AS TP_SETOR_BLOCO_CIR
                                                    ,'80752'    AS TP_SETOR_AUTORIZACAO
                                                    ,'80749'    AS TP_SETOR_AGENDAMENTO
                                                    ,'691'      AS DS_CONSIDERACOES
                                                    ,'701'      AS TP_DEMANDA_AREA
                                                    ,'705'      AS TP_ST_RELACIONAMENTO
                                                    ,'689'      AS DS_ST_RELACIONAMENTO
                                                    ,'703'      AS TP_ST_CADASTRO
                                                    ,'698'      AS DS_ST_CADASTRO
                                                    ,'706'      AS TP_ST_COMERCIAL
                                                    ,'700'      AS DS_ST_COMERCIAL 
                                                    ,'70271'    AS TP_ST_REPMED
                                                    ,'70274'    AS DS_ST_REPMED
                                                    ,'70277'    AS TP_ST_REGULACAO
                                                    ,'70280'    AS DS_ST_REGULACAO
                                                    ,'70285'    AS TP_ST_INTEL_MERC
                                                    ,'70288'    AS DS_ST_INTEL_MERC
                                                    ,'70294'    AS TP_REVISITA
                                                    ,'70297'    AS DS_OBS_REVISITA
                                                    ,'79385'    AS DT_REVISITA

            ))
    )
    GROUP BY CD_REGISTRO
    ORDER BY CD_REGISTRO DESC
)

WHERE DT_VISITA  <> 'null'
ORDER BY DT_VISITA desc
;
/*
690 - CRM
702 - NOME MEDICO
708 - DATA VISITA
69957 - ESPECIALIDA MÃ‰DICA
80782 - ATUAÃ‡ÃƒO RHP ? SIM OU NÃƒO
80719 - CHECK PORTUGUES
80722 - CHECK MEMORIAL
80725 - CHECK ESPERANÃ‡A
80728 - CHECK SANTA JOANA
80731 - CHECK SÃƒO MARCOS
80734 - CHECK JAYME DA FONTE	
80737 - CHECK OUTROS HOSPITAL
80740 - TEXT OUTROS HOSPITAIS	
715 - RB AVALIA RHP
69954 - RB CLASSIFICAÃ‡ÃƒO MÃ‰DICA NA VISITA
80779 - SETOR RELACIONAMENTO MÃ‰DICO	
80776 - SETOR ORÃ‡AMENTO	
80773 - SETOR REPASSE	
80770 - SETOR TRANSPORTE	
80767 - SETOR NUTRIÃ‡ÃƒO RELAC	
80764 - SETOR FATURAMENTO	
80761 - SETOR COMERCIAL	
80758 - SETOR CADASTRO MÃ‰DICO	
80755 - SETOR BLOCO	
80752 - SETOR AUTORIZAÃ‡ÃƒO	
80749 - SETOR AGENDAMENTO
691 - TEXT CONSIDERAÃ‡Ã•ES VISITA
701 - TP DEMANDA (SIM OU NÃƒO)
705 - TP RELACIONAMENTO
689 - TXT RELACIONAMENTO
703 - TP CADASTRO
698 - TXT CADASTRO
706 - TP COMERCIAL
700 - TXT COMERCIAL
70271 - TP REPASSE MEDICO
70274 - TXT REPASSE MEDICO
70277 - TP REGULAÃ‡ÃƒO
70280 - TXT REGULAÃ‡ÃƒO
70285 - TP INTELIGÃŠNCIA MERCADO
70288 - TXT INTELIGÃŠNCIA MERCADO
70294 - TP REVISITA MEDICA (SIM OU NÃƒO)
70297 - TXT REVISITA MEDICA
79385 - DATA REVISITA MEDICA
*/