---[RLM]_POC2_BUSCA_ATIVA_CLASSIFICAÇÃO_MED------
SELECT 
    SETOR_AGE_CIR
    ,SETOR_AUT_CIR
    ,SETOR_BLOCO_CIR
    ,SETOR_CAD_MEDICO
    ,SETOR_COMERCIAL
    ,SETOR_FATUR
    ,SETOR_NUTRI
    ,SETOR_TRANSP
    ,SETOR_REPASSE_HONO
    ,SETOR_ORCAMENTO
    ,SETOR_RELAC_MEDICO
    ,SETOR_TECNOLOGIA
FROM EDITOR_CUSTOM.HIST_VISITA_MED

    WHERE CRM = 16492
    AND DATA_VISITA = '07/06/2023'
    AND MEDICO = 'ANA BEATRIZ MEDEIROS LINS DE ALBUQUERQUE'