SELECT DISTINCT 
  AVC.CD_AVISO_CIRURGIA,
  AVC.DT_AVISO_CIRURGIA,
  AVC.NM_PACIENTE,
  AVC.DT_REALIZACAO,
  AVC.CD_PACIENTE,
  AVC.CD_ATENDIMENTO,
  AVC.DT_CONFIRMACAO,
  MVI.CD_MOV_INT,
  (SELECT DS_UNID_INT FROM DBAMV.UNID_INT WHERE CD_UNID_INT = LEI.CD_UNID_INT ) AS UNID_INT,
  MVI.CD_LEITO,
  LEI.DS_LEITO,
  MVI.DT_MOV_INT,
  MVI.HR_MOV_INT,
  MVI.DS_LOCAL
FROM 
  DBAMV.AVISO_CIRURGIA AVC,
  DBAMV.MOV_INT MVI,
  DBAMV.LEITO LEI
WHERE MVI.CD_ATENDIMENTO  = AVC.CD_ATENDIMENTO
AND AVC.DT_REALIZACAO    < MVI.HR_MOV_INT
AND MVI.DT_MOV_INT        = MVI.HR_MOV_INT
AND LEI.CD_LEITO          = MVI.CD_LEITO
AND TRUNC (DT_REALIZACAO) > '28/03/2024'
--AND NM_PACIENTE LIKE 'MARCIA %'
ORDER BY NM_PACIENTE, HR_MOV_INT
--CD_PACIENTE TESTE 304971
       /
SELECT *
FROM ALL_TAB_COLUMNS
WHERE COLUMN_NAME LIKE '%LEI%'
AND OWNER = 'DBAMV'
ORDER BY 1 ;
SELECT * FROM DBAMV.MOV_INT
