SELECT 
AHP.PROC_INST_ID_, 
SUBSTR (AHP.BUSINESS_KEY_,22) ID_,
DECODE (AHP.PROC_DEF_KEY_,'szOZGBvt00ZLw7oDw_4N5B','WHATSAPP - CHAT') FLUXO,
TO_DATE (TRUNC(AHP.START_TIME_)) AS DATE_,
AHP.START_TIME_, 
AHP.END_TIME_, 
AHP.STATE_,
AHV.WMOVLEI_NR_FONE_CONTATO,
AHV.WMOVLEI_DS_LEITO,
AHV.WMOVLEI_CD_PRESTADOR,
AHV.WMOVLEI_NM_PACIENTE,
AHV.WMOVLEI_DS_UNID_INT,
AHV.WMOVLEI_BOT_API_QUIZ_ID,
AHV.WMOVLEI_BOT_API_PHONE
FROM
    (
        select * From(
                select
                    PROC_INST_ID_,
                    name_,
                    TEXT_
                from
                    engine.act_hi_varinst
                order by
                    2
            ) ahv 
            PIVOT (
                MAX(TEXT_) FOR name_ IN (
                    'NR_FONE_CONTATO' AS WMOVLEI_NR_FONE_CONTATO,
                    'DS_LEITO' AS WMOVLEI_DS_LEITO,
                    'CD_PRESTADOR' AS WMOVLEI_CD_PRESTADOR,
                    'NM_PACIENTE' AS WMOVLEI_NM_PACIENTE,
                    'DS_UNID_INT' AS WMOVLEI_DS_UNID_INT,
                    'BOT_API_QUIZ_ID' AS WMOVLEI_BOT_API_QUIZ_ID,
                    'BOT_API_PHONE' AS WMOVLEI_BOT_API_PHONE
                        )
                     )
    ) AHV, ENGINE.ACT_HI_PROCINST AHP
        WHERE AHP.PROC_INST_ID_ = AHV.PROC_INST_ID_
        AND AHP.PROC_DEF_KEY_ IN('szOZGBvt00ZLw7oDw_4N5B')--Whatsapp ChatBoot                

order by AHP.START_TIME_ desc , AHP.END_TIME_ desc
;

SELECT 
AHP.PROC_INST_ID_, 
SUBSTR (AHP.BUSINESS_KEY_,22) ID_,
DECODE (AHP.PROC_DEF_KEY_,'szOZGBvt00ZLw7oDw_4N5B','WHATSAPP - CHATBOOT') FLUXO,
AHP.START_TIME_, 
AHP.END_TIME_, 
AHP.STATE_,
AHV.*
from ENGINE.ACT_HI_PROCINST AHP, engine.act_hi_varinst AHV
WHERE AHP.PROC_INST_ID_ = AHV.PROC_INST_ID_
        AND AHP.PROC_DEF_KEY_ IN('szOZGBvt00ZLw7oDw_4N5B')--Whatsapp ChatBoot      
        AND AHP.PROC_INST_ID_ = 'fe7070eb-e87a-11ee-9252-0242ac120016'

order by AHP.START_TIME_ desc , AHP.END_TIME_ desc
;
CREATE TABLE EDITOR_CUSTOM.CHATBOT_TI(
VCD_PESQUISA_FLOW NUMBER 
,NM_PESQUISA_FLOW VARCHAR2 (150) --BUSINESS_KEY_CASE_INSENSITIVE
,CD_ATEND_SAC VARCHAR2 (150)     --
,VPERG_1 VARCHAR2 (150)
,VJUST_1 VARCHAR2 (150)
,VPERG_2 VARCHAR2 (150)
,VJUST_2 VARCHAR2 (150)
,VPERG_3 VARCHAR2 (150)
,VJUST_3 VARCHAR2 (150)
)
;
CREATE SEQUENCE EDITOR_CUSTOM.SEQ_CHATBOT_TI
  INCREMENT BY 1 MAXVALUE 999999 CYCLE;
;
CREATE OR REPLACE PROCEDURE EDITOR_CUSTOM.PRC_CHATBOT_TI(
P_VCD_PESQUISA_FLOW NUMBER 
,P_NM_PESQUISA_FLOW VARCHAR2 --BUSINESS_KEY_CASE_INSENSITIVE
,P_CD_ATEND_SAC VARCHAR2
,P_VPERG_1 VARCHAR2
,P_VJUST_1 VARCHAR2
,P_VPERG_2 VARCHAR2
,P_VJUST_2 VARCHAR2
,P_VPERG_3 VARCHAR2
,P_VJUST_3 VARCHAR2
)IS 
BEGIN
INSERT INTO EDITOR_CUSTOM.CHATBOT_TI(
  VCD_PESQUISA_FLOW, 
  NM_PESQUISA_FLOW, 
  CD_ATEND_SAC, 
  VPERG_1, 
  VJUST_1, 
  VPERG_2, 
  VJUST_2, 
  VPERG_3, 
  VJUST_3
  )
VALUES (
 editor_custom.SEQ_CHATBOT_TI.NEXTVAL
  ,P_NM_PESQUISA_FLOW
  ,P_CD_ATEND_SAC 
  ,P_VPERG_1 
  ,P_VJUST_1 
  ,P_VPERG_2 
  ,P_VJUST_2 
  ,P_VPERG_3 
  ,P_VJUST_3 
  );
  COMMIT;
  END;
/

 
SELECT EDIOTR_CUSTOM.SEQ_CHATBOT_TI.NEXTVAL FROM DUAL
SELECT editor_custom.SEQ_CHATBOT_TI.NEXTVAL FROM DUAL



CREATE SEQUENCE editor_custom.SEQ_CHATBOT_TI
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  INCREMENT BY 1
  START WITH 1
  NOCYCLE
  NOORDER
  NOCACHE
/
  
 -- DROP SEQUENCE EDITOR_CUSTOM.SEQ_CHATBOT_TI
 