SELECT 
SUBSTR (AHP.BUSINESS_KEY_,41) AS ID_,
TRUNC(AHP.START_TIME_) AS DATE_,
AHP.START_TIME_, 
AHP.END_TIME_, 
AHP.STATE_,
AHV.CD_EDITOR,
AHV.CD_DRT_REGISTRANTE,
(SELECT MAX (NM_USUARIO) FROM DBASGU.USUARIOS WHERE CD_USUARIO = AHV.CD_DRT_REGISTRANTE ) AS NM_REGISTRANTE,
AHV.CD_SOLICITANTE,
AHV.NM_SOLICITANTE,
AHV.DS_SOLIC_CARGO,
AHV.DS_SETOR,
AHV.DT_SOLICITACAO,
AHV.NR_RAMAL,
AHV.DS_EMAIL,
AHV.DS_JUSTIFICATIVA,
AHV.DS_FORNECEDORES,
AHV.SN_MOT_SUBSTITUICAO,
AHV.DS_MOT_SUBSTITUICAO,
AHV.SN_EQUIPAMENTOS,
AHV.DS_EQUIPAMENTOS,
AHV.SN_OUTROS_HOSP,
AHV.DS_OUTROS_HOSP,
AHV.NR_VLORCADO,
CASE WHEN AHV.TP_RETORNO_CUSTOS = 'true' THEN 1 ELSE 0  END AS TP_RETORNO_CUSTOS,
CASE WHEN AHV.TP_RETORNO_EFICIENCIA = 'true' THEN 1 ELSE 0 END AS TP_RETORNO_EFICIENCIA,
CASE WHEN AHV.TP_RETORNO_NPS = 'true' THEN 1 ELSE 0 END AS TP_RETORNO_NPS,
CASE WHEN AHV.TP_RETORNO_RECEITA = 'true' THEN 1 ELSE 0 END AS TP_RETORNO_RECEITA,
CASE WHEN AHV.TP_RETORNO_OUTROS = 'true' THEN TO_CHAR (DS_RETORNO_OUTROS) ELSE NULL END AS DS_RETORNO_OUTROS,
AHV.TP_APROVACAO,
AHV.DS_APROV_JUSTIF
FROM (
select
    *
from
    (
        select
            PROC_INST_ID_,
            name_,
            TEXT_
        from
            engine.act_hi_varinst
        order by
            2
    ) ahv PIVOT (
        MAX(TEXT_) FOR name_ IN (
                'PAR_REGISTRY_ID' AS CD_EDITOR,
                'INSTANCE_USER' AS CD_DRT_REGISTRANTE,
                'DRT_NV_TEC300' AS CD_SOLICITANTE,
                'OBS_VAL_NV_TEC989' AS DS_APROV_JUSTIF,
                'EMAIL_NV_TEC51' AS DS_EMAIL,
                'TX_AQUISICAO_NV_TEC39' AS DS_EQUIPAMENTOS,
                'EMPRESAS_FORNECEM_NV_TEC257' AS DS_FORNECEDORES,
                'DESCREVER_TEC_NV_TEC916' AS DS_JUSTIFICATIVA,
                'QUAL_MOTIVO_NV_TEC608' AS DS_MOT_SUBSTITUICAO,
                'EMPRESAS_UTILIZAM_NV_TEC928' AS DS_OUTROS_HOSP,
                'SETOR_NV_TEC271' AS DS_SETOR,
                'FUNCAO_NV_TEC190' AS DS_SOLIC_CARGO,
                'DT_REGISTRO_NV_TEC141' AS DT_SOLICITACAO,
                'NM_NV_TEC321' AS NM_SOLICITANTE,
                'RAMAL_NV_TEC924' AS NR_RAMAL,
                'VALOR_ORCADO_RB_NV_TEC62' AS NR_VLORCADO,
                'SN_FERRAMENTAS_NV_TEC164' AS SN_EQUIPAMENTOS,
                'AQUISICAO_NV_TEC36' AS SN_MOT_SUBSTITUICAO,
                'RB_OUTROS_HOSP_UTILI825' AS SN_OUTROS_HOSP,
                'RB_VAL_APROV_NAPROV657' AS TP_APROVACAO,
                'CK_REDUCAO_CUSTOS101' AS TP_RETORNO_CUSTOS,
                'CK_AUMENTO_EFICIENCIA346' AS TP_RETORNO_EFICIENCIA,
                'CK_AUMENTO_NPS_NV_TEC811' AS TP_RETORNO_NPS,
                'CK_OUTRO453' AS TP_RETORNO_OUTROS,
                'CK_AUMENTO_RECEITA_NV_TEC757' AS TP_RETORNO_RECEITA,
                'CT_ESPE_NV_TEC852' AS DS_RETORNO_OUTROS

        )   )
    )AHV,
ENGINE.ACT_HI_PROCINST AHP
WHERE
    AHP.PROC_INST_ID_ = AHV.PROC_INST_ID_
    AND AHP.START_TIME_ BETWEEN TO_DATE ('01/09/2023', 'DD/MM/YYYY')AND SYSDATE + 1
    AND  AHP.PROC_DEF_KEY_ = 'jMsT82feu0wc93jOcgv3Fi'
    
    order by start_time_ desc