
SELECT * FROM colunas
WHERE CD_TABELA IN ('SOL_COM','ORD_COM')
ORDER BY COLUNA;

SELECT count(*) FROM dbamv.ord_com
WHERE cd_sol_com IS NULL
AND DT_ORD_COM BETWEEN To_Date ('01062022', 'dd/mm/yyyy') AND To_Date ('30062022','dd/mm/yyyy')
GROUP BY cd_estoque
ORDER BY cd_estoque ASC;

SELECT
cd_ord_com,
dt_ord_com,
vl_total,
vl_desconto,
vl_perc_desconto
FROM dbamv.ord_com
WHERE cd_sol_com IS NULL
AND DT_ORD_COM BETWEEN To_Date ('01062022', 'dd/mm/yyyy') AND To_Date ('30062022','dd/mm/yyyy')
ORDER BY cd_ord_com;

SELECT
DT_ORD_COM DATA_COMPRA,
SUM(VL_TOTAL) SOMATORIO FROM dbamv.ord_com
WHERE cd_sol_com IS NULL
AND DT_ORD_COM BETWEEN To_Date ('01062022', 'dd/mm/yyyy') AND To_Date ('30062022','dd/mm/yyyy')
GROUP BY DT_ORD_COM
ORDER BY DT_ORD_COM ASC;

 --ESTRANGEIRAS: CD_ESTOQUE, CD_SOL_COM
 -- SOL_COM: CD_CONTA, CD_MOT_PED, CD_USUARIO,DT_SOL_COM, TP_SITUACAO, TP_SOL_COM, VL_TOTAL
 -- ORD_COM: CD_ESTOQUE, CD_ORD_COM, CD_SOL_COM, DS_ORDEM_DE_COMPRA, DT_ORD_COM, TP_SITUACAO,VL_TOTAL
SELECT
O.CD_ESTOQUE CODIGO_ESTOQUE,
E.DS_ESTOQUE DESCRICAO_ESTOQUE,
O.CD_ORD_COM CODIGO_COMPRA,
O.CD_SOL_COM CODIGO_SOLICITACAO,
O.DT_ORD_COM DATA_COMPRA,
Decode (O.TP_SITUACAO,'C','CANCELADO','T','ATENDIDA','L','PARCIAL','U','AUTORIZADA','N','NÃO AUTORIZADO','A','ABERTO')AS TIPO_SITUACAO,
O.VL_TOTAL VALOR_ORDEM,
S.CD_CONTA,
S.CD_MOT_PED MOTIVO_PEDIDO,
S.CD_USUARIO EXECUTANTE,
S.DT_SOL_COM DATA_SOLICITACAO,
Decode (S.TP_SITUACAO,'F','FECHADA','C','CANCELADA','N','LANÇAMENTO','A','ABERTA','P','PARCIAL','S','SOLICITADO') AS SITUACAO_SOLICITACAO,
S.TP_SOL_COM
FROM ORD_COM O
LEFT JOIN SOL_COM S ON S.CD_SOL_COM = O.CD_SOL_COM
LEFT JOIN ESTOQUE E ON E.CD_ESTOQUE = O.CD_ESTOQUE
WHERE DT_ORD_COM BETWEEN To_Date ('01062022', 'dd/mm/yyyy') AND To_Date ('30062022','dd/mm/yyyy')
AND O.CD_ORD_COM IN ('157323','160615'	,	'161066'	,	'160003'	,	'160727'	,
'160915',	'160348',	'160025',	'160658',
'160872',	'160724',	'160630',	'160057',
'160050',	'160022',	'161024',	'160770',
'159940',	'160340',	'160616',	'160769',
'160071',	'160056',	'160113',	'160347',
'158934',	'160576',	'159059',	'160573',
'161033',	'160664',	'160722',	'160368')
AND O.TP_SITUACAO <> 'C'
ORDER BY DATA_COMPRA
;

--C = CANCELADO, T = ATENDIDA, L = PACIAL, U = AUTORIZADA, N = NÃO AUTORIZADO, A = ABERTA
SELECT cd_ord_com, tp_situacao FROM ord_com
WHERE tp_situacao <> 'C'
AND tp_situacao <> 'T'
AND tp_situacao <> 'L'
AND tp_situacao <> 'U'
AND tp_situacao <> 'N'
AND tp_situacao <> 'A'
;

--F = FECHADA, C = CANCELADA, N = LANÇAMENTO, A = ABERTA, P = PARCIAL, S = SOLICITADO
SELECT cd_SOL_com, tp_situacao FROM SOL_com
WHERE tp_situacao <> 'F'
AND tp_situacao <> 'C'
AND tp_situacao <> 'N'
AND tp_situacao <> 'A'
AND tp_situacao <> 'P'
AND tp_situacao <> 'S'
;

SELECT
Decode (O.TP_SITUACAO,'C','CANCELADO','T','ATENDIDA','L','PARCIAL','U','AUTORIZADA','N','NÃO AUTORIZADO','A','ABERTO')AS TIPO_SITUACAO,
count (O.VL_TOTAL)FROM ORD_COM O
LEFT JOIN SOL_COM S ON S.CD_SOL_COM = O.CD_SOL_COM
WHERE DT_ORD_COM BETWEEN To_Date ('24042023', 'dd/mm/yyyy') AND To_Date ('26042023','dd/mm/yyyy')
AND S.CD_MOT_PED IS null
GROUP BY O.TP_SITUACAO
ORDER BY O.TP_SITUACAO ASC;

SELECT
O.CD_ESTOQUE CODIGO_ESTOQUE,
E.DS_ESTOQUE DESCRICAO_ESTOQUE,
O.CD_ORD_COM CODIGO_COMPRA,
O.CD_SOL_COM CODIGO_SOLICITACAO,
O.DT_ORD_COM DATA_COMPRA,
Decode (O.TP_SITUACAO,'C','CANCELADO','T','ATENDIDA','L','PARCIAL','U','AUTORIZADA','N','NÃO AUTORIZADO','A','ABERTO')AS TIPO_SITUACAO,
O.VL_TOTAL VALOR_ORDEM,
S.CD_CONTA,
S.CD_MOT_PED MOTIVO_PEDIDO,
S.CD_USUARIO EXECUTANTE,
S.DT_SOL_COM DATA_SOLICITACAO,
Decode (S.TP_SITUACAO,'F','FECHADA','C','CANCELADA','N','LANÇAMENTO','A','ABERTA','P','PARCIAL','S','SOLICITADO') AS SITUACAO_SOLICITACAO,
DECODE (S.TP_SOL_COM, 'P','PRODUTO','S','SERVIÇO') TIPO_SOLIC
FROM ORD_COM O
LEFT JOIN SOL_COM S ON S.CD_SOL_COM = O.CD_SOL_COM
LEFT JOIN ESTOQUE E ON E.CD_ESTOQUE = O.CD_ESTOQUE
WHERE DT_ORD_COM BETWEEN To_Date ('01062022', 'dd/mm/yyyy') AND To_Date ('30062022','dd/mm/yyyy')
ORDER BY DATA_COMPRA
;
