SELECT
    DISTINCT 
    AHC.PROC_DEF_KEY_,  --IDENTIFICADOR DA MODELAGEM DO PROCESSO
    AHC.ACT_TYPE_,      --CLASSIFICAÇÃO DO TIPO DE TAREFA
    AHC.ACT_NAME_,      --NOMECLATURA DA TAREFA
    AHV.NAME_,          --NOMECLATURA DA VARIAVEL DA TAREFA
    AHV.VAR_TYPE_,      --CLASSIFICAÇÃO DO TIPO DA VARIAVEL
    AHV.TEXT_,          /*E-MAIL ATRELADO AO CONTEUDO DA VARIAVEL*/
    AHV.STATE_,         /*STATUS DA VARIAVEL*/
    (SELECT  MAX(NAME_) FROM ENGINE.ACT_RE_PROCDEF WHERE KEY_ = AHC.PROC_DEF_KEY_)   "NOME PROCESSO",
    AHP.BUSINESS_KEY_,  /*IDENTIFICADOR DO PROCESSO*/
    AHP.START_TIME_,    /*ABERTURA DO PROCESSO*/
    AHP.END_TIME_,      /*FINALIZAÇÃO DO PROCESSO*/
    AHP.START_ACT_ID_,  /*IDENTIFICAÇÃO DO SERVIÇO ATRELADO AO INICIO DO PROCESSO*/
    AHP.END_ACT_ID_,    /*IDENTIFICAÇÃO DO SERVIÇO ATRELADO AO FINAL DO PROCESSO*/
    AHP.STATE_          /*STATUS DO PROCESSO INICIADO*/
FROM
    ENGINE.ACT_HI_ACTINST AHC,
    ENGINE.ACT_HI_PROCINST AHP,
    ENGINE.ACT_HI_VARINST AHV
WHERE
    AHP.PROC_INST_ID_ = AHC.PROC_INST_ID_
    AND AHV.PROC_INST_ID_ = AHC.PROC_INST_ID_
    
    AND AHC.ACT_TYPE_ = 'serviceTask'
    AND AHP.END_TIME_ BETWEEN TO_DATE ('25/03/2024', 'DD/MM/RRRR')
    AND SYSDATE
    AND UPPER (ACT_NAME_) NOT LIKE UPPER ('%Whats%')
    AND AHV.TEXT_ LIKE '%@%'
    AND AHV.NAME_ NOT IN ('INSTANCE_USER_EMAIL') /*DESCONSIDERAR E-MAIL CADASTRADO AO USUARIO DA APLICAÇÃO */
ORDER BY
    start_time_ desc;
    
    SELECT * FROM SYS.ALL_TAB_COLUMNS
    WHERE COLUMN_NAME LIKE '%_KEY_%'
    AND OWNER = 'ENGINE'
    ;
    --ACT_RE_PROCDEF ACT_RE_DECISION_DEF ACT_RU_TASK ACT_RU_JOBDEF
    SELECT * FROM ENGINE.ACT_RE_PROCDEF  
    