
SELECT SC.CD_SOL_COM,
       SC.CD_COTADOR,
       CT.DS_COTADOR,
       SC.CD_SETOR,
       ST.NM_SETOR,
       SC.NM_SOLICITANTE,
       DECODE (SC.TP_SITUACAO,'C','CANCELADA','F','FECHADA','A','ABERTA','N','LANÇAMENTO','P','PARCIAL','S','SOLICITADA') AS "STATUS SOL",
       SC.DT_SOL_COM,
       NVL (P.CD_PRODUTO,(SELECT OS.CD_SERVICO FROM DBAMV.ENT_SERV ES,DBAMV.ITENT_SERV IES, DBAMV.MANU_SERV OS
      WHERE IES.CD_ENT_SERV = ES.CD_ENT_SERV
      AND OS.CD_SERVICO = IES.CD_SERVICO
      AND ES.CD_ORD_COM = OC.CD_ORD_COM))CD_ITEM,
       NVL (P.DS_PRODUTO,(SELECT OS.NM_SERVICO FROM DBAMV.ENT_SERV ES,DBAMV.ITENT_SERV IES, DBAMV.MANU_SERV OS
      WHERE IES.CD_ENT_SERV = ES.CD_ENT_SERV
      AND OS.CD_SERVICO = IES.CD_SERVICO
      AND ES.CD_ORD_COM = OC.CD_ORD_COM))DS_ITEM,
       NVL (ISC.QT_SOLIC,0)QT_SOLIC,
       OC.CD_ORD_COM,
       OC.DT_ORD_COM,
       OC.DT_PREV_ENTREGA,
       DECODE (OC.TP_SITUACAO, 'C','CANCELADA','T','ATENDIDA','U','AUTORIZADA','L','PARCIAL','N','NÃO AUTORIZADO','A','ABERTA') AS "STATUS OC",
       NVL (OC.DT_AUTORIZAOC.DT_CANCELAMENTO
       
FROM DBAMV.SOL_COM SC,
     DBAMV.ORD_COM OC,
     DBAMV.ITSOL_COM ISC,
     DBAMV.PRODUTO P,
     DBAMV.COTADOR CT,
     DBAMV.SETOR ST
     

WHERE SC.CD_SOL_COM = OC.CD_SOL_COM(+)
AND SC.CD_SOL_COM = ISC.CD_SOL_COM(+)
AND ISC.CD_PRODUTO = P.CD_PRODUTO(+)
AND SC.CD_COTADOR = CT.CD_COTADOR
AND ST.CD_SETOR = SC.CD_SETOR

AND SC.NM_SOLICITANTE LIKE 'ESTEVAM%'

ORDER BY 1
;
SELECT * FROM ALL_TAB_COLUMNS
WHERE OWNER = 'DBAMV' 
AND COLUMN_NAME LIKE '%TP_SITUACAO%'
ORDER BY 2
--11400
;
--DBAMV.ENT_SERV || 
SELECT OS.CD_SERVICO, OS.NM_SERVICO FROM DBAMV.ENT_SERV ES,DBAMV.ITENT_SERV IES, DBAMV.MANU_SERV OS  -- CD_ORD_COM
WHERE IES.CD_ENT_SERV = ES.CD_ENT_SERV
AND OS.CD_SERVICO = IES.CD_SERVICO
AND ES.CD_ORD_COM = 244540
;
SELECT CD_ORD_COM, DT_ORD_COM, DT_PREV_ENTREGA, VL_TOTAL, DT_CANCELAMENTO, DT_AUTORIZACAO, TP_SITUACAO, CD_SOL_COM, SN_RESPONDIDA, SN_EMAIL_ENVIADO_PARA_FORN, TP_ORD_COM, SN_AUTORIZADO, DT_INTEGRA from ORD_COM
WHERE 
--TP_SITUACAO = 'U' 
--CD_ORD_COM = 244540
DT_AUTORIZACAO IS NOT NULL
ORDER BY DT_ORD_COM DESC